### ISSUE TITLE
openconfig-isis.yang: SPF timers are unclear

### ISSUE THREAD

**Issue by ghankins** [openconfig/public#100]
oc-ext:openconfig-version "0.3.3";

` |  +--rw spf`
 ` |  |  |  +--rw config`
  `|  |  |  |  +--rw spf-hold-interval?     uint64`
  `|  |  |  |  +--rw spf-first-interval?    uint64`
  `|  |  |  |  +--rw spf-second-interval?   uint64`

spf-hold-interval: SPF Hold Down time interval in milliseconds.  The definitions are unclear, is it the hold time that needs to expire before using the configured SPF intervals?

spf-second-interval: not clear if OpenConfig also uses this for the subsequent SPF runs.

**Comment by 3alexb** [comment]
spf-hold-interval: SPF Hold Down time interval in milliseconds. The definitions are unclear, is it the hold time that needs to expire before using the configured SPF intervals?
[ab] 
hold down before subsequent SPF run, i.e. spf-wait
spf-first-interval = initial-wait
spf-second-interval = second-wait

pls clarify what this means: "not clear if OpenConfig also uses this for the subsequent SPF runs"

**Comment by ghankins** [comment]
Thanks for clarification, it's clear now.
