### ISSUE TITLE
Clarification on 'in-pkts' definition across oc-if-ip and oc-if models

### ISSUE THREAD

**Issue by suhgopin** [openconfig/public#1000]
Hello, 

Could you clarify the 'in-pkts' definition across oc-if-ip and oc-if models?
Unlike oc-if.yang description of “in-pkts”, oc-if-ip.yang is not very explicit in saying it needs to include all (unicast,multicast,broadcast).
 
oc-if-ip.yang

> /interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/in-pkts
> 
> description:
> The total number of IP packets received for the specified address family, including those received in error
> nodetype: leaf (ro)
> type: oc-yang:counter64

 
oc-if.yang:

> /interfaces/interface/state/counters/in-pkts
> 
> description:
> The total number of packets received on the interface, including all unicast, multicast, broadcast and bad packets etc.
> nodetype: leaf (ro)
> type: oc-yang:counter64
 
Should in-pkts counter under oc-if-ip.yang account all unicast, multicast and broadcast packets like in oc-if.yang model?
If yes, could you update the definitions accordingly?

Regards,
Suhas

**Comment by dplore** [comment]
Yes,  `/interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/in-pkts` should include all IP unicast, multicast, broadcast and bad packets.

Usually I would ask the issue reported to submit a pull request to clarify the description.  But this one is so small, I'll happily do it.

**Comment by suhgopin** [comment]
Thank you, noted.

**Comment by dplore** [comment]
Fixed by #1072
