### ISSUE TITLE
What will expected behaviour for replace at intefaces level for openconfig-interface.yang

### ISSUE THREAD

**Issue by nijeshvp** [openconfig/public#1004]
Hello,

I need help to understand expected behaviour on below scenario.

Operation:  Replace at interfaces level using gnmi/netfconf . (openconfig-interfaces.yang)

If there are 10 interfaces in system, and we do replace at interfaces level with one interface config in request.
Do all 9 other interface will be removed from system and only one interface remain ?.

before  config : 10 interfaces   

netconf RPC: 

  </target> 
  <config>
  <interfaces xmlns="http://openconfig.net/yang/interfaces" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="replace">
 <interface>
  <name>Bundle-Ether1</name>
  <config>
  <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ieee8023adLag</type>
  <mtu>1200</mtu> 
  <enabled>true</enabled>
  </config> 
  </interface>
  </interfaces>
  </config> 
  </edit-config>

After RCP: only bundle config present with enabled true .

is this expected behaviour ?

**Comment by dplore** [comment]
Yes, this is the expected behavior.  gnmi Set with replace action should result in the config path tree looking exactly like what what set, including removing any existing configuration within the specified tree that is present.

**Comment by nijeshvp** [comment]
Thank you very much for quick reply .

if bundle-ether1 had vrf or qos configured earlier (which is from different yang model), before this RPC
And replace at interfaces request , have only "enabled" config .

After replace at interacts RPC, Does qos or vrf config also expected to present under bundle-ether1 ?
