### ISSUE TITLE
What will expected behaviour for replace at intefaces level for openconfig-interface.yang

### ISSUE THREAD

**Issue by nijeshvp** [openconfig/public#1005]
Thank you very much for quick reply .

if bundle-ether1 had vrf or qos configured earlier (which is from different yang model), before this RPC
And replace at interfaces request , have only "enabled" config .

After replace at interacts RPC, Does qos or vrf config also expected to present under bundle-ether1 ?

_Originally posted by @nijeshvp in https://github.com/openconfig/public/issues/1004#issuecomment-1820310857_

**Comment by dplore** [comment]
gNMI replace operates at the tree level, so a replace at /interfaces/interface replaces all config content at this level and below in the tree within the 'origin' specified.    Configuration within the /qos tree would not directly be affected.  

However, for example, if there are leaf-refs present in [/qos/interfaces/interface/interface-id](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-interfaces-interface-interface-id)  which refer to interfaces that are not present in the gnmi replace, then the server should reject the configuration with an error as the resulting configuration would have invalid leafrefs.
