### ISSUE TITLE
openconfig-isis.yang: state objects should be ro, not rw

### ISSUE THREAD

**Issue by ghankins** [openconfig/public#101]
I'm looking at version 0.2.1 of the openconfig-isis.yang model, and I found 10 state objects that are rw.  It seems like they should be ro.

`|     +--rw system-level-counters`
`      +--rw circuit-counters`
`      |     +--rw packet-counters`
`      |     |  +--rw lsp`
`      |     |  +--rw iih`
`      |     |  +--rw ish`
`      |     |  +--rw esh`
`      |     |  +--rw psnp`
`      |     |  +--rw cnsp`
`      |     |  +--rw unknown`

**Comment by 3alexb** [comment]
you are a number of versions behind. can you pls check 0.3.3

**Comment by ghankins** [comment]
The same objects are are rw in version 0.3.3 as well.
