### ISSUE TITLE
wrong prefix for import mpls types - should be oc-mpls-types

### ISSUE THREAD

**Issue by sgrazian** [openconfig/public#102]
line 10 of openconfig-isis-routing.yang - version 0.3.3

import openconfig-mpls-types { prefix oc-mplst; }

and line 11 of openconfig-segment-routing.yang - version 0.0.3

import openconfig-mpls-types { prefix "oc-mpls-t"; }

are not consistent with prefix defined in module openconfig-mpls-types - version 2.4.1 - line 8

prefix "oc-mpls-types"; 

Problem possibly apply for other modules as well

**Comment by aashaikh** [comment]
As we've noted in other similar issues, having the same prefix is not required in YANG -- this is likely a problem in the tooling you're using to parse / compile YANG modules.

**Comment by 3alexb** [comment]
@robshakir pls comment

**Comment by robshakir** [comment]
Thanks Alex. Sorry I missed the response -- this is something that should be supported by YANG tooling. @sgrazian -- can you confirm what toolchain does not support this please?
