### ISSUE TITLE
Are there different counters for next-hop programming errors?

### ISSUE THREAD

**Issue by rkrishna-git** [openconfig/public#1025]
https://github.com/openconfig/public/blob/71a14c9e3ec6abaf1dbbf43efb542a5c60060937/release/models/network-instance/openconfig-programming-errors.yang#L64C1-L64C1

Does “failed programming” indicates installation of route prefix installation failures only? Are there different counters planned for next-hop installation failures?"

**Comment by dplore** [comment]
This is a good question.   @akalluru1, any comments?  How should an error adding a NH or NHG be represented?

**Comment by akalluru1** [comment]
I'll defer to @mayukh288 on this one.

**Comment by sujitkumarsah** [comment]
@rkrishna-git yes, “failed programming” indicates installation of route prefix installation failures only..AFAIK, there were no immediate plans for representing next-hop installation failures.. Mayukh, please correct me there is any change of plan..
