### ISSUE TITLE
Proposal: Rename repository to reflect actual content/intent

### ISSUE THREAD

**Issue by earies** [openconfig/public#1029]
It's now been some years since the model developments underwent a private -> public repository publish so am throwing out the proposal to reconcile the repository name to something more meaningful to reflect the actual content under the OpenConfig project

Suggestions:

* models
* data-models
* yang

**Comment by dplore** [comment]
It is true that the 'public' repository is now the only OpenConfig Yang model repository, and not just a public accessible copy of a private models repository.

I appreciate any broader input on what the impact of renaming the repository is.  For us, renaming the repository causes quite a bit of churn to handle the renaming and the benefits are not clear.

**Comment by earies** [comment]
When a repository is renamed, redirects are handled indefinitely however if there is any dependency on hard-coding the old name as a directory anywhere from a new clone, etc... this would need to be adapted.

https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

The only real benefit here is naming it to reflect the actual content as "public" is not intuitive

**Comment by dplore** [comment]
Reviewed at the OC operators meeting.  At the moment, there is not consensus to rename the repository.
