### ISSUE TITLE
container authentication may be renamed to hello-authentication in isis-interface-group

### ISSUE THREAD

**Issue by sgrazian** [openconfig/public#103]
In module openconfig-isis.yang - version 0.3.3 hello-authentication configuration is defined by grouping isis-hello-authentication-group. This is used within grouping isis-interface-group in container authentication and within grouping isis-interface-level-group in container hello-authentication. Considering that you have also grouping isis-authentication-group used in container authentication, maybe container  authentication in grouping isis-interface-group could be renamed to hello-authentication for consistency.

**Comment by 3alexb** [comment]
ack, makes sense. changes will be as per below:

 grouping isis-interface-group {
..
    container hello-authentication {
      description
        "This container defines ISIS authentication.";

      uses isis-hello-authentication-group;
    }
..
