### ISSUE TITLE
Questions about /network-instances/network-instance/afts/ethernet

### ISSUE THREAD

**Issue by mikewiebe** [openconfig/public#1033]
We have a few questions about mapping for ethernet based forwarding entries under `/network-instances/network-instance/afts/ethernet/mac-entry`.

* Based on our understanding this should represent the Hardware mac table (both local and remote mac-entries).  Is that understanding correct?
* What kind of metadata should be carried in this property?
    * /network-instances/network-instance/afts/ethernet/mac-entry/state/entry-metadata

**Comment by mikewiebe** [comment]
Hi @dplore, I see this was added to the OC operator review last month.  Was there any discussion on this topic?

**Comment by dplore** [comment]
Hi @mikewiebe you are correct, this is the (abstract) hardware mac entry.

I am not sure what people had in mind for `/network-instances/network-instance/afts/ethernet/mac-entry/state/entry-metadata`.  Typically these fields are opaque blobs that are implementation / out-of-band defined data.

**Comment by dplore** [comment]
Looking at the git blame, I don't see any other insight into the content of the `entry-metadata` leaf:
https://github.com/openconfig/public/commit/2208d7ea0cd5e27dbc0bd13b32035e58af31b161
