### ISSUE TITLE
 update the description of  tunnel-src-ip-address leaf in openconfig-aft-common.yang file

### ISSUE THREAD

**Issue by krishna-juniper** [openconfig/public#1040]
https://github.com/openconfig/public/blob/master/release/models/aft/openconfig-aft-common.yang#L272

Description of tunnel-src-ip-address is confusing. It can be used to populate gre tunnel src address. can we update the description to make it specific to EVPN/VXLAN?

https://github.com/openconfig/public/pull/1038#issuecomment-1915008593

**Comment by dplore** [comment]
Agreed that the current description allows for broad use and interpretation for this leaf.  https://github.com/openconfig/public/pull/570 which added this leaf only contemplated the VXLAN use case.  In concept it seems like any encapsulation that uses IP as the outer header might be expected to populate this leaf.   

I'd appreciate feedback from the community on the feasibility of supporting this given the current description, or if we should narrow it to only certain use cases which could include only VXLAN.

**Comment by robshakir** [comment]
I think that this is a reasonable backwards compatible change, but what we perhaps should do is restructure the contents of this container to be grouped by tunnel type per @romeyod's previous suggestion.

This will be backwards incompatible and has impact in gRIBI, but we could start this work now and just mark the other leaves as deprecated. The suggestions thus far would be to create `mpls`, and `vxlan`, `ip-in-ip` already has its own container, and `gre` will based on #1038.
