### ISSUE TITLE
Incorrect path at when statement in 'openconfig-mpls-rsvp' model

### ISSUE THREAD

**Issue by hgeriki** [openconfig/public#105]
Seeing the below errors due to the when statement in 'openconfig-mpls-rsvp' model. Could you please look into this. This is noticed at few more when statements in the model.

yang/openconfig-mpls-rsvp.yang:510: error: the node 'mpls' from module 'openconfig-network-instance' is not found                                                                                   
yang/openconfig-mpls-rsvp.yang:510: error: the node 'mpls' from module 'openconfig-network-instance' is not found                                                                                   
yang/openconfig-mpls-rsvp.yang:510: error: the node 'tunnel' from module 'openconfig-mpls' (in node 'constrained-path' from 'openconfig-mpls') is not found                                         
yang/openconfig-mpls-rsvp.yang:510: error: the node 'tunnel' from module 'openconfig-mpls' (in node 'constrained-path' from 'openconfig-mpls') is not found                         

Error at:
----------
'when "/mpls/lsps/constrained-path/tunnel/config" +"/signaling-protocol = 'PATH_SETUP_RSVP'" {'

From model:
--------------
grouping rsvp-p2p-tunnel-attributes_config {
    description
      "properties of RSPP point-to-point paths";

    leaf source {
      when "/mpls/lsps/constrained-path/tunnel/config" +
        "/signaling-protocol = 'PATH_SETUP_RSVP'" {
        description
          "When the signaling protocol is RSVP-TE ";
      }
      type inet:ip-address;
      description
        "RSVP-TE tunnel source address";
    }

**Comment by robshakir** [comment]
Thanks -- this looks to be an issue of the paths not having been updated to relative paths. We'll make a fix for this and release a new version of the model.

Thanks for highlighting the issue.

**Comment by LeonGWang** [comment]
I believe this is fixed by commit 5dc792b
