### ISSUE TITLE
Segment Routing (SR) Policy Candidate Path configuration

### ISSUE THREAD

**Issue by jardel-lucca-venko** [openconfig/public#1052]
Hello,

I'm trying to conceive Segment Routing (SR) Policy Candidate Path configuration as defined in [RFC9256](https://datatracker.ietf.org/doc/html/rfc9256#name-candidate-path-and-segment-), using OpenConfig datamodel.

As mentioned in #718, there is a quite similar structure (`.../network-instance/segment-routing/te-policies/te-policy/candidate-paths`, however it is read-only.

Also according to #718, we can configure SR Policy via `openconfig-pf-srte`, but it does not seem to support candidate paths.

Is there anyway I could statically configure candidate paths with distinct preferences in SR Policies?

If not, is there any plan to add this support in the future? What about dynamic paths?

Thanks.
Jardel Lucca

**Comment by dplore** [comment]
Thanks for this comment.  Indeed OC does not currently have these paths.  I invite you to make a contribution which adds them!    To get started you don't even have to write the yang.  You could just propose a list of paths you think will cover your use case and reference at least 2 implementations that support the functionality you're proposing to be added.  If there is rough consensus on that, we can move on the writing the yang.

**Comment by jardel-lucca-venko** [comment]
@dplore thank you very much. I'll work on this.
