### ISSUE TITLE
BGP&OSPF：no route advertisement is defined？

### ISSUE THREAD

**Issue by andersliuc** [openconfig/public#106]
Hi， I am confused whether the route advertisement is defined in bgp and ospf models like the CLI “network” in Cisco. Is that in route-policy model?

**Comment by robshakir** [comment]
This is defined in the local routing model as aggregates. The network
instance model's table connections is then used to redistribute the routes
into the relevant protocols.  Please take a look and see if this makes
sense to you.

r.

**Comment by andersliuc** [comment]
Thanks！It makes sense to me！

**Comment by andersliuc** [comment]
Hi，I have a new question showed below:
I want to advertise a route through BGP.
As the method you mentioned above, I firstly defined route in the local routing model as aggregates，then I use the table connection with leaf of src protocol,dst protocol and address family，but there is no attribute relate to which route I want to redistribute in the table connection (in other words, I defined many routes though aggregates and I just want to advertise one of them in bgp).
So how to realize that？Many thanks!

**Comment by robshakir** [comment]
In `table-connection/config` we have an `import-policy` leaf, this means that we can specify a policy that will match the particular route that is created as an aggregate. I think that this should allow such filtering.
