### ISSUE TITLE
OpenConfig Support for Configurable Media-Channel Compensation Range and ASE recovery hysteresis

### ISSUE THREAD

**Issue by kcroussore** [openconfig/public#1067]
This proposal would add 3 configurable parameters to the existing [openconfig-wavelength-router](https://github.com/openconfig/public/blob/master/release/models/optical-transport/openconfig-wavelength-router.yang) model (listed below with proposed names):
A leaf:  max-undershoot-compensation
A leaf: max-overshoot-compensation
A leaf: ase-recovery-hysteresis

The new parameters would be added in the following path:
“wavelength-router/media-channels/channel[index]/config/”, similar to the existing parameter “attenuation-control-mode”.

The purpose of the new parameters is to enable the operator to determine the details of how media-channel power compensation is performed.
Specifically, the operator can prescribe the amount of channel power overshoot and undershoot that should be actively compensated.
Additionally, operators can prescribe the hysteresis value used to determine if a channel should be added initially, or reverted after being switched to ASE due to low power.

Under the current model, these implementation details must be specified using vendor native models (in addition to configuration which can be set directly through OpenConfig).
The proposed model update will transfer ownership of media-channel optical control to OpenConfig directly.
The new parameters would be optional, allowing existing operator implementations which rely partially on native vendor models to be preserved.

Below is a summary of model additions that will be proposed.
These parameters will be applied on a per-media-channel basis (i.e. they are set on every media-channel and can be different across media-channels).

 // identity statements
  identity ATTENUATION_CONTROL_RANGE {
    description
      "The definition for different types of modes to specify attenuation control range settings on a media channel.";
  }

  identity CONTROL_RANGE_FULL {
    base ATTENUATION_CONTROL_RANGE;
    description
      "Media channel power compensation range is not constrained, and limited by available WSS dynamic range. Operator does not explicitly set the undershoot and overshoot compensation values.";
  }

  identity CONTROL_RANGE_LIMITED {
    base ATTENUATION_CONTROL_RANGE;
    description
      "Media channel undershoot and overshoot compensation ranges are defined by max-undershoot-compensation and max-overshoot-compensation.";
  }

leaf attenuation-control-range {
      type identityref {
        base ATTENUATION_CONTROL_RANGE;
      }
      description
        "Sets the attenuation control range for the media channel. The control range defines the amount of media channel undershoot and overshoot compensation that will be applied when performing power targeting to meet the defined output port spectrum power profile";
    }
  }

New optical control parameters:

"max-undershoot-compensation"
Applicable for CONTROL_RANGE_LIMITED
Description:
“Defines the maximum allowable WSS attenuation adjustment the system will use to compensate a channel with input power lower than the defined target power at the input. This value is measured relative to the baseline WSS attenuation established for an individual media-channel.”

"max-overshoot-compensation"
Applicable for CONTROL_RANGE_LIMITED
Description:
"Defines the maximum allowable WSS attenuation adjustment the system will use to compensate a channel with input power higher than the defined target power at the input. This value is measured relative to the baseline WSS attenuation established for an individual media-channel."

"ase-recovery-hysteresis"
Applicable for ase-injection-mode = MODE_DELTA or MODE_THRESHOLD
Description:
"Defines the optical power offset value relative to the ASE injection threshold at which point ASE should be removed and the media-channel should be restored. Also specifies the optical power offset relative to injection threshold in dB above which a media channel will be initially added to the system.”

https://github.com/openconfig/public/blob/815341544e58548526e7f9bec4e0ed2d615b69ac/release/models/optical-transport/openconfig-wavelength-router.yang#L133

**Comment by ejbrever** [comment]
This makes sense to me, thanks for starting this proposal!

**Comment by dplore** [comment]
@kcroussore please do submit a pull request for review!  Thanks.

**Comment by dplore** [comment]
Fixed by https://github.com/openconfig/public/pull/1090
