### ISSUE TITLE
The openconfig-bgp-policy module  is not imported by other modules？

### ISSUE THREAD

**Issue by jensencj** [openconfig/public#107]
The openconfig-bgp-policy module is not imported by other modules. And I can not find the keyword 'uses' to expand the grouping in this module. I can not find any nodes related with the openconfig-bgp-policy in all openconfig yang files. Can you tell me the reason? Thank you!

**Comment by robshakir** [comment]
HI,

The openconfig-bgp-policy module augments the openconfig-routing-policy
module such that BGP specific policy hooks are added to the defined sets,
and routing match/action criteria therein.

You can see the augments here:
https://github.com/openconfig/public/blob/master/release/models/bgp/openconfig-bgp-policy.yang#L1177-L1193


Thanks,
r.

**Comment by robshakir** [comment]
Please re-open this issue if you have further issues here, thanks!
