### ISSUE TITLE
800G Client Related Additions

### ISSUE THREAD

**Issue by ejbrever** [openconfig/public#1078]
I'd like to propose the following changes to help support 800G clients:

1)  identity PROT_800GE {
    base TRIBUTARY_PROTOCOL_TYPE;
    description "800G Ethernet protocol";
  }

2) A change to the description of OSPF form factors to mention 400G or 800G (currently just says 400G).

3) Add a TRIBUTARY_PROTOCOL_TYPE of PROT_FLEXO

**Comment by dplore** [comment]
Fixed by #1079
