### ISSUE TITLE
in openconfig-interfaces.yang counters are missing for interface

### ISSUE THREAD

**Issue by nijeshvp** [openconfig/public#1102]
Hi Expert,

For  openconfig-interfaces.yang  counter , it will show no counter leaves for ~10sec after interface create.
So if the get request on interface/state/counter , it wont show any counter.

What will be the expected behaviour  If stats don't have any counter for that interface.
Do we need to show 0's as counter value if nothing to show instead empty counter  container?

example: 
```
       <state>
        <index>3</index>
        <description>sub1_3</description>
        <enabled>true</enabled>
        <name>GigabitEthernet0/0/0/1.3</name>
        <ifindex>36</ifindex>
        <admin-status>UP</admin-status>
        <oper-status>UP</oper-status>
        <last-change>1712572337321869091</last-change>
        <logical>true</logical>
        <management>false</management>
        <cpu>false</cpu>
        <counters>
        </counters>
       </state>
```

thanks
Nijesh

**Comment by dplore** [comment]
I would expect an empty counter container when the data is unavailable.

**Comment by rgwilton** [comment]
I agree with Darren in that, in that if an item of operational data doesn't exist then it is better not to return it than return a default or incorrect value, but then in our implementation I would expect the base interface counters to logically exist at the same point that the interface is created in the system, so they would all exist with value 0.

**Comment by dplore** [comment]
> I agree with Darren in that, in that if an item of operational data doesn't exist then it is better not to return it than return a default or incorrect value, but then in our implementation I would expect the base interface counters to logically exist at the same point that the interface is created in the system, so they would all exist with value 0.

I think exposing the counters with a value of 0 upon creation of an interface is also ok.  In this case the key is a new interface is being created.  Counter data is expected to only be refreshed periodically and therefore not at the same instant that the interface counter nodes are created.

**Comment by LimeHat** [comment]
Hi Darren,

I have no relation to OP, but I'd like to follow up on your response.

> I would expect an empty counter container when the data is unavailable.  

What is considered "unavailable"? 
Does that mean that if a counter never exceeds zero, it doesn't need to be returned at all?

**Comment by dplore** [comment]
> Hi Darren,
> 
> I have no relation to the OP, but I'd like to follow up on your response.
> 
> > I would expect an empty counter container when the data is unavailable.
> 
> What is considered "unavailable"? Does that mean that if a counter never exceeds zero, it doesn't need to be returned at all?

By unavailable, I mean "does not exist".  This scenario begins with the interface in question does not exist.   During the period in which the interface does not exist, there should not be any nodes in the tree to represent it.  Then the interface is created.  Of course at this point, the nodes in the interface tree should be created.  It is ok if counters nodes are also created, even if it takes some further amount of time before data is available.  At the moment of counters creation, the values can be '0'.
