### ISSUE TITLE
ISIS Lan Adj state issue 

### ISSUE THREAD

**Issue by sms-juniper** [openconfig/public#1115]
/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/adjacencies/adjacency/state/adjacency-state
description:
P2P 3-way ISIS adjacency state(up, down, init, failed).

description says adj state for p2p only  which restricts streaming out of lan adj state.

however the model is designed to address lan adj as well , like dis-system-id which is specific to lan only.

/network-instances/network-instance/protocols/protocol/isis/interfaces/interface/levels/level/adjacencies/adjacency/state/dis-system-id
description:
DIS System ID(LAN hello only).

Can adjacency-state description be corrected to address lan adjacency also ? or can a new leaf be introduced explicitly for lan adj state ??

**Comment by dplore** [comment]
Hi, I think it's ok to update the description to make it generic for both LAN and P2P adjacencies.   Would you like to open a pull request to proposed this update for us?
