### ISSUE TITLE
Pim: Add support for PIM_MODE_BIDIR in openconfig-pim-types.yang

### ISSUE THREAD

**Issue by raviv-arista** [openconfig/public#1118]
The bidirectional pim mode is missing from the pim mode types.
```
    identity PIM_MODE_BIDIR {
        base PIM_MODE;
        description
          "PIM BIDIR mode.";
        reference "RFC5015";
    }
    
```
This should be added. I can open a PR for this.
Creating this issue to ask if there was a reason it wasn't added before.

**Comment by dplore** [comment]
Looks like it was only an oversight, happy to review a PR for this.
