### ISSUE TITLE
AAA_AUTHORIZATION_EVENT_TYPE base type issue

### ISSUE THREAD

**Issue by atomicbaum1** [openconfig/public#112]
I noticed that the openconfig-aaa-type.yang identities for "AAA_AUTHORIZATION_EVENT_COMMAND" and "AAA_AUTHORIZATION_EVENT_CONFIG" had a base type of "AAA_ACCOUNTING_EVENT_TYPE" and we think the intent was a base type of "AAA_AUTHORIZATION_EVENT_TYPE".  I made the example changes here if anyone wants to take a look [https://github.com/atomicbaum1/public/commit/865fec716744c1e27b81878d9a0a54ae2897492e#diff-c73608f726eb54cf7d12bf824cd0794e](https://github.com/atomicbaum1/public/commit/865fec716744c1e27b81878d9a0a54ae2897492e#diff-c73608f726eb54cf7d12bf824cd0794e)

**Comment by megarajan** [comment]
I too ran into this issue. This must be fixed. Are your changes committed and integrated to the openconfig codebase ?

**Comment by robshakir** [comment]
Hi, 

Thanks for reporting this issue -- this does look like an error. We'll make the change and push it to the `public` repo after an operator's group review.

Thanks,
r.

**Comment by megarajan** [comment]
Thanks for taking care of this.

**Comment by dplore** [comment]
Fixed by (https://github.com/openconfig/public/commit/06b33ff792b5533081680e637c3243749c0bee5a with no associated PR)
