### ISSUE TITLE
Optical channel reference to it's logical channel

### ISSUE THREAD

**Issue by ejbrever** [openconfig/public#1128]
I'd like to propose adding a new state leaf to optical channels that would be a reference to the logical channel that is directly assigned to it; if it is assigned to a logical channel.

Currently the model has the reverse reference from the logical channel --> optical channel.

However, it is not trivial to do the reverse as that involves two layers of lists to iterate through (logical-channels and then logical-channel-assignments) which can be an expensive query to make if when there are a lot of logical-channels. Having the reverse direction in the model would provide a lot of simplicity in doing this lookup.

**Comment by dplore** [comment]
fixed in https://github.com/openconfig/public/pull/1130
