### ISSUE TITLE
Query on software life cycle management

### ISSUE THREAD

**Issue by EstherLerouzic** [openconfig/public#1134]
Could you please tell me where I can find the openconfig software management modules that cover aspects related to software management, including software versions, installation, activation, rollback, and other related parameters ?
thanks !

**Comment by dplore** [comment]
Hi, please take a look at gNOI.OS  It is a grpc interface for doing software install, activation and verification.

https://github.com/openconfig/gnoi/blob/main/os/os.proto

On a closely related topic there is also [OpenConfig bootz](https://github.com/openconfig/bootz) which provides a secure bootstrapping service to bring up a device from factory defaults, installation of certificates and the production configuration.
