### ISSUE TITLE
Correction to loopback-mode-type FACILITY and TERMINAL

### ISSUE THREAD

**Issue by liulk** [openconfig/public#1135]
https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-terminal-device.html

Currently:

  * FACILITY: A port **internal** loopback at ASIC level.
  * TERMINAL: A port **external** loopback at ASIC level.

Cisco reported that FACILITY and TERMINAL loopbacks should be reversed. @ahsaanyousaf confirmed it.

Proposed:

  * FACILITY: A port **external** loopback at ASIC level.
  * TERMINAL: A port **internal** loopback at ASIC level.

Background:

@aashaikh first added the definition here: https://github.com/openconfig/public/commit/4e0d236b04326c37275ea9d5c621ea51e7d8eeb8

@aashaikh first use of loopback-mode-type for terminal device loopback-mode leaf here: https://github.com/openconfig/public/commit/b05e0076a8716f4a21dd5029e22fc47d54b7d059

@sulrich changed the interface loopback-mode leaf from boolean to loopback-mode-type here: https://github.com/openconfig/public/pull/731

@sallylsy and @dplore added PHY and MAC specific enums: https://github.com/openconfig/public/pull/1034

**Comment by liulk** [comment]
cc: @aaronmillisor

**Comment by ahsaanyousaf** [comment]
cc: @ejbrever

**Comment by LimeHat** [comment]
An ASIC can implement loopback functionality in the MAC layer or the (internal) PHY layer.
There's also an external PHY layer which corresponds to a transceiver.

One of the points in #1034 was that in some use cases, the actual loopback functionality is not necessarily required and the `FACILITY` is used to emulate the oper-up state of an interface (when the operator doesn't care about the data plane behavior of the interface)

**Comment by ejbrever** [comment]
I agree the definitions of FACILITY and TERMINAL are reversed.

Maybe FACILITY|TERMINAL are not applicable to pluggable optics on a router the same way. In that case, perhaps dedicated enums for those would be better. But I would strongly suggest we do not deprecate FACILITY|TERMINAL as for optical networking they are industry standard names and we have a lot of OpenConfig implementations using those that we shouldn't break (at least ten across four vendors).

**Comment by liulk** [comment]
Updated proposal, after discussion with @dplore:

* Deprecate: `FACILITY`, `TERMINAL` without changing their incorrect meanings.
* Add: `LOCAL` for internal and `REMOTE` for external.
* Not changed: `ASIC_PHY_LOCAL`, `ASIC_PHY_REMOTE`, `ASIC_MAC_LOCAL`, `ASIC_MAC_REMOTE`

The rationale for deprecating `FACILITY` and `TERMINAL` but add new enums, as opposed to fixing their meaning, is that we want to avoid bumping the OC version for now. If we change their meanings, we will have to bump OC version in accordance with https://www.openconfig.net/docs/guides/semver/.

**Comment by ejbrever** [comment]
Deprecating FACILITY and TERMINAL creates a lot of extra work. IMHO this creates confusion and to change all of the existing in production implementations just because the description is incorrect doesn't seem right. What is wrong with just bumping the OC version?

**Comment by dplore** [comment]
Updating the descriptions of a leaf to invert the meaning of the leaf's
function. (ie just changing FACILITY to mean a remote loopback versus a
local loopback) is a breaking change that is very hard to detect and not
that easy to work with programmatically.  Implementing breaking changes is
a lot of work and confusion and config generation, testing and telemetry
which is especially difficult if there is no obvious change in the schema.
  Further, an upgrade to the NOS version will change production device
behavior which is not a good operational practice.  (a device with loopback
configured to FACILITY gets a NOS upgrade and switches from a local
loopback to remote loopback)

Using new leaf names to represent the new meaning makes it easy to know
exactly what the meaning is of each leaf and what the implementation
supports.

**Comment by dplore** [comment]
I spoke with @ejbrever;  he is saying that many known existing optical vendor devices treat FACILITY and TERMINAL as expected, and not in the reverse ways in the OC description.  That is,  optical device vendors known to us define 

- FACILITY as a port external loopback at ASIC level where data received from a far end neighbor is looped out to the transmit port back to the neighbor.  
- TERMINAL as a port internal loopback at ASIC level where data sent from the device to the PORT is looped back to the local device.   

So updating the OC description to match this would not be a breaking change, but rather just a patch/bug fix to the OC description.

I'd like to get some feedback from packet device vendors to see if this is roughly the same situation.

**Comment by LimeHat** [comment]
We (Nokia) have an implementation that was done according to the current OC description in SRLinux. For us, it is going to be a breaking change.

**Comment by aaronmillisor** [comment]
Cisco's optical and packet sides have both mapped facility/terminal in the way being proposed by this change (i.e. according to industry standard terminology) rather than by the OC description.

**Comment by liulk** [comment]
After speaking to @dplore again, we've decided to correct the description of the FACILITY and TERMINAL enums without introducing new enums. We will bump the major version number as a one-time breaking change, taking into account the fact that a couple of packet device models across a few vendors will be affected. For the optical devices or vendors that already implemented the correct meaning, this will be no-op for them.
