### ISSUE TITLE
cannot specify output interface when /qos/scheduler-policies/scheduler-policy/output/config/output-type == INTERFACE

### ISSUE THREAD

**Issue by dliu2223** [openconfig/public#1199]
The config has child-scheduler and output-fwd-group, but at the last scheduler in a hierarchy, e.g., port scheduler, the output is the egress interface and the current model does not support it. Should a interface name or ref be added? In our configuration, the /qos/interfaces/interface/interface-ref points to the ingress interface where the scheduler is attached.  If our understanding is incorrect, please advise.  Thanks

David

**Comment by dplore** [comment]
Interface ref is to an interface, but there are references for input and output  schedulers.  See:

![image](https://github.com/user-attachments/assets/2d66f3f6-0e71-46a6-96cc-6496bf6e9a88)


Here is a schema diagram to show the references:
![image](https://github.com/user-attachments/assets/2337bc28-3e5b-48ae-a995-ef9fa3c85a1a)


Does it make sense?  Please feel free to open if not.

**Comment by dliu2223** [comment]
Sorry I was not clear about the issue, let me try a different way, see the qos-scheduler-output-config below:
     |           +--rw output
     |           |  +--rw config
     |           |  |  +--rw output-type?
     |           |  |  +--rw child-scheduler?
     |           |  |  +--rw output-fwd-group?
output-type is an enum that can be SCHEDULER, FWD_GROUP, or INTERFACE. If the output-type is SCHEDULER, the leaf child-scheduler is used or if the output-type is FWD_GROUP, then the output-fwd-group is used.
But, if the output-type is INTERFACE, there is no leaf to specify which interface will be the sink for the output. See the YANG schema of grouping qos-scheduler-output-config from openconfig-qos-elements.yang.
