### ISSUE TITLE
Clarifying temperature sensor sampling periods

### ISSUE THREAD

**Issue by mschuldt** [openconfig/public#120]
Hello,

I'm looking for clarification on the sampling periods for values of ave, min, and max at path components/component/state/temperature.

For example the description of 'ave': "The arithmetic mean value of the statistic over the sampling period."

Is this sampling period over the full uptime of the device or a more restricted moving window?

**Comment by aashaikh** [comment]
Thanks for the comment.  The interval here is typically a moving window of fixed size over which the statistics are computed, e.g., avg/min/max over the last 5min interval.  I agree the descriptions could be made clearer for these stats.

The latest rev of the platform model also includes an `interval` leaf to allow the system to indicate what the size of the interval is.
