### ISSUE TITLE
CPU utilization as a counter instead of percentage

### ISSUE THREAD

**Issue by aaronbee** [openconfig/public#125]
In commit 634a8776566db1b2c2ebd4f6ab46219e3eeead71 new CPU utilization nodes were added to the system module. The leafs are all in unit percentage. However, linux (and I assume other kernels) report CPU usage as a counters for time spent idle, in user code, in kernel code, etc. Utilization percent is calculated by looking at how much the counters have changed over a time period, essentially an average over that time period. An "instant" utilization percent doesn't make sense. "instant" could be calculated as an average over a short time period, but then what is the "avg" leaf? An average over a slightly longer time period?

What might be more useful is to have "instant" be the raw CPU counter. With this information a system consuming from an OpenConfig target can calculate utilization over any time period.

**Comment by aashaikh** [comment]
Thanks for the comment and suggestion.  We discussed this in the operator working group and the feedback was that it's much easier to consume this data in terms of percentages (and the system has the best info to provide it).  While the client *could* compute percentages, the computation is not as straightforward as a rate of counter increase as it requires normalization with other platform information (e.g., USER_HZ on Linux), as well as across counters.

The `interval` field in these statistics allows the system to report the time over which the average, etc. are computed.  The instantaneous value would be the most recently sampled value at the time a telemetry notification is sent.  The system may only provide the instant value if the statistics are not available.

We might consider adding raw counters to the model in the future.

**Comment by avinkon** [comment]
Iam still not clear , could you please help me understand following  if oc-cpu:avg  is provided over `interval` 
then "instant" value is not required or it could be same as avg
