### ISSUE TITLE
/interfaces/interface/config/mtu type uint16 not compatible with default Linux configuration

### ISSUE THREAD

**Issue by gmathon-ovh** [openconfig/public#129]
Hi,

Default loopback interface MTU is set to 64*1024 (65536) in [linux kernel since 2012](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/drivers/net/loopback.c?h=v4.15.3&id=0cf833aefaa85bbfce3ff70485e5534e09254773). 
Openconfig defines /interfaces/interface/config/mtu as a uint16, so max value is 65535 (matching maximum IPvX datagram total length?):
https://github.com/openconfig/public/blob/0c955cd2a4d0e0e78e20fe8146fe3e6d4cfda9bc/release/models/interfaces/openconfig-interfaces.yang#L335

When you try to store default linux loopback config following this model, it will fail because the value don't fit uint16 type.

Should the type be changed to allow higher values, or the default MTU default configuration decreased?

**Comment by robshakir** [comment]
Hi,

Apologies, we'd missed this issue. I've opened an internal issue tracking this fix. I don't see a problem with it given that Linux has this implementation, but we'll discuss and push an update.

Thanks,
r.

**Comment by precla** [comment]
Any updates on this?

It is still in the latest [openconfig-if-ip.yang](https://github.com/openconfig/public/blob/323a3e2e43c60aafa2bf78ec7c955c00f6cfac4d/release/models/interfaces/openconfig-if-ip.yang#L457) model.

There is no limitation in the MTU size in "RFC 791: Internet Protocol"

**Comment by dplore** [comment]
Hi @precla,  thanks for the reference and ping on this.

Rob raised a proposal to the internal OpenConfig operators group back in 2018, but it quickly became stale.

What do you think about this update? Look good?

        type uint32 {
          range 1..65536;
        }

**Comment by precla** [comment]
Hi @dplore and thanks for the reply!

I'd say that from a Linux point of view it looks good. Considering that only the [loopback can have 65536](https://elixir.bootlin.com/linux/latest/source/drivers/net/loopback.c#L203).
Whereas all other interfaces can have [max 65535](https://elixir.bootlin.com/linux/v6.5.7/source/include/linux/ip.h#L53).

In the current [openconfig-if-ip.yang](https://github.com/openconfig/public/blob/323a3e2e43c60aafa2bf78ec7c955c00f6cfac4d/release/models/interfaces/openconfig-if-ip.yang#L457) model there is a minimum of 68, which is also the [minimum for IPv4](https://en.wikipedia.org/wiki/Maximum_transmission_unit#MTUs_for_common_media).

Keep that for the range or go with new minimum 1?

```
    type uint32 {
      range 68..65536;
    }
```

[Loopback](https://elixir.bootlin.com/linux/v6.5.7/source/drivers/net/loopback.c#L258) and other interfaces in Linux can not have a minimum less than 68:
`#define ETH_MIN_MTU 68 /* Min IPv4 MTU per RFC791 */`
https://elixir.bootlin.com/linux/v6.5.7/source/include/uapi/linux/if_ether.h#L40

**Comment by precla** [comment]
Added it. I hope the revision is ok?

I just signed the Google CLA, takes some time until it gets green light?
