### ISSUE TITLE
/system/processes/process/[pid]/args definition as leaflist does not make sense

### ISSUE THREAD

**Issue by peterfeifanchen** [openconfig/public#135]
The definition asks for the command line arguments to be broken down into its components and added to args as leaflists. However, this seems unnecessarily complicated as how the arguments are typed out is dependent on the application. Openconfig spec shouldn't be asking for mappings that have to guess which arguments form a set and which are independent. 

If instead this meant that the leaflist should be a list of arguments delimited by spaces, then it would collide with the uniqueness requirement for leaflist leafs since there is no way to guarantee that same argument + value won't show up twice in this case. 

It would be much simpler if this was just a string, I feel rather than a leaf list.

**Comment by aashaikh** [comment]
This just makes it easier for a client receiving this information as telemetry, as it does not have to parse the arguments -- this has already been done on the device (e.g., on a stack, exposed in /proc/[pid]/cmdline on Linux-based systems IIRC).  

I think you're right that the device would need to suppress identical arguments, or we could consider making this a uindexed list (which has its own challenges).  I could also see an argument that the leaf-list should be really be a list with a bit more structure, e.g., to separate names of arguments from their values where applicable, but this would require more work on the device.

**Comment by peterfeifanchen** [comment]
Yes, but the way it is defined in the release is that rather than a space delimited list, OpenConfig has to interpret /proc/[pid]/cmdline for what set is actually a complete argument. For example:

some_program -e -b 10 20 -d 50 10

There is no way to know from above unless you wrote "some_program" what are independent or dependent arguments. Is "-b 10 20" one argument? Or is it "-b 10", "20"? These are application specific things that OpenConfig have no way of knowing about.
