### ISSUE TITLE
openconfig-lacp.yang:  lacp container has invalid condition.

### ISSUE THREAD

**Issue by sushant-kumar** [openconfig/public#14]
Hi, 

The "when" statement below is invalid.  There is no "lag-type" leaf in the relative oc-path referred to by "when" statement. 
```
module: openconfig-lacp

    container lacp {
      when "../config/lag-type = LACP" {
        description
          "LACP configuration and opstate is active when the
          aggregate interface type is LACP";
        }
```
Is the "when" statement intend to validate if **at least one of the interfaces** has lag-type as LACP configured? I don't think that is the intention, but if so, condition need to be modified appropriately. It is more likely a remnant from the openconfig-if-aggregate.yang module where lacp container used to reside. 

Regards,
Sushant

**Comment by aashaikh** [comment]
Thanks Sushant -- you're right, this is a leftover from when LACP was embedded in the aggregate interface model.  We'll remove the condition and update the model.

**Comment by aashaikh** [comment]
This should be fixed in the latest update.  Marking this closed.
