### ISSUE TITLE
why is qinq vlan type removed from the ethernet/switch-vlan/vlan-switched-config/trunk-vlans

### ISSUE THREAD

**Issue by antonelaf5** [openconfig/public#143]
I noticed that the openconfig-vlan.yang,  oc-ext:openconfig-version "2.0.0" was modified to remove 
type oc-vlan-types:qinq-id;
from the trunk-vlan vlan-id type.

This is forcing the qinq configuration for ethernet trunk-port interfaces to require an interface/subinterface module, in addition to the interface/ethernet.

Can anyone clarify why this happened?
If i misunderstand the change, can originator of the change show a full example of the trunk-port which does qinq?

Thank you in advance for any clarifications.

**Comment by aashaikh** [comment]
This change was based on the understanding that for flat L2 switching domains (i.e., the `switched-vlan` part of the model) , switching on an inner tag is not supported.  We also got this feedback from implementors.

Do you have an example of an implementation that supports this behavior?

**Comment by antonelaf5** [comment]
Thank you for your reply.
I am still confused.
The description of the subinterface vlan-id is:
grouping vlan-logical-config {
    description
      "VLAN related configuration that is part of subinterface
      (logical interface) configuration.  These are generally
      L3 VLANs with an id that is local.";
.........
}
So is qinq seen as L3 functionality? To me this does not seem right.

What if i have just  L2 functionality?
my config would look like:

interface foo
 config name              foo
 config type              ethernetCsmacd
 config tpid              TPID_0X8100
 ethernet switched-vlan config interface-mode TRUNK
 ethernet switched-vlan config native-vlan 20
 ethernet switched-vlan config trunk-vlans [ 31 32 ]
 subinterface 1234
  config index 1234
  config enabled
  vlan config vlan-id 1000.100
 !
!

This interface can be potentially untagged, tagged and double-tagged.
Does this look fine to you?
Is this config correct?
If not, what else am i missing?
Thank you.
