### ISSUE TITLE
namespace for openconfig-vlan and openconfig-vlan-types are the wrong way round

### ISSUE THREAD

**Issue by rgwilton** [openconfig/public#15]
I.e. the namespace for module openconfig-vlan should be:
  namespace "http://openconfig.net/yang/vlan";

and the namespace for openconfig-vlan-types should be:
 namespace "http://openconfig.net/yang/vlan-types";

At the moment they are the wrong way round.

**Comment by aashaikh** [comment]
Rob, thanks for the catch.  Should be fixed in the latest update.  Am going ahead and closing this issue.
