### ISSUE TITLE
Can enabled be overridden by iBGP configuration or eBGP configuration parameters update in openconfig-bgp.yang file 

### ISSUE THREAD

**Issue by sunseawq** [openconfig/public#150]
In openconfig-bgp-common.yang, bgp-common-use-multiple-paths-config grouping is defined as follows:
"
   grouping bgp-common-use-multiple-paths-config { 
     description 
       "Generic configuration options relating to use of multiple 
       paths for a referenced AFI-SAFI, group or neighbor"; 
  
     leaf enabled { 
       type boolean; 
       default false; 
       description 
         "Whether the use of multiple paths for the same NLRI is 
         enabled for the neighbor. This value is overridden by 
         any more specific configuration value."; 
     } 
   }
"
Not clear to me, what are "more specific configuration value"? when more specific configuration value take effect to influence the enable value? If the enable parameter is set to false, can we configure eBGP or iBGP multi-path related parameters,e.g,maximum-paths?
Can enabled be overridden by iBGP configuration or eBGP configuration parameters update?

**Comment by robshakir** [comment]
The meaning of "more specific" here is to cover inheritance through the BGP model. This was something that we discussed in some detail during the design of the model.

Particularly, in the BGP model, you can configure `use-multiple-paths` for an AFI,SAFI at the global level, and this is inherited by neighbours and peer-groups within the instance. This leaves one with the problem of how to say that even though the configuration is enabled at the global level, how do I disable it for a specific peer? Hence, we have the `enabled` leaf that can be set to false - which overrides the global configuration.

Cheers,
r.

**Comment by sunseawq** [comment]
why MPLS-TE model doesn't follow this example?
