### ISSUE TITLE
No global enabled parameter in openconfig-mpls-te.yang file

### ISSUE THREAD

**Issue by sunseawq** [openconfig/public#154]
In openconfig-mpls-te.yang file, we fail to see global enabled parameters for MPLS-TE, we only see local enabled parameter for specific configuration parameters,e.g.,
"
   grouping te-lsp-auto-bandwidth_config { 
     description 
       "Configuration parameters related to autobandwidth"; 
  
     leaf enabled { 
       type boolean; 
       default false; 
       description 
         "enables mpls auto-bandwidth on the 
          lsp"; 
     } 
"
Is this intended?

**Comment by robshakir** [comment]
This leaf specifically controls auto-bandwidth for an LSP. Please can you explain what a global enabled leaf for MPLS would actually control?

Thanks,
r.

**Comment by sunseawq** [comment]
The global enable leaf is used to enabled the whole MPLS-TE, including enable auto-bandwidth control for an LSP. but enabled parameter for auto-banwdith control can overried global enabled parameter.
