### ISSUE TITLE
No explicit path to be configured for SR TE path in openconfig-mpls-sr.yang

### ISSUE THREAD

**Issue by sunseawq** [openconfig/public#155]
In openconfig-mpls-sr.yang file, only sid-selection-model is configured, however it is not clear where to configure explict path for SR TE path, how to identify SID based explicit path?
"
   grouping sr-path-attributes_config { 
     description 
       "Configuration parameters relating to SR-TE LSPs"; 
  
     leaf sid-selection-mode { 
       type enumeration { 
         enum ADJ_SID_ONLY { 
           description 
             "The SR-TE tunnel should only use adjacency SIDs 
             to build the SID stack to be pushed for the LSP"; 
         } 
         enum MIXED_MODE { 
           description 
             "The SR-TE tunnel can use a mix of adjacency 
             and prefix SIDs to build the SID stack to be pushed 
             to the LSP"; 
         } 
       } 
       default MIXED_MODE; 
       description 
         "The restrictions placed on the SIDs to be selected by the 
         calculation method for the explicit path when it is 
         instantiated for a SR-TE LSP"; 
     } 

"

**Comment by robshakir** [comment]
Today, the expectation is that SR tunnels that are configured this way are configured with IP addresses that are resolved to the SIDs by the system. The intention of this `sid-selection-mode` leaf is to give one a way to be able to control what type of SIDs are selected to meet the path constraint specified.

For explicit SID stacks, there are two options. The emergent way to configure this would be through static SR-TE policies - such as are defined by the [`openconfig-pf-srte`](https://github.com/openconfig/public/blob/master/release/models/policy-forwarding/openconfig-pf-srte.yang) model. Alternatively, we could add them to the existing explicit path specification in the MPLS model.

As of yet, we haven't had a specific request to be able to specify SIDs in this way. It'd be useful to understand whether the use case that you have in mind uses SR-TE policy, or whether it's something that is more akin to influencing CSPF as this is the split in the current model.

**Comment by sunseawq** [comment]
We prefer to add them to existing explicit path specification in the MPLS model, maybe SR-TE is a better choice. But MPLS model is more mature than SR-TE model.
