### ISSUE TITLE
is default network instance of segment routing a global routing instance In openconfig-network-instance.yang file?

### ISSUE THREAD

**Issue by sunseawq** [openconfig/public#156]
In openconfig-network-instance.yang file, Segment routing configuration is only valid with the default 
 network instance
" 
        uses oc-sr:sr-top { 
           when "config/type = 'DEFAULT_INSTANCE'" { 
             description 
               "Segment routing configuration is only valid with the default 
               network instance."; 
           } 
         } 
"
I am wondering is default network instance global routing instance? Do we separate global routing instance model for segment routing?

**Comment by robshakir** [comment]
Yes, the default network instance is the global network instance.

Please can you clarify what the latter question means - I'm afraid I don't understand.

Thanks,
r.

**Comment by sunseawq** [comment]
just want to confirm there is no independent global routing instance model besides network instance model. I think you have already answered my question, Thanks.
