### ISSUE TITLE
How do we support distributed single board information monitoring in openconfig-system.yang file?

### ISSUE THREAD

**Issue by sunseawq** [openconfig/public#157]
It is not clear to me how to support distributed CPU cores in multiple systems? in other words, how to support distributed single board information monitoring?
"
  grouping system-cpu-top { 
     description 
       "Top-level grouping for system CPU data"; 
  
     container cpus { 
       config false; 
       description 
         "Enclosing container for the list of CPU cores on the 
         system"; 
  
       list cpu { 
         key "index"; 
         description 
           "List of CPU cores on the system (including logical CPUs 
           on hyperthreaded systems), keyed by either a numerical 
           index, or the ALL value for an entry representing the 
           aggregation across all CPUs."; 
  
         leaf index { 
           type leafref { 
             path "../state/index"; 
           } 
           description 
             "Reference to list key"; 
         } 
  
         container state { 
  
           description 
             "Operational state data for the system CPU(s)"; 
  
           uses system-cpu-state; 
         } 
       } 
     } 
   } 
"

**Comment by robshakir** [comment]
If there are multiple boards then we would expect that these are different components in the `openconfig-platform` model. Each board being a component in that list can then have a CPU subcomponent that describes its CPUs.

The relationship between components and their subcomponents is expressed through the subcomponent references.

@aashaikh has a document in progress that explains this model in more detail. We'll publish it as soon as it is ready.

**Comment by sunseawq** [comment]
Thanks, you address my comments, interesting to know the progress of the guidance document.
