### ISSUE TITLE
Is there any reason or motivation to add virtual-link-local besides virtual-router-id for VRRP config in the openconfig-if-ip.yang file?

### ISSUE THREAD

**Issue by sunseawq** [openconfig/public#158]
augment "/oc-if:interfaces/oc-if:interface/oc-if:subinterfaces/" + 
     "oc-if:subinterface/oc-ip:ipv6/oc-ip:addresses/oc-ip:address/" + 
     "vrrp/vrrp-group/config" { 
     description 
       "Additional VRRP data for IPv6 interfaces"; 
  
     uses ip-vrrp-ipv6-config; 
   } 
In standard MIB, only ifindex and VRRP-ID are specified.

**Comment by robshakir** [comment]
OpenConfig does not try and align with standard MIBs -- it aligns with use cases that operators have. This leaf allows for a virtual link local address to be defined. Can you clarify what the concern with this leaf is please?

Thanks,
r.
