### ISSUE TITLE
Why config/type = 'DEFAULT_INSTANCE' is only applied to MPLS and SR in the openconfig-network-instance.yang file

### ISSUE THREAD

**Issue by sunseawq** [openconfig/public#159]
uses oc-mpls:mpls-top { 
           when "config/type = 'DEFAULT_INSTANCE'" { 
             description 
               "MPLS configuration is only valid within the default 
               network instance."; 
           } 
         } 
  
         uses oc-sr:sr-top { 
           when "config/type = 'DEFAULT_INSTANCE'" { 
             description 
               "Segment routing configuration is only valid with the default 
               network instance."; 
           } 
         }

**Comment by robshakir** [comment]
The use cases that were considered for both MPLS (RSVP, LDP) and SR were constrained to being used within the default instance. The operators within the group, and the implementations surveyed do not have support for RSVP-TE within a VRF for example. What would the use case be for such implementations? Which platforms support this?

**Comment by jefftant** [comment]
Rob,

I think - "instance” is an unfortunate name, it has a quite different context in IGP’s (IGP instance doesn’t have to be in another VRF and shares the RIB with other instances)
More common name would be GRT/default VRF?
To my memory - Junos supports MPLS protocols in a VR

Thanks,
Jeff

**Comment by robshakir** [comment]
We certainly have multiple "instances", the naming here was selected to generic enough to represent different types of "instance" - e.g., L2 VSI, VRF etc.

We can add some additional colour to the description that we have in [`openconfig-network-instance-types.yang`](https://github.com/openconfig/public/blob/master/release/models/network-instance/openconfig-network-instance-types.yang#L103-L108) but it does reference both 'default' and 'global'.

**Comment by jefftant** [comment]
Rob,

DEFAULT_INSTANCE description does it.

Thanks,
Jeff
