### ISSUE TITLE
Request to make routing policy BGP action "set-as-path-prepend" YANG model more flexible 

### ISSUE THREAD

**Issue by abhiramkalluru** [openconfig/public#162]
Following is the YANG model for "set-as-path-prepend" BGP action from https://github.com/openconfig/public/blob/master/release/models/bgp/openconfig-bgp-policy.yang:

```
grouping as-path-prepend-config {
      description
         "Configuration data for the AS path prepend action";

      leaf repeat-n {
        type uint8 {
          range 1..max;
        }
        description
          "Number of times to prepend the value specified in the asn
          leaf to the AS path. If no value is specified by the asn
          leaf, the local AS number of the system is used. The value
          should be between 1 and the maximum supported by the
          implementation.";
      }

      leaf asn {
        type oc-inet:as-number;
          description
             "The AS number to prepend to the AS path. If this leaf is
              not specified and repeat-n is set, then the local AS
              number will be used for prepending.";
      }
}
```  

Above YANG model supports prepending a single AS number "n" number of times, like "10 10 10". It's not possible to represent as-path prepend with different AS number values, for example: "10 20 30". This ability to configure as-path prepend with different AS number values is supported by various networking vendors through their CLI. I would like to request changing above as-path-prepend YANG model more flexible such that it's possible to configure single AS number repeated multiple times and different AS number values (where some of them could be repeated like "10 20 30 10" etc...).

Thanks & Regards,
Abhiram.

**Comment by dplore** [comment]
FYI: on a related topic, see https://github.com/openconfig/public/pull/1148
