### ISSUE TITLE
openconfig-aaa: union ordering issue?

### ISSUE THREAD

**Issue by einarnn** [openconfig/public#171]
In `openconfig-aaa` we see [this](https://github.com/openconfig/public/blob/master/release/models/system/openconfig-aaa.yang#L363-L375):

```
    leaf role {
      type union {
        type string;
        type identityref {
          base oc-aaa-types:SYSTEM_DEFINED_ROLES;
        }
      }
```

You may wish to reorder the types here, as YANG specifies that the first match is what the type is assumed to be. Any wire-encoding of an identity looks to all intents and purposes like a string, and so any YANG RFC-compliant implementation will never acknowledge the provision of an identity with this ordering.

Cheers,

Einar

**Comment by robshakir** [comment]
Thanks for pointing this out -- a fix has been staged, and will be targeted to form part of an upcoming update.

**Comment by ncsrikar** [comment]
This has still not been fixed. Any specific reason?
