### ISSUE TITLE
uint8 type of client-rf/state/frequency leaf in openconfig-wifi-mac.yang

### ISSUE THREAD

**Issue by edwardpham** [openconfig/public#172]
The definition of the /access-points/access-point/ssids/ssid/clients/client/client-rf/state/frequency
node is as below:

      leaf frequency {
        type uint8;
        description
          "Frequency the client is utilizing. Typically, 2.4 or 5[GHz].";
      }

What value to return for 2.4 [GHz] if the type is uint8 ? An enum or identifyref type would be appropriate here.

**Comment by aashaikh** [comment]
@mike-albano perhaps you can comment on this? -- it looks like we need to clarify the intended units here (or consider using a different type).

**Comment by mike-albano** [comment]
Just seeing this now; apologies.
Agreed, the type here should be an enum.

**Comment by mike-albano** [comment]
Description has been updated.
