### ISSUE TITLE
How to call a container inside another container where both containers are in different modules

### ISSUE THREAD

**Issue by shravyarani** [openconfig/public#177]
I have use case with two modules: switch and interface.
Switch Yang

module switch {

   yang-version "1";

   // namespace
   namespace "xxx";

   prefix "xxx-switch";

   container switch {
  .........
  }
}

Interface yang

module interface {

   yang-version "1";

   // namespace
  namespace "xxx";

  prefix "xxx-interface";

   container interface {
       description
           "Configuration data for switch";
      --------
   }
}

I want to define list of interfaces in the switch. How can I achieve this in yang?

Example proto:

message Switch {
string id = 1;
.............
repeated list Interface interfaces = 5;
}
message  Interface {
  string id = 1;
 string name = 2;
..........
}

How do I achieve this in yang?

**Comment by aashaikh** [comment]
Sorry,  I don't understand the context here -- this doesn't seem related to OpenConfig models.

If you're looking for general information about YANG modeling, suggest you could have a look at some of the material online, e.g. Tail-f YANG tutorial videos on YouTube.  Perhaps you want to look into defining your interfaces list as a grouping and then instantiating it in your switch module.
