### ISSUE TITLE
openconfig-terminal-device.yang  frequency in dBm??

### ISSUE THREAD

**Issue by bergroth** [openconfig/public#19]
Shouldn't the output-frequency be in MHz?

grouping terminal-output-optical-frequency {
    description
      "Reusable leaves related to optical output power -- this is
      typically configurable on line side and read-only on the
      client-side";

    leaf output-frequency {
      type uint64;
      units dBm;
      description

<<Magnus

**Comment by aashaikh** [comment]
yes, thanks for catching the mistake in the units statement.  The description has it correct.  Committed a fix for this and should be reflected in the next revision of the model.
