### ISSUE TITLE
openconfig-telemetry --Question

### ISSUE THREAD

**Issue by dhruv2180** [openconfig/public#194]
In openconfig-telemetry the leafref in some groupings are using relative paths due to which the models are not compiling under ODL environment, and are  failing with the following error

```
[ERROR] yang-to-sources: Unable to generate sources with org.opendaylight.mdsal.binding.maven.api.gen.plugin.CodeGeneratorImpl generator
java.lang.IllegalArgumentException: Failed to find leafref target: ../../../../../../../sensor-groups/sensor-group/config/sensor-group-id in module openconfig-telemetry (QNameModule{ns=http://openconfig.net/yang/telemetry, rev=2017-08-24})
                at com.google.common.base.Preconditions.checkArgument(Preconditions.java:455)
```
though pyang does not complain, have you seen this error too ? if yes do you have a fix.

**Comment by s-accart** [comment]
I have the same error trying to compile openconfig-telemetry in ODL. Any solution ?
