### ISSUE TITLE
Extending set-tag functionality in "static-routes" container

### ISSUE THREAD

**Issue by abhiramkalluru** [openconfig/public#204]
Following is the model for set-tag:
```
grouping local-generic-settings {
    description
      "Generic options that can be set on local routes When
      they are defined";

    leaf set-tag {
      type oc-pt:tag-type;
      description
        "Set a generic tag value on the route. This tag can be
        used for filtering routes that are distributed to other
        routing protocols.";
    }
  }

  grouping local-static-config {
    description
      "Configuration data for static routes.";

    leaf prefix {
      type inet:ip-prefix;
      description
        "Destination prefix for the static route, either IPv4 or
        IPv6.";
    }

    uses local-generic-settings;
  }
```

Currently is only one tag can be associated with a particular prefix. In some of the networking vendors it's possible to configure tag value at each nexthop level, value can be same across the nexthops if the user/gNMI client doesn't want to have different tag value for each nexthop. I think there'll be advantages in extending "set-tag" functionality as it doesn't have to be associated with a prefix there by I would like to request moving the "set-tag" leaf into "next-hop" list container config & state at the same level in hierarchy as "metric"/"recurse" leaves.

Thanks & Regards,
Abhiram.

**Comment by sulrich** [comment]
perhaps make this a leaf-list?
