### ISSUE TITLE
Why is bgp-rib not under network-instances hierarchy?

### ISSUE THREAD

**Issue by AndreasVoellmy** [openconfig/public#205]
Under network-instances (openconfig-network-instance.yang) we have protocols container, and it has (among other protocols) a container on bgp, which has various things, such as peer states, etc. In addition, we have at top-level the bgp-rib container that has per-afi-safi, per-peer ribs. Why is this not included under network-instances protocols bgp hierarchy? It seems like protocol-specific state data. Related question: why do the routes under bgp-rib not have vrf attribute?

**Comment by robshakir** [comment]
You're right -- the BGP RIB model is defined in a context that makes it relevant per-network instance. We are in the process of importing all models that should be under network-instance into that model, and then deprecating their top-level RIB. BGP-RIB is still on the TODO for this.

**Comment by aashaikh** [comment]
FYI, this change has been staged, and should be published soon.  Please re-open if you have further questions.
