### ISSUE TITLE
When Statement in openconfig-terminal-device.yang not as per RFC6020

### ISSUE THREAD

**Issue by vprasad** [openconfig/public#206]
Hi,

This is what is present in oc-terminal-device.yang

           when "config/logical-channel-type = 'PROT_OTN'" {
           when "config/logical-channel-type = 'PROT_ETHERNET'" {

This is the correct version

            when "config/logical-channel-type = 'oc-opt-types:PROT_OTN'" {
            when "config/logical-channel-type = 'oc-opt-types:PROT_ETHERNET'" {

Issue is The identity ref is used without a prefix which indicates this is defined local to this yang. But this identity ref is defined in openconfig-transport-types.yang.So we need to use the prefix with this.

RFC6020 ref:-
9.10.3.  Lexical Representation

   An identityref is encoded as the referred identity's qualified name
   as defined in [XML-NAMES].  If the prefix is not present, the
   namespace of the identityref is the default namespace in effect on
   the element that contains the identityref value.

Currently i am using confd/tail-f stack for supporting Netconf.And Confd is not able to populate the elements in the when statement due to the above issue.

Thanks,
Vivek prasad

**Comment by vprasad** [comment]
Can anyone please look into this issue.

**Comment by vprasad** [comment]
Hi ,
Can you please kindly revert on this issue?
Thanks,
Vivek prasad

**Comment by vprasad** [comment]
> Hi ,
> Can you please kindly revert on this issue?
> Thanks,
> Vivek prasad

Also the below statement in openconfig-transport-line-common.yang has the same issue :-

augment "/oc-platform:components/oc-platform:component" {
    description
      "Adding optical line port data to platform model";

    uses transport-line-common-port-top {
      when "current()/oc-platform:state/oc-platform:type = 'PORT'" {
        description
          "Augment is active when component is of type
          PORT";
      }   
    }   
  }
Again the PORT should be appended by the prefix where this identity is present i.e., ‘oc-platform-types:PORT’

**Comment by Nshet** [comment]
can you please anybody look into this

**Comment by aashaikh** [comment]
This looks like a similar issue as #209, i.e., not having sufficiently good validation of when statements in the common YANG validation tools (e.g., pyang and confdc).  We will fix these together.

What validation tools are you using that are failing on these statements?  We can look at the possibility of using them as part of the CI for models.

thanks.

**Comment by circip** [comment]
Hello , I am trying to generate classes for openconfig-terminal-device.yang using pyangbind , but it fails with this message: 

openconfig-terminal-device.yang:997): warning: node "openconfig-terminal-device::logical-channel-type" is not found in "openconfig-terminal-device::config"

openconfig-terminal-device.yang:1004): warning: node "openconfig-terminal-device::logical-channel-type" is not found in "openconfig-terminal-device::config"

INFO: encountered (<pyang.error.Position object at 0x7fdd28e97be0>, '**XPATH_NODE_NOT_FOUND1**', (u'openconfig-terminal-device', u'logical-channel-type', u'openconfig-terminal-device', u'config'))


If I try to modify as per statements above :

from : 

 when "config/logical-channel-type = 'PROT_OTN'" {
 when "config/logical-channel-type = 'PROT_ETHERNET'" {

to

 when "config/logical-channel-type = 'oc-opt-types:PROT_OTN'" {
 when "config/logical-channel-type = 'oc-opt-types:PROT_ETHERNET'" {

instead I got these errors: 

openconfig-terminal-device.yang.when:997): error: prefix "logical-channel-type" is not defined (reported only once)
openconfig-terminal-device.yang.when:1004): warning: node "openconfig-terminal-device::logical-channel-type" is not found in "openconfig-terminal-device::config"
INFO: encountered (<pyang.error.Position object at 0x7f5180f24be0>, 'PREFIX_NOT_DEFINED', u'logical-channel-type')

Any suggestions will be appreciated.
Thanks

**Comment by ikashan** [comment]
Hi,
I see you have committed the change but when I open the file openconfig-terminal-device.yang from public the 'when' statement is still incorrect. 
How can I obtain the file with the correct when statement?

Thanks 
Inbal
