### ISSUE TITLE
Fix ops.openconfig.net/...

### ISSUE THREAD

**Issue by dbarrosop** [openconfig/public#207]
Are there any plans to fix ops.openconfig.net? It's been returning 404s for quite some time now. Also, certificate used by the server is not correct as it's built for example.com :)

**Comment by robshakir** [comment]
Hi David,

The content that was in the branches directory can be found at http://ops.openconfig.net/branches/models/master -- we made some changes to support multiple repos. This was initially a development tool for the operator group, but has become more public -- we need to align our support approach with that fact :-)

You're right, we need to get a cert for this.

Cheers,
r.

**Comment by ashwinak** [comment]
+1.

This is a great tool for it's intended purpose.

Thanks,
-Ashwin

**Comment by dbarrosop** [comment]
Thanks, I think it's worth adding a note/link [here](http://www.openconfig.net/docs/models-html/) as that resource is invaluable :)

One more question, the tool that generate the "docs" part, is it opensourced?

**Comment by aashaikh** [comment]
Hi David, yes I was supposed to add a redirect /link - will do that :-(.  That link was intended for use internal to the group.  We plan to make the docs available on the web site in this format. 

The docs are generated by a pyang plugin and is open sourced in the oc-pyang repo. Beware it's still pretty rough, still needs tests, etc.
