### ISSUE TITLE
the VRF of ntp\logging remote-server configuration

### ISSUE THREAD

**Issue by luffycjf** [openconfig/public#211]
As I said in google group:
I'm trying to map the "the vrf of ntp\logging remote-server" configuration available on most vendor CLI to the right Openconfig model leafs, but i don't see a direct match.
+--rw remote-servers
   +--rw remote-server* [host]
      +--rw host         -> ../config/host
      +--rw config
      |  +--rw host?             oc-inet:host

remote-server should have a leaf  'vrf ',like this:
+--rw remote-servers
   +--rw remote-server* [host]
      +--rw host         -> ../config/host
      +--rw config
      |  +--rw vrf?             oc-netinst:name
      |  +--rw host?          oc-inet:host

grouping logging-remote-config {
  leaf vrf {
    type oc-netinst:name;
    description
    "the vrf to the log server";
  }       
}

**Comment by chrisy** [comment]
In our internal model, we've modeled this like this:
```
/oc-sys:system/oc-sys:logging/oc-sys:remote-servers/oc-sys:network-instances/oc-sys:network-instance/oc-sys:config/name
type: leafref
path reference: /network-instances/network-instance/name
```
