### ISSUE TITLE
Wrong 'parent' definition  in openconfig-platform

### ISSUE THREAD

**Issue by ADVA-OPTICAL** [openconfig/public#212]
I believe that there is wrong definition of 'parent' object:

+--rw components
   +--rw component* [name]
      +--rw name                  -> ../config/name
      +--rw config
      |  +--rw name?   string
      +--ro state
      |  +--ro name?               string
      |  +--ro type?               union
      |  +--ro id?                 string
      |  +--ro location?           string
      |  +--ro description?        string
      |  +--ro mfg-name?           string
      |  +--ro mfg-date?           openconfig-yang-types:date
      |  +--ro hardware-version?   string
      |  +--ro firmware-version?   string
      |  +--ro software-version?   string
      |  +--ro serial-no?          string
      |  +--ro part-no?            string
      |  +--ro removable?          boolean
      |  +--ro oper-status?        identityref
      |  +--ro empty?              boolean <false>
      |  +--ro **parent**?             -> **../../config/name**
      |  +--ro temperature

According to libyang validation I got error if I use it for datastore like below (simpliefied datastore):

<components xmlns="http://openconfig.net/yang/platform">
      <component>
        <name>MainEntity</name>
        <config>
          <name>MainEntity</name>
        </config>
        <state>
          <name>MainEntity</name>
          <parent>MainEntity</parent>
        </state>
      </component>
      <component>
        <name>SubEntity</name>
        <config>
          <name>SubEntityI</name>
        </config>
        <state>
          <name>SubEntity</name>
          <parent>**MainEntity**</parent>
        </state>
      </component>

libyang[0]: Leafref "../../config/name" of value "MainEntity" points to a non-existing leaf. (path: /openconfig-platform:components/component[name=SubEntity']/state/parent)

The first 'component' is validated ok, because it points to itself, however the second 'component' - SubEntity - pointing to the MainEntity throws an error.

If I change the Yang model to have |  +--ro **parent**?             -> **../../../component/config/name** than the validation is passed.

Am I using the 'parent' object wrong or is there an error in Yang model?

**Comment by idefixcert** [comment]
Hi,

I identified the same problem today,
can we have a change of the model?

**Comment by ADVA-OPTICAL** [comment]
Guys, according to xpath ../../ means 2 levels back, which means that from 'parent' we end up in 'component' - the same component that the reference is coming from. It's seems like a real bug in definition. Could you please check it ?

**Comment by idefixcert** [comment]
I already opened a pull request for that:
https://github.com/openconfig/public/pull/218

**Comment by aashaikh** [comment]
Thanks for the catch and discussion.  This is indeed not a correct reference given that it would point to the same component.

We'll get this fixed asap (we will be able to accept PRs once we update the contributor docs, CLA, etc. -- in progress).

**Comment by aashaikh** [comment]
This was fixed in the latest push of the models.
