### ISSUE TITLE
is there any reason for  not developing "match ipvX address" in vrrpv3 as per RFC5798  in openconfig-if-ip.yang? 

### ISSUE THREAD

**Issue by mvicki93** [openconfig/public#213]
is there any reason for  not developing "match ipvX address" in vrrpv3 as per RFC5798  in openconfig-if-ip.yang?
"count ipvx address and ipvx addresses" is used to match the active router's address config in the standby routers. Can we add a leaf for the same (match address) in OC?

**Comment by aashaikh** [comment]
Not sure I understand the ask here -- can you please clarify?  Assume you are asking about an opstate leaf to indicate which of the addresses was selected for the VRID?

**Comment by mvicki93** [comment]
Hi Anees,
I am taking about below request.

https://github.com/openconfig/public/pull/214

**Comment by aashaikh** [comment]
Sorry, I'm looking rather for some more explanation on what this leaf is supposed to do -- can you provide references / examples of the corresponding CLI commands to configure this on a couple of platforms from different vendors?

**Comment by mvicki93** [comment]
HI,
could you please refer the Cisco config guide?
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipapp_fhrp/configuration/xe-3s/fhp-xe-3s-book/fhrp-vrrpv3-xe.html
please search match address in the above link.
Match address is enabled by default, but allows us to un configure them
using "no match address".

Juniper:
Juniper config guide.please find the below link.
I don't find any config for match address, may be it is not allowed to
change in the Juniper box.
https://www.juniper.net/documentation/en_US/junos/topics/reference/command-summary/show-vrrp-ex-series-interfaces.html

this error message is based on the check on countipvx adores in hello pkt.
*Bad VIP count* received—Number of VRRP PDUs whose virtual IP address
counts differ from the count that has been configured on the VRRP instance.


Can we have a leaf for match-address and have default value as enabled ?

**Comment by aashaikh** [comment]
In the Cisco documentation it says:
```
match-address

(Optional) Matches secondary address in the advertisement packet
against the configured address. Secondary address matching is
enabled by default.
```
I don't see the equivalent in the Juniper docs as you said -- is this supported on other platforms?

If it's something specific to IOS-XE, you could also define a local augmentation to the OpenConfig models.

**Comment by mvicki93** [comment]
Hi Anees,

Cisco nexus box does't have match address leaf and they don't have any plan
to add the "match address" leaf in near future.
what is your suggestion on this?


Thanks,
Vignesh M

**Comment by einarnn** [comment]
Vignesh,

Speaking as a vendor engineer, if we don’t support something then we usually declare a deviation and mark content as “not-supported”.

Cheers,

Einar

**Comment by aashaikh** [comment]
Circling back to this, it looks like we're only seeing one platform that supports this behavior?  So if you need to use this knob, I'd suggest to create a local augmentation to the OC model to add a `match-address` leaf.

Closing this issue -- please feel free to reopen if you have more questions.
