### ISSUE TITLE
Clarification on "admin-user" container

### ISSUE THREAD

**Issue by romikumar7** [openconfig/public#215]
Hi All,

Following model is in openconfig/public/release/models/system/openconfig-aaa.yang

  grouping aaa-admin-config {
    description
      "Configuration data for the system built-in
      administrator / root user account";

    leaf admin-password {
      type string;
      oc-ext:openconfig-hashed-value;
      description
        "The admin/root password, supplied as a cleartext string.
        The system should hash and only store the password as a
        hashed value.";
    }

    leaf admin-password-hashed {
      type oc-aaa-types:crypt-password-type;
      description
        "The admin/root password, supplied as a hashed value
        using the notation described in the definition of the
        crypt-password-type.";
    }
  }

  grouping aaa-authentication-admin-top {
    description
      "Top-level grouping for root user configuration and state
      data";

    container admin-user {
      description
        "Top-level container for the system root or admin user
        configuration and operational state";

      container config {
        description
          "Configuration data for the root user account";

        uses aaa-admin-config;
      }

      container state {
        config false;

        description
          "Operational state data for the root user account";

        uses aaa-admin-config;
        uses aaa-admin-state;
      }
    }
  }

There is ambiguity in container/leaf name and description. name starts with admin but description suggests admin/root. Can we get clarity if it refers to root user or admin user account. 

Thanks,
Romi

**Comment by robshakir** [comment]
This naming is intentional -- some systems do not call the base superuser account "root", and hence this is intended to capture both. Are there systems that you are mapping to that have two superusers that would clash?

**Comment by romikumar7** [comment]
In our case we have 2 users root, admin. root user is default disabled. admin user is having network-admin role and is enabled by default.
