### ISSUE TITLE
Sloppy syntax in many "when" statements

### ISSUE THREAD

**Issue by BoyuanYan** [openconfig/public#223]
Hi all, 

When an identity is used in "when" statement, there are always prefix missing in openconfig yang files. For example, in file "openconfig-platform-transceiver.yang":
https://github.com/openconfig/public/blob/5897507ecdb54453d4457e7dbb0a3d4b7ead4314/release/models/platform/openconfig-platform-transceiver.yang#L557-L558

Line#558 should be modified as:
```yang
"oc-platform:type = 'oc-platform-types:TRANSCEIVER'" {
```
Currently, [ConfD](https://www.tail-f.com/confd-basic/) is able to process such sentence, but [Netopeer2](https://github.com/CESNET/Netopeer2) isn't. And according to [RFC7950#9.10.3](https://tools.ietf.org/html/rfc7950#section-9.10.3) as below, there should be explicit description for the identity reference.

```
   The string value of a node of type "identityref" in a "must" or
   "when" XPath expression is the referred identity's qualified name
   with the prefix present.  If the referred identity is defined in an
   imported module, the prefix in the string value is the prefix defined
   in the corresponding "import" statement.  Otherwise, the prefix in
   the string value is the prefix for the current module.
```

The times where "when" statement appears in the whole "public" project is 217, which is calculated by using the command below:
```shell 
grep -rn "when \"" * | wc -l
```

I know it's a complicated task to modify all these conditions, but it's helpful for standardization. So if the member of OpenConfig agrees on this suggestion, please let me know and I will submit a patch to fix it.

**Comment by aashaikh** [comment]
Couple of things here:

* OpenConfig models are YANG 1.0, hence the relevant text is from [RFC 6020](https://tools.ietf.org/html/rfc6020#section-9.10) which could have a couple of interpretations:
```
If the prefix is not present, the namespace of the identityref is the default namespace
in effect on the element that contains the identityref value.
```
* Not all tools behave the same way (or have bugs) as you have also seen with confd vs. libyang -- the libyang library (used in Netopeer2) enforces a prefix requirement on all modules it seems based on several similar reports.  We use multiple tools to validate modules, but we can't be exhaustive.

* That said, we've already started making some of these changes to add prefixes on identity values in `when` statements as they come up;  the 217 `when` statements you cite don't all involve identities, nor are they all lacking namespace prefixes.

**Comment by BoyuanYan** [comment]
I didn't realize that OpenConfig is based on YANG 1.0. It's my negligence. Thanks very much for your reply!
