### ISSUE TITLE
Openconfig-platform-transceiver.yang augment statement

### ISSUE THREAD

**Issue by Nshet** [openconfig/public#226]
Hi,
  augment "/oc-platform:components/oc-platform:component" {

    description

      "Adding transceiver data to physical inventory";

    uses port-transceiver-top {

      when "current()/oc-platform:state/" +

        "oc-platform:type = 'TRANSCEIVER'" {

        description

          "Augment is active when component is of type TRANSCEIVER";

      }

    }

  } The above x-path should be like below:
 when "current()/oc-platform:state/" +
        "oc-platform:type = 'oc-platform-types:TRANSCEIVER'" {
        description
          "Augment is active when component is of type TRANSCEIVER";
      }
    }
  
please fix it as soon as possible.

**Comment by aashaikh** [comment]
See the discussion in #223.
