### ISSUE TITLE
identities in openconfig-acl model

### ISSUE THREAD

**Issue by einarnn** [openconfig/public#23]
We have this identity:

```
  identity FORWARD {
    base ACL_ACTION_TYPE;
    description
      "Forwarding-related actions";
  }
```

And then this one:

```
  identity FORWARDING_ACTIONS {
    description
      "Base identity for forwarding-related actions";
  }
```

This is a bit confusing. Is there a typo here in the descriptions? Also, the names are very close.

Cheers,

Einar

**Comment by aashaikh** [comment]
This is just a chained identity -- the intention is to provide multiple categories of actions (the `ACL_ACTION_TYPE` base identity), one of which is related to forwarding actions (`FORWARDING_ACTIONS` base identity) which then includes things like `ACCEPT`, `DROP`, ...

We can add some further description text to clarify.
