### ISSUE TITLE
OSPF3 model is missing

### ISSUE THREAD

**Issue by cpeng90** [openconfig/public#232]
Ciena is currently implementing openconfig Yang model. What we found is that the current openconfig model is lack of OSPFv3 model. As a reference to the structure of OSPFv2 model, we developed OSPFv3 model and would like to contribute the model to the community for discussion as a starting point. If there has already been an OSPFv3 model under construction, we would like to know in order to streamline with our development.

Attached please find the OSPF3 model.

Thanks,
Cheng

[openconfig-ospfv3.tar.gz](https://github.com/openconfig/public/files/3253936/openconfig-ospfv3.tar.gz)

**Comment by robshakir** [comment]
Thanks for this contribution.

There is not an existing OSPFv3 model submission in progress. I believe there is some interest from others in contributing here. 

It'd be good to get some additional discussion as to the layout here. There's a lot of commonality with the OSPFv2 model - but no sharing between the two models today. Are there parts that we should refactor out to have common definitions and increase the maintainability of the two models?

I'd encourage additional discussion here (cc: @earies) to discuss how OSPFv[23] should interact with each other, and then we can start to see how we want to start to shepherd this contribution into a PR.

**Comment by cpeng90** [comment]
Thanks Rob.

We understand that there are a lot of commonality between OSPFv2 and OSPFv3 from internal implementation perspective. However, they are two different protocols from user perspective. In the current openconfig network-instances model, different protocols are distinguished under the network-instances/network-instance/protocols. Therefore, it is natural to have ospfv3 as a new protocol instance of instances/network-instance/protocols/protocol. Note that the arrangement of the openconfig network-instance model is different from IETF OSPF Yang model in that the latter distinguishes V2 and V3 within the OSPF container.  Using the IETF OSPF method on Openconfig model may introduce unnecessary confusion because it requires protocol to be distinguishable at different layer of the Yang tree.

I agree with you that the OSPFv3 model should use as many as common modules defined in the OSPFv2 model. This is actually what we have done. Just my two cents...

Regards,
Cheng

**Comment by jefftant** [comment]
Cheng,

Agree with you on a separate model for v3.

Cheers,
Jeff

**Comment by robshakir** [comment]
Sorry, I didn't mean to imply that we should have the same model for OSPFv3. I just would like to ensure that we have as much commonality across them as possible. The only import today is `openconfig-ospf-types`, but it seems like there should be more commonality than this -- e.g., do we really need another definition of the `metric` which is almost identical to the one [here](https://github.com/openconfig/public/blob/master/release/models/ospf/openconfig-ospfv2-area-interface.yang#L106)? I'm not sure I see the commonality that you're describing.

I'd suggest that a good start for this module is to get to a PR that gives us the very basic config (no LSDB to start with, perhaps just area and interface config) and agree that approach. We can then build that model up through a series of small PRs.

r.

**Comment by cpeng90** [comment]
Agree. The other thing is it would be better to abstract some definition in OSPFv2 to OSPF common so that it can be used by OSPFv3. We can prepare a draft to start with (only config and interface) with your comments and see how thing goes.

**Comment by jefftant** [comment]
And here IETF ospf model could be quite helpful (work is practically done,
draft has been submitted to IESG)

**Comment by cpeng90** [comment]
Ciena and Arrcuss created a dev branch on repo https://github.com/cpeng90/Ciena-Openconfig for discussion of the openconfig OSPFv2 and OSPFv3 model. We are trying to reuse as many existing OSPF modules as possible when defining OSPFv3 model and updated the missing leafs or containers in the existing model which are defined by RFC. Meanwhile, there are still a lot of work that needs to be done to ensure the compliance of the model to the standard. We welcome the operators and other vendors to provide feedbacks, comments and contributions.

Regards,
Cheng

**Comment by cpeng90** [comment]
@robshakir @jefftant 

Sorry for taking long to respond to the thread. I have created a PULL request (see below) creating a common OSPF model for both OSPFv2 and OSPFv3. The OSPFv2 portion looks nearly the same as the existing model except for fixing errors and adding missing leaves. Could you please have a look at the request and see whether it is ok? Thanks.
 
https://github.com/openconfig/public/pull/281

**Comment by vneelamegam** [comment]
Pull request 281 (https://github.com/openconfig/public/pull/281) addressed most of the pending configs in the OSPFv2 model and added OSPFv3. Why was this not taken forward?
