### ISSUE TITLE
ietf-if:interface-type used in leaf type under grouping interface-phys-config does not contain any identities

### ISSUE THREAD

**Issue by rrbrunda** [openconfig/public#233]
Hi,
In openconfig-interafces.yang,  leaf "type" under grouping  "interface-phys-config" uses identityref of type "ietf-if:interface-type".  The interface-type identity in ietf is not mapped to any interface-type.
However,  the identity interface-type in openconfig-if-types.yang has interface types mapped to it.
Could you please let me know  if there is any reason to use "ietf-if:interface-type" in leaf type.
leaf type {
      type identityref {
        base ietf-if:interface-type;
      }
}
with Regards,
Brunda

**Comment by robshakir** [comment]
Hi!

`ietf-if:interface-type` is an base identity. All of the interface types that are defined in `iana-if-type` (RFC7224) extend this base identity - such that OpenConfig's use of this module gets all of the IANA-defined interface types.

OpenConfig is intending to transition towards the `openconfig-if-types` module -- however, this is a backwards incompatible change to solely transition to this module - so the change has been controlled. The motivation for the change is that the IANA interface types have a lot of legacy interface types within them that are no longer relevant.

Cheers,
r.
