### ISSUE TITLE
IS-IS and ospfv2  models are instantiated in terms of the network instance. bgp model is instantiated in both network-instance and bgp

### ISSUE THREAD

**Issue by rrbrunda** [openconfig/public#234]
Hi,

I observe that IS-IS and ospfv2  models are instantiated in terms of the network instance only .
Bgp model is instantiated both from openconfig-bgp.yang and openconfig-network-instance.yang.
Both of  the yang files (openconfig-bgp.yang and openconfig-network-instance.yang)have  "uses bgp-top" statement. Could you please let me know the rationale for the difference in model for ospfv2 and bgp.  The model diagram in the link http://www.openconfig.net/projects/models/ does not show  bgp as a seperate model.

With Regards,
Brunda

**Comment by robshakir** [comment]
Hi!

The next major revision of the BGP module removes the `/bgp` path, in preference to that in `/network-instances/network-instance/protocols/protocol/bgp`. The reason that the model existed in both locations was that this was one of the very first modules that OpenConfig developed, and was implemented by vendors. We've been working with those vendors to transition their implementations to the network instance path, and are now ready to deprecate the old path. This change will be pushed in the next private to public transition.

Thanks,
r.
