### ISSUE TITLE
Need a top level grouping for Telemetry module 

### ISSUE THREAD

**Issue by bijoymc** [openconfig/public#25]
Hi,

All the other yang modules defines a top level grouping. 
Please add a top level grouping for Telemetry module as well, which can help in making it consistent with the other yang models. 
Also this helps in adding features on top of this model.

Looking at something like,
@@ -29,6 +29,12 @@
     reference "0.2.0";
   }

+
-  grouping telemetry-system-top {
-     description
-      "Top-level grouping for interface configuration and
-      operational state data";
  +
  container telemetry-system {
   description
     "Top level configuration and state for the
  @@ -438,6 +444,7 @@
     }
   }
  }
-  }
  
  // extension statements

@@ -722,6 +729,8 @@
     }
   }
-  uses telemetry-system-top ;
  +
  // data definition statements
  
  // augment statements

Thanks!
Bijoy.

**Comment by robshakir** [comment]
Hi Bijoy,

Thanks for the issue - I agree that there are some elements of this module that need to be brought in-line with the OpenConfig style guide. We'll start to do this, and push a new revision with a `telemetry-top` grouping following review in the private repo.

Thanks!
r.
