### ISSUE TITLE
Openconfig  support for netconf configuration

### ISSUE THREAD

**Issue by apathak1990** [openconfig/public#250]
Currently we don't have any model to configure netconf on a device using Openconfig 
We can configure grpc  via Openconfig . Is it possible to add support for netconf config using openconfig like we have for grpc . Most of the vendors uses netconf over ssh protocol .

**Comment by aashaikh** [comment]
If you would like to propose modeling for this (see the [External submissions guide](https://github.com/openconfig/public/blob/master/doc/external-contributions-guide.md)), I'd be willing to help shepherd it.
