### ISSUE TITLE
IGMP/MLD snooping

### ISSUE THREAD

**Issue by nahmed77** [openconfig/public#255]
Hello,

I want to add support to enable IGMP/MLD snooping on a VLAN.  I don't see it being defined anywhere. I have to augment an existing yang model or add a new yang model for IGMP/MLD snooping. Appreciate, If someone from the community can help me or guide me in finding the best way to do it. 

-regard's Nasir

**Comment by aashaikh** [comment]
Where to add this depends on where the right place to configure /monitor this would be (e.g., as part of IGMP config, referencing the VLANs to enable).  I'd suggest to start by looking at how a few platforms from different vendors support this, and propose extensions to add the core configuration and opstate leaves accordingly.  I'm not sure this would need a separate YANG module -- you could simply propose additions to the current openconfig-igmp.yang module.

**Comment by nahmed77** [comment]
Hi,
Thanks for your suggestion.  I did some study on other vendors model. All of them have a separate yang module for igmp-snoop. 

Below is an expert from ietf draft for igmp-mld-snooping-yang the igmp-snooping-instance:
--------- excerpt start -------------
For the BRIDGE scenario this model augments /dot1q:bridges/dot1q:bridge
to reference igmp-snooping-instance. It means IGMP Snooping is enabled
in the whole bridge.

augment /dot1q:bridges/dot1q:bridge:
       +--rw igmp-snooping-instance?   igmp-snooping-instance-ref

It also augments /dot1q:bridges/dot1q:bridge/dot1q:component/
dot1q:bridge-vlan/dot1q:vlan to reference igmp-snooping-instance. It
means IGMP Snooping is enabled in the certain VLAN of the bridge.

   augment /dot1q:bridges/dot1q:bridge/dot1q:component/dot1q:bridge-vlan/dot1q:vlan:
       +--rw igmp-snooping-instance?   igmp-snooping-instance-ref
--------- excerpt end -------------

Combining all variable into one module is not a very clean approach.
Some variables have meaning at a global level and some at VLAN level.
For example, the IGMP membership database is per VLAN level and not at a global level.
Similarly the static-group command. I think having two modules targeted for each 
scope of configuration will keep things simple and more readable.

Having said that, I think we have three options.

Option - 1:
-----------
The equivalent of whole bridge in openconfig is network-instance (am I right). Therefore, augment the
network-instance with igmp-snoop-global module.

The equivalend of dot1.q is vlan module. so augment vlan module with
igmp-snoop-vlan module.

Option - 2:
----------

Since igmp-snoop is an L2 protocol create a similar yang module parallel to stp in the openconfig.
This moudle will follow the stp way of defining the variables (global + vlan list)

Option - 3:
-----------

Embed the igmp-snoop variables in the openconfig igmp.yang module.
I do not prefer this becuase, igmp-snoop and igmp are completely different module.
For example:

 - One runs on vlan and other on l3 interfaces.
 - igmp-snoop has router port configuration 
 - igmp-snoop as querier enable disable configuration.
 - igmp-snoop has its own forwarding table similar to fdb
 - igmp-snoop runs on a pure l2 switch.
 
Such differences may cause confusion and our yang file may become complex.
even if we do it this way we will have similar yang module as option-2 (global + vlan list)

Please let me know your view/suggestions.

-regard's Nasir
