### ISSUE TITLE
ieeefloat32 in openconfig-types.yang is binary format. This is not user friendly because user don't know value directly.

### ISSUE THREAD

**Issue by sangdhan** [openconfig/public#261]
ieeefloat32 in openconfig-types.yang is binary format. This is not user friendly because it has to convert binary format to float to catch the exact value. I think background engine or system might be working with ieeefloat32 format but data itself should be display as float value to understand value directly without any converting action. If this value display it as binary, then users don't catch the value directly and it is annoying users.

  typedef ieeefloat32 {
    type **binary** {
      length "4";
    }
    description
      "An IEEE 32-bit floating point number. The format of this number
      is of the form:
        1-bit  sign
        8-bit  exponent
        23-bit fraction
      The floating point value is calculated using:
        (-1)**S * 2**(Exponent-127) * (1+Fraction)";
  }

**Comment by aashaikh** [comment]
I'm not sure what system you're using but this is something that could be handled in its presentation layer (i.e., a simple float->string conversion?).  If I understand what you're asking, you basically want this float type to be a string for the purposes of display to a user -- which I don't think makes sense here.

**Comment by robshakir** [comment]
Given that decimal64 is a fixed-precision type, and float32 is not - I'm not sure what you're proposing here. YANG doesn't have a floating point type, so this is the solution to ensure that we're able to use one. I agree that it is suboptimal that it is not - by default - displayed as such, but we're rather constrained by the language here. IETF NETMOD has historically not accepted this change - there's a long thread [here](https://mailarchive.ietf.org/arch/msg/rtg-yang-coord/1wZ9uunJx0PF-SwXDwGBkM8lc18).

**Comment by sangdhan** [comment]
Hi Rob,

It looks not clear yet. What I understand,  Yang doesn’t support float type, so binary float format is used to display float type.

Float 250.0 is binary 01000011011110100000000000000000.
I just want to know how ieeefloat32 binary format data should be displayed.
First one or Second one at below example? Please let me clear.

                        <capacity xmlns="http://openconfig.net/yang/platform/psu">250.0</capacity<http://openconfig.net/yang/platform/psu%22%3e250.0%3c/capacity>>

                        <capacity xmlns="http://openconfig.net/yang/platform/psu">01000011011110100000000000000000</capacity<http://openconfig.net/yang/platform/psu%22%3e01000011011110100000000000000000%3c/capacity>>

Best Regards,
Sangdon Han

**Comment by rgwilton** [comment]
There is also this issue https://github.com/netmod-wg/yang-next/issues/34.  Rob, if you really want float/double then it might be helpful to comment directly on that issue.

**Comment by aashaikh** [comment]
The YANG [spec](https://tools.ietf.org/html/rfc6020#section-9.8)  (OpenConfig modules are YANG 1.0) dictates that the lexical representation of a binary type is base64.  So I expect the most "correct" thing is to use that since you are using XML here.

If there is a system receiving these messages and providing a view of the data, it could translate to a more human-readable view -- that's what I meant earlier in this thread by having a presentation layer.

**Comment by sangdhan** [comment]
Hi Anees,

I think every yang data type definition is for the presentation layer not for system level.  Like Boolean or date-and-time, it defines how data is displayed. We are using Netconf and it doesn’t convert data after it gets from system.

If  ieeeflot32 is system level data, then yang spec might be changed to display as decimal float point and it should mention system should follow ieeeflot32 format to avoid confusion.

Of course, we can remove converting part from float to binary for human-readable.

Please make sure whether your suggestion is official announcement or just your opinion because I don’t want later someone complains data displaying is not matching with Yang spec when binary data format changes it to decimal point value.

Best Regards,
Sangdon Han

**Comment by aashaikh** [comment]
"I think every yang data type definition is for the presentation layer not for system level"

Sorry, I don't understand this comment -- the spec indicates a lexical and canonical representation for every YANG built-in type for this purpose.  In the case of binary values, both are base64.

**Comment by sangdhan** [comment]
HI Anees,

Another way is changing data type from ieeefloat32 to decimal64 with 2 fraction-digits like other properties using float data. Then this doesn’t touch ieeefloat32 definition itself which can be used other Yang files.

Openconfig-platform-psu.yang :

  grouping psu-state {
    description
      "Operational state data for power supply components";
    leaf capacity {
      type oc-types:ieeefloat32;   ==>     type decimal64 {
          fraction-digits 2;
      }
      units "watts";
      description
        "Maximum power capacity of the power supply.";
      }
    }
    leaf input-current {
      type oc-types:ieeefloat32;   ==>     type decimal64 {
          fraction-digits 2;
      }
      units "amps";
      description
        "The input current draw of the power supply.";
      }
    }

Best Regards,
Sangdon Han

From: "Sangdon Han (sangdhan)" <sangdhan@cisco.com>
Date: Tuesday, October 15, 2019 at 9:14 AM
To: openconfig/public <reply@reply.github.com>, openconfig/public <public@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [openconfig/public] ieeefloat32 in openconfig-types.yang is binary format. This is not user friendly because user don't know value directly. (#261)

Hi Anees,

I think every yang data type definition is for the presentation layer not for system level.  Like Boolean or date-and-time, it defines how data is displayed. We are using Netconf and it doesn’t convert data after it gets from system.

If  ieeeflot32 is system level data, then yang spec might be changed to display as decimal float point and it should mention system should follow ieeeflot32 format to avoid confusion.

Of course, we can remove converting part from float to binary for human-readable.

Please make sure whether your suggestion is official announcement or just your opinion because I don’t want later someone complains data displaying is not matching with Yang spec when binary data format changes it to decimal point value.

Best Regards,
Sangdon Han

**Comment by sangdhan** [comment]
Hi Anees,

Even base64 is not human readable based on rfc4648 section-4.

I means defined type in yang file is data format which describes how data is displayed and which user might see.  Thus I think all day types in yang are for presentation layer.

As I mentioned previous email, to avoid ambiguous, it is better changing data type using ieeefloat32 to decimal64 with 2 fraction digit.

Of course, without changing any data type, ieeeflot32 data type can be displayed as decimal point value as you mentioned. If you want to this, then make sure this is official opinion of your group.

Best Regards,
Sangdon Han

**Comment by robshakir** [comment]
Note: We should not change the existing `ieeefloat32` definition in-place to allay these concerns, regardless of the outcome of this discussion. We have leaves in the models that are actually float32 on the wire (e.g., reserved bandwidth in IS-IS TE attributes) - since we want to faithfully include these within the telemetry data that is exported for LSDB then an in-place change will negatively impact these models.

**Comment by sangdhan** [comment]
HI Rob,

Yes I’m agree with you because it might affect other models using this data type.
Thus my suggestion is changing property data type in openconfig-platform-psu.yang from ieeefloat32 to decimal64 type with 2 fraction digits.

Best Regards,
Sangdon Han

**Comment by ishidawataru** [comment]
I also came across this issue.

I'd like to mention that the temperature values are using decimal64 with 1 fraction digits in `openconfig-platform` model.

https://github.com/openconfig/public/blob/master/release/models/platform/openconfig-platform-types.yang#L86-L133

It would be better if we have some sort of consistency in the model.
