### ISSUE TITLE
Possible incorrect path in openconfig-qos-elements.yang

### ISSUE THREAD

**Issue by marcusyuri** [openconfig/public#263]
535c559
<           when "config/queue-type = 'oc-qos-types:RED'" {
---
>           when "../config/queue-type = 'oc-qos-types:RED'" {
542c566
<           when "config/queue-type = 'oc-qos-types:WRED'" {
---
>           when "../config/queue-type = 'oc-qos-types:WRED'" {

**Comment by aashaikh** [comment]
Can you please explain this a bit more -- is there an error you are seeing when validating the modules?

**Comment by marcusyuri** [comment]
Hello, Annes. Thank you for the question. I am using an evaluation version of Cisco NSO, that is free for download for non production utilization. The tooling is called Cisco netsim, that allows to import an yang device model, and simulate the corresponding auto-generated command line.

When I import this particular yang files, it complies about a typo in xpath expression:

/home/marcus/nso-4.7.5/bin/ncsc --ncs-compile-bundle yang                        \
                 --ncs-device-dir ncsc-out   \
                 --ncs-device-type netconf            \
                  &&                          \
        cp ncsc-out/modules/fxs/*.fxs ../load-dir;
yang/openconfig-qos-elements.yang:535: **error: the node 'config' from module 'openconfig-qos' (in node 'queues' from 'openconfig-qos') is not found**

        If I remove the "../" from the path, it compiles ok, so it apears to be a typo on the xpath expression.
