### ISSUE TITLE
query regarding INSTALL_PROTOCOL_TYPE

### ISSUE THREAD

**Issue by zubinbm** [openconfig/public#27]
Can anyone give more details for me to understand the functionality of "install-protocol-eq" which comes in openconfig-routing-policy model?
What if there are multiple instances of same protocol: like ospf-100 and ospf-200?

If possible can you give an example with equivalent CLI commands?

leaf install-protocol-eq {
type identityref {
base oc-pol-types:INSTALL_PROTOCOL_TYPE;
}
description
"Condition to check the protocol / method used to install
the route into the local routing table";
}

**Comment by robshakir** [comment]
The functionality provided by `install-protocol-eq` is to provide the ability to match entries that were installed by a particular protocol into the RIB - i.e., to allow prefixes that were installed by BGP to be identified by a policy model match criteria. 

In some cases (as you observe), `install-protocol-eq` by itself may not provide all match functionality that is expected by the policy (for example, `install-protocol-eq` of OSPF might match all instances of OSPF that are populating the RIB that is being considered by the policy, whereas there may be a requirement for more granular matching). In the case that multiple instances of a particular protocol are allowed, the relevant protocol-specific policy elements (e.g., see the BGP policy module) provide this additional functionality.

Equivalent CLI commands exist in most routing protocol implementation languages - see Juniper's `from { protocol } }`, and ALU's `from ... protocol`. Other implementations may not directly allow matching of the installing protocol based on the fact that their policies are instantiated in the context of an individual protocol. The `network-instance` model provides the framework within which the different RIB structures of network elements can be represented.

Cheers,
r.
