### ISSUE TITLE
OPENCONFIG BFD related Queries to un-block Micro-bfd session support

### ISSUE THREAD

**Issue by rvelucha** [openconfig/public#277]
1.  /bfd/interfaces/interface[id]/config/local-address?   oc-inet:ip-address
---> It specifies either of v4 or v6 address can be configured per interface.
---> Does that BFD session can be present only for v4 or v6 for an interface and not for both types.

2. /bfd/interfaces/interface[id]/state/enable-per-member-link?   boolean (Default:false)
-----> When “enable-per-member-link” leaf is set the intend is enable BFD on all member link of Bundle, but there is no “remote address” present here. 
a) Because all the Bundle Parent and Member session will be created from Bundle Manager, so in BFD we need to map to Bundle Manager for these session create, for which both “Parent interface/destionation address” must be configured at same time. However this is difficult today because of below reasons.
b) We see that member “local/remote address” comes under micro-bfd-session table. In our opinion we don’t require this be configured on per member interface level, as the BFD session will be using same local/remote address for each of the member link.
c) So can we have “local/remote address” at the parent interface level along with “enable-per-member-link” itself.

3. /bfd/interfaces/interface[id]/micro-bfd-sessions/micro-bfd-session[member-interface]/state/session-state?   bfd-session-state
-----> For Micro BFD session walk has only Parent and Member interface as key, but for same Parent and Member combination we can have two different session running (one for v4 and other for v6)
-----> So in those cases which exact entry to be returned to OC when the query is done for this field.

**Comment by s19nal** [comment]
I'll take a look at this and propose some model changes we can review. Some of your points make sense and I can see some simplifications to the model that would help.
I have a couple of questions - are you expecting to be able to support v4 and v6 at the same time? As you pointed out, currently the model supports a single addressed session.  
For uBFD on multiple links, each member link session will get a unique local-discriminator, correct?
thanks
Simon

**Comment by rvelucha** [comment]
Hello Simon,

Thanks for response. We would really appreciate your ACK on our queries posted here.

Yes we would suggest that both v4/v6 BFD session can be present for same interface and destination pair.

Regarding other query, Yes each member link of uBFD will have unique local-discriminator.

Would it be possible for you to revert back on when these queries can be incorporated in OC Model that will help us make progress on our Development.

Regards
V.Rajaguru
XR/BFD/PI

**Comment by rvelucha** [comment]
Hello Simon,

Would you like to share some update on this please.

Regards
V.Rajaguru
XR/BFD/PI

From: Rajaguru Veluchamy (rvelucha) <rvelucha@cisco.com>
Sent: Wednesday, December 11, 2019 2:57 PM
To: openconfig/public <reply@reply.github.com>; openconfig/public <public@noreply.github.com>
Cc: Author <author@noreply.github.com>; Ananthakrishnan Rajamani (anarajam) <anarajam@cisco.com>; Rajaguru Veluchamy (rvelucha) <rvelucha@cisco.com>
Subject: RE: [openconfig/public] OPENCONFIG BFD related Queries to un-block Micro-bfd session support (#277)

Hello Simon,

Thanks for response. We would really appreciate your ACK on our queries posted here.

Yes we would suggest that both v4/v6 BFD session can be present for same interface and destination pair.

Regarding other query, Yes each member link of uBFD will have unique local-discriminator.

Would it be possible for you to revert back on when these queries can be incorporated in OC Model that will help us make progress on our Development.

Regards
V.Rajaguru
XR/BFD/PI
