### ISSUE TITLE
Not possible to compile openconfig-terminal-device.yang

### ISSUE THREAD

**Issue by kackola** [openconfig/public#28]
I downloaded latest version of yang models and compiled them with confdc and got some errors.

The augment path in openconfig-if-ethernet.yang is incorrect
Next problem is in openconfig-terminal-device.yang, the leafref path in logical-channel at line 457 and 473 seem to be wrong.
Seems like stuff is moved around and the paths are not updated accordingly.

**Comment by aashaikh** [comment]
thanks for raising these ... we have not compiled OpenConfig models with confdc so have not seen these issues.  do you also see them with pyang?

1. can you elaborate a bit on the augment path issue in the ethernet module -- we may refactor the `when` statement a bit to avoid the conditional augment, but otherwise the path seems to be ok

2.  i suspect there may be a similar issue with XPATH validation of the must statement in these leafrefs?   the leafref paths seem ok but pyang does an incomplete job of XPATH expression validation -- again, if you could elaborate on the error you're seeing, that would be helpful

**Comment by vprasad** [comment]
Issue 1 :-for openconfig-if-ethernet.yang ,there is augment statement like :- 
 augment "/oc-if:interfaces/oc-if:interface" {
    when "oc-if:type = 'ift:ethernetCsmacd'" {

But when we compile using confdc compiler it throws error saying type is not found in openconfig-interfaces.yang.
However when i change it to :- 
augment "/oc-if:interfaces/oc-if:interface" {
    when "oc-if:config/oc-if:type = 'ift:ethernetCsmacd'" {

Now it compiles file i.e., i specify the container in which type is present.
 
Issue 2 :-all the must expression present in opencnfig-terminal-device.ynag are failing.Below is the error:- 
g: The 'must' expression will fail: the node 'LOGICAL_CHANNEL' from module 'openconfig-terminal-device' (in node 'logical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:453: warning: The 'must' expression will fail: the node 'assignment-type' from module 'openconfig-terminal-device' (in node 'logical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:453: warning: The 'must' expression will fail: the node 'LOGICAL_CHANNEL' from module 'openconfig-terminal-device' (in node 'logical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:467: warning: The 'must' expression will fail: the node 'assignment-type' from module 'openconfig-terminal-device' (in node 'optical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:467: warning: The 'must' expression will fail: the node 'OPTICAL_CHANNEL' from module 'openconfig-terminal-device' (in node 'optical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:467: warning: The 'must' expression will fail: the node 'assignment-type' from module 'openconfig-terminal-device' (in node 'optical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:467: warning: The 'must' expression will fail: the node 'OPTICAL_CHANNEL' from module 'openconfig-terminal-device' (in node 'optical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:820: warning: The 'must' expression will fail: the node 'operational-modes' from module 'openconfig-terminal-device' (in node 'components' from 'openconfig-platform') is not found
openconfig-terminal-device.yang:820: warning: The 'must' expression will fail: the node 'operational-modes' from module 'openconfig-terminal-device' (in node 'components' from 'openconfig-platform') is not found
openconfig-terminal-device.yang:820: warning: The 'must' expression will fail: the node 'operational-modes' from module 'openconfig-terminal-device' (in node 'components' from 'openconfig-platform') is not found
openconfig-terminal-device.yang:820: warning: The 'must' expression will fail: the node 'operational-modes' from module 'openconfig-terminal-device' (in node 'components' from 'openconfig-platform') is not found

Thanks,
Vivek Prasad

**Comment by vprasad** [comment]
can any one please tell why the above openconfig yangs are not compiling.

**Comment by Maconair** [comment]
Hello everyone,
I'm a little late to this thread, but I'd like to ask if a solution has been found for this error

**Comment by dplore** [comment]
Hi, we are not seeing this issue with pyang?  I suspect this issue is obsolete.  Please feel free to reopen the issue.  If so, please provide links to the build you are using.  I don't work with confdc and we don't test with it either in our CI checks so you'll have to provide the full details of your build.
