### ISSUE TITLE
Question Reg: “routing-policy/defined-se/..."

### ISSUE THREAD

**Issue by thilak07** [openconfig/public#286]
The public repo does not show “routing-policy/defined-set/… anymore? I can see that in the model browsers at http://ops.openconfig.net/branches/models/OC/openconfig-routing-policy.html#
However, not in the public repo https://github.com/openconfig/public/tree/master/release/models. Did “routing-policy/defined-set/..“routing-policy/defined-set ? moved elsewhere?

**Comment by aashaikh** [comment]
Location of defined sets haven't changed -- they should still be under `/routing-policy/defined-sets` . Note that protocol-specific policy conditions/actions/defined-sets are augmented into the base policy model by the corresponding protocol model.  So BGP policy elements, for example, are augmented into `routing-policy` by `openconfig-bgp-policy.`

**Comment by thilak07** [comment]
I was pointing "generator.go" only to "openconfig-bgp.yang" and was looking for defined-set elsewhere. I am able to generate all models now. Thanks for the help!.
