### ISSUE TITLE
Inconsistent use of `enable` vs. `enabled` leaf naming

### ISSUE THREAD

**Issue by exa-arrcus** [openconfig/public#288]
For leafs that represent enablement/disablement of a domain/service, etc... there are inconsistencies throughout the entire model set of the use of `enable` vs. `enabled`

```
$ grep -RE "leaf enable[d]? {" * | awk '{print $2,$3}' | sort | uniq -c
     11 leaf enable
     41 leaf enabled
```

**Comment by aashaikh** [comment]
We opened an issue to look into this -- agree it would be nice to have some normalization of terms where possible.  I did look into it in a bit more detail and see that at least there is consistency within models/modules.
