### ISSUE TITLE
Can hostname of the device be leaf-list ? 

### ISSUE THREAD

**Issue by sureshboyapati** [openconfig/public#289]
As per the below description, it looks like we have leaf-list for the hostname. 
As hostnames are unique, can it be just a leaf, rather than leaf-list?

container hostname {
          when "../state/type = 'oc-isis-lsdb-types:DYNAMIC_NAME'" {
            description
              "Include the dynamic hostname TLV only when the TLV is
              type 137.";
          }
          description
            "This container defines TLV 137.";

          container state {
            description
              "State parameters of ISIS TLV 137.";

            leaf-list hostname {
              type string;
              description
                "Name of the node.";

              reference
                "RFC6233: IS-IS Registry Extension for Purges, RFC
                5301: Dynamic Hostname Exchange Mechanism for IS-IS.
                TLV 137";
           }
         }
        }

**Comment by robshakir** [comment]
In the IS-IS model we have a single container for a particular TLV, but there's nothing that guarantees that there's just one instance of that TLV in the packet. To allow this corner case to be reported, we either have something that allows multiple instances of the same TLV, or for TLVs that carry a singular set of information, we make the field a `leaf-list` to allow for it to be reported.
