### ISSUE TITLE
Open-config: Oc schema for hello-interval and refresh reduction needs to be changed.

### ISSUE THREAD

**Issue by ramkijnpr** [openconfig/public#29]
Description*
In the oc schema under the hellos we have hello-interval and refresh reduction. This needs to be changed.
Hence i request this modification has to be happened in the OC schema. I have filed this PR as Modification

```
edit]
regress@10.102.177.71# set openconfig-mpls:mpls signaling-protocols rsvp-te interface-attributes interface all hellos ?
Possible completions:
+ apply-groups         Groups from which to inherit configuration data
+ apply-groups-except  Don't inherit configuration data from these groups
> config               Configuration parameters relating to RSVP
                       hellos
[edit]
regress@10.102.177.71# set openconfig-mpls:mpls signaling-protocols rsvp-te interface-attributes interface all hellos config ?
Possible completions:
+ apply-groups         Groups from which to inherit configuration data
+ apply-groups-except  Don't inherit configuration data from these groups
  hello-interval       set the interval in ms between RSVP hello
                       messages (1..60 seconds)
  refresh-reduction    enables all RSVP refresh reduction message
                       bundling, RSVP message ID, reliable message delivery
                       and summary refresh
[edit]
regress@10.102.177.71# set openconfig-mpls:mpls signaling-protocols rsvp-te interface-attributes interface all hellos config    
```

**Comment by robshakir** [comment]
Hi!

Unfortunately I don't quite understand what you would like fixed here -- please could you give a little explanation as to the bug?

Thanks,
r.

**Comment by ramkijnpr** [comment]
Hi Rob,

In the OC-shema for the MPLS config, Under the RSVP-te  we have Hellos.
Under the hellos we have hello config and refresh reduction config.
Refresh reduction is not a hello message , so the we need to replace the hellos to rsvp-messages or soft state messages.


 OC Path-/mpls/signaling-protocols/rsvp-te/global/hellos/config/refresh-reduction


 OC Path-/mpls/signaling-protocols/rsvp-te/global/hellos/config/hello



Thanks
Ramki
