### ISSUE TITLE
Ordinals for enumerable types

### ISSUE THREAD

**Issue by MainlyGauche** [openconfig/public#291]
Many enumerable types lack canonical ordinal values, for a couple of reasons. In some cases, the base `enumeration` simply lacks ordinals. Others have type `identityref`, so their values, which are `identity`s, cannot have ordinals associated at all. This makes the sanest gNMI `TypedValue` encoding for these types a `string_val` or equivalent. In turn, this complicates the type conversion at the boundary of applications written in a language that represent enumerable types as integral values, i.e. most modern applications. A similar complication exists for archival systems that wish to reduce their data footprint.

Modelling all of these enumerable types as a derived type of `enumeration`, each `enum` of which has a `value`, should minimize bugs in systems representing these enumerable types as ordinals internally. It also would permit gNMI support for ordinal values in responses, simplifying those systems.

**Comment by aashaikh** [comment]
Thanks for bringing up this issue -- we did discuss it in the OpenConfig group meeting briefly.   It's not really an option to remove identities (or replace them all with enumerations).  They are important to support extensibility of the models, in particular by third parties (e.g., vendors) who need to create, say, a new component type.   In particular making this change throughout all of the current models seems like a significant challenge (from a compatibility standpoint).

This means that one needs to think about some other workarounds for the items you mentioned, including a separation between presentation of these values and a consistent mapping to ordinal values.  I'd also refer you to the protobuf representation of the models produced by [ygot](https://github.com/openconfig/ygot/tree/master/proto_generator) that  provides some examples of how we've handled this where only enums with ordinal values are supported.
