### ISSUE TITLE
Protocol status of the interfaces in oc-interfaces

### ISSUE THREAD

**Issue by sujeetgoit** [openconfig/public#293]
Hi,

For many vendors, there are protocol status associated with the interfaces. It generally denotes  whether the port is receiving or ready to receive data or not.
Is there any field in oc-interfaces yanf model, to show this status?
If no, can the leaf "protocol-status" be implemented? It will help in case of Event driven telemetry if the protocol goes down.

**Comment by sujeetgoit** [comment]
Hi,

Sorry for late reply.
oper-status leaf is equivalent to administrative state of the interface.
However, the protocol-status is equivalent to Layer2 line protocol status of the interface.

This can be seen in Cisco Devices:

RP/0/RP0/CPU0:NCS1K-SIT-TB1#show ip int br                       
Wed Apr  1 23:37:33.905 IST

Interface                      IP-Address      Status          **Protocol** Vrf-Name
MgmtEth0/RP0/CPU0/0            w.x.y.z    Up              **Up**       default 
MgmtEth0/RP0/CPU0/1            unassigned    Shutdown        Down     default 
MgmtEth0/RP0/CPU0/2            unassigned        Shutdown        Down     default 

RP/0/RP0/CPU0:ios#show interfaces mgmtEth 0/RP0/CPU0/0
Wed Apr  1 23:39:19.708 IST
MgmtEth0/RP0/CPU0/0 is up, **line protocol is up** 
  Interface state transitions: 25

**Comment by dplore** [comment]
[/interfaces/interface/state/oper-status](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-interfaces.html#interfaces-interface-state-oper-status) shows the  L2 operational state.

[/interfaces/interface/state/admin-status](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-interfaces.html#interfaces-interface-state-admin-status) shows if the L2 port is 'enabled' or in other modes as described in the yang.

[/interfaces/interface/state/enabled](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-interfaces.html#interfaces-interface-state-enabled) is the mirror of the config state for enabling an interface.  

Normally the enabled and admin-status leaves will be in the same value.    There is one well known exception when using [gnoi link qualification](https://github.com/openconfig/gnoi/blob/main/packet_link_qualification/packet_link_qualification.proto) where the interface may be enabled, but state/admin-status = `TESTING`.   


FWIW, 
[/interfaces/interface/subinterfaces/subinterface/state/oper-status](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-interfaces.html#interfaces-interface-subinterfaces-subinterface-state-oper-status) shows L3 operational state.    This is typically a mirror of the configuration leaf for enable/disable of a subinterace (L3) interface.  Note, no all platforms support enable/disable of subinterfaces.  In some platforms if a subinterface is configured, it is always up.
