### ISSUE TITLE
How to select fpga image for line-card

### ISSUE THREAD

**Issue by prmanna** [openconfig/public#295]
Hello Team,

Ref: openconfig-terminal-device.yang / openconfig-platform.yang

There is situation, where one line-card supports multiple fpga images, there should be way to select an image for the line-card. Each image supports specific features, it should be programmed on data-path to get the required features in data-path. I don’t see a way to do that. 
In 'openconfig-terminal-device.yang', there is operational-mode, meant to specify vendor-specific parameters. But this is applicable to line-port only, NOT to line-card.
Do you see any way to support the above?

Regards,
Prasenjit Manna

**Comment by ejbrever** [comment]
Hi Prasenjit, I was hoping you could explain the use case a little more. Are you expecting that a device has multiple fpga images on it and each line card in the device selects its own fpga image?

I am not sure if you'd want to make a config change which would result in new software being activated. Generally, this is done through a gNOI operational command. One thought is perhaps we could update a gNOI request with the ability to upgrade a specific line card as opposed to the whole device.

For example, we could add a "target" to these requests which would allow you to perform an upgrade to the targetted linecard:
https://github.com/openconfig/gnoi/blob/master/os/os.proto#L108

Note that we are in a transition phase from the original SetPackage RPC (https://github.com/openconfig/gnoi/blob/master/system/system.proto#L59) to the new ones in the os proto definition.

Depending on your current implementations it might make sense to update one or both of these protos to support something like this.

Please let us know your thoughts.
