### ISSUE TITLE
Inconsistent design on upper/lower bound definitions

### ISSUE THREAD

**Issue by exa-arrcus** [openconfig/public#299]
When a data node is to be represented with a lower and upper bounds, there are 2 techniques in use across the data-model sets

* A type `string` with a pattern restriction dictating a special format of `[lower]..[upper]`
* 2 parallel nodes each representing lower/upper with precise data types

The type `string` can be seen in ACL/VLAN domains while 2 parallel nodes is seen in MPLS/Optical-Transport domains.

While the 1st approach might make for ease of use definitions, it does not represent the original datatype and requires consumers to have to parse strings into correct datatypes while the 2nd approach can use the intended data-types.

The 2nd method also does not carry restrictions in the published data-models (e.g. lower bound node must be less than upper bound node)

**Comment by chrisy** [comment]
Minor comment on the 1st approach you mention; the `xx..yy` syntax for VLANs was deprecated a while back in favor of a more fully modeled set of paths for the various approaches to match VLAN tags.
