### ISSUE TITLE
revision statements are not given in reverse chronological order

### ISSUE THREAD

**Issue by LibinLiu0189** [openconfig/public#304]
Hi, I found the warnings and error as follows in openconfig-spanning-tree.yang and openconfig-spanning-tree-types.yang when I want to generate oc-stp class using pyangbind.

penconfig-yang/stp/openconfig-spanning-tree.yang:38: warning: the revision statements are not given in reverse chronological order
openconfig-yang/stp/openconfig-spanning-tree-types.yang:34: warning: the revision statements are not given in reverse chronological order
INFO: encountered (<pyang.error.Position object at 0x7f782c62fdc0>, 'REVISION_ORDER', ())
FATAL: pyangbind cannot build module that pyang has found errors with.

I checked these two files and found that,

oc-ext:openconfig-version "0.3.0";

  revision "2014-03-14" {
    description
      "Remove the time-since-last-topology-change leaf and
      replace it with a timestamp of last topology change.";
    reference "0.3.0";
  }

  revision "2018-11-21" {
    description
      "Add OpenConfig module metadata extensions.";
    reference "0.2.1";
  }

I gussed it should be,

oc-ext:openconfig-version "0.3.0";

  revision "2019-03-14" {
    description
      "Remove the time-since-last-topology-change leaf and
      replace it with a timestamp of last topology change.";
    reference "0.3.0";
  }

  revision "2018-11-21" {
    description
      "Add OpenConfig module metadata extensions.";
    reference "0.2.1";
  }

Best,
Libin

**Comment by aashaikh** [comment]
Thanks for noting this -- should be fixed in the recent updates to fix a number of pyang validation issues.   We should be able to publish fixed version by next week.
