### ISSUE TITLE
No interface speed for calculation

### ISSUE THREAD

**Issue by bclaise** [openconfig/public#305]
Hi, 

I would like to calculate the link utilization.

leaf negotiated-port-speed {

type identityref
{ *base* ETHERNET_SPEED; }

description "When auto-negotiate is set to TRUE, and the interface has
completed auto-negotiation with the remote peer, this value
shows the interface speed that has been negotiated."; }

The speed is encoded in an identity. I like identities in general, but in case, I don't want to do calculation based on some text in descriptions. 

RFC8343 has got the speed.
         leaf speed {
           type yang:gauge64;
           units "bits/second";
           config false;
           description
               "An estimate of the interface's current bandwidth in bits
                per second.  For interfaces that do not vary in
                bandwidth or for those where no accurate estimation can
                be made, this node should contain the nominal bandwidth.
                For interfaces that have no concept of bandwidth, this
                node is not present.";
           reference
             "RFC 2863: The Interfaces Group MIB -
                        ifSpeed, ifHighSpeed";
         }

The ask is not to change your identities into counters, but to add an extra leaf: 
negotiated-port-speed-value, type gauge64

**Comment by bclaise** [comment]
Anees, any news on this one?

**Comment by aashaikh** [comment]
We discussed this and do plan to add a leaf to support it.  Sorry, it's on the backlog but hope to progress this, along with a few other small suggestions in the next couple of weeks.

**Comment by robshakir** [comment]
@bclaise -- feel free to send a PR for this to speed up this being added. Thanks.
