### ISSUE TITLE
New leaf in openconfig-system-management with no new revision

### ISSUE THREAD

**Issue by nkitchen** [openconfig/public#306]
Commit https://github.com/openconfig/public/commit/fa31fb5446cdfccaa9f38f15df794d3d2f50b4ff added a new leaf [`metadata-authentication`](https://github.com/openconfig/public/commit/fa31fb5446cdfccaa9f38f15df794d3d2f50b4ff#diff-def4657819eb4eabf30618b0b6cb8654) to openconfig-system-management, and it did not add a new revision to the module.

This can create a problem with the OpenDaylight controller, which identifies modules by name and revision in its cache. It may use the older version already cached and thus fail validation of data containing `metadata-authentication`.

**Comment by aashaikh** [comment]
Thanks for pointing out the bug -- this was indeed a miss when reviewing the change.  We will get a new version published with updated version and revision statement.

**Comment by nkitchen** [comment]
This is no longer an issue, since metadata-authentication moved to openconfig-system-grpc.yang in b97c9e2d2ae880afbcd1e7142c2b7c5ff9c66af0.
