### ISSUE TITLE
Suggestion to change speed parameter in openconfig-platform-fan model.

### ISSUE THREAD

**Issue by CFSNM** [openconfig/public#312]
Hello,

I suggest to change the parameter "speed" in the openconfig-platform-fan model for a container with four values: instant, max, min and avg.

Nowadays, it follows the next structure:

![image](https://user-images.githubusercontent.com/22430652/69343139-4d88c900-0c6d-11ea-88e1-443ae243e190.png)

With the change I propose to follow the OpenConfig convention in other models and parameters:

![image](https://user-images.githubusercontent.com/22430652/69343187-672a1080-0c6d-11ea-8510-b224b76e2d17.png)

Regards,

César

**Comment by aashaikh** [comment]
Can you comment on whether there are platforms that support fan speed reporting with min/max/avg values?  My understanding is that this is generally only reported as an instantaneous value.
