### ISSUE TITLE
Incorrect when statement changes in commit  aaf9135

### ISSUE THREAD

**Issue by LeonGWang** [openconfig/public#313]
The when statement changes in master branch commit aaf9135 is incorrect. I believe the commit is based on Li's PR #279, which is in-turn based on the pyang errors he saw in issue #278. However, these pyang errors are incorrect. The bug causing pyang to output incorrect errors is discussed in mbj4668/pyang#495. This bug has since been fixed in pyang commit https://github.com/mbj4668/pyang/commit/4435dfec9396c9c1f3ef6b3c22e4f804a6051f92.

@aashaikh Can you consider verify commit aaf9135 is incorrect using the latest pyang version and revert that commit?

**Comment by aashaikh** [comment]
Thanks for raising this -- we've merged fixes for all of the modules that are showing xpath errors in `when` statements based on the fixes in pyang 2.x (in particular mbj4668/pyang@474e086c).  I also verified using confd 7.x.  These should be published later this week.

**Comment by LeonGWang** [comment]
Bump.

Is there any progress on this?

**Comment by aashaikh** [comment]
This is ready to be published -- was trying to combine with some other updates, but I will decouple and try to publish these updates asap this week.  thanks for pinging.

**Comment by LeonGWang** [comment]
Thanks aashaikh, commit dde2c1c320617cb753e1a448a812d12025cd3925 fixed the issue. I will close this issue.
