### ISSUE TITLE
Not able to generate python classes for vlan model

### ISSUE THREAD

**Issue by hmadhulika** [openconfig/public#316]
When i am trying to generate biniding.py file from openconfig-vlan.yang, it is generating only one class without any functions. Please find the attached screenshot.
<img width="812" alt="vlan_binding_error" src="https://user-images.githubusercontent.com/9612698/71092188-c9265900-21cc-11ea-9db3-25e99ec9f4a6.PNG">

Suggest me to fix this issue.

**Comment by aashaikh** [comment]
The VLAN module does not instantiate any data nodes itself -- it augments data nodes into the interfaces model in various places.  This is evident from the YANG module.    You'll need to build the interface modules (including the vlan module) to generate those classes.

**Comment by hmadhulika** [comment]
I was able to generate classes of interface, i am not getting how to use vlan in it. Can you please provide an example of simple vlan configuration.

**Comment by aashaikh** [comment]
Have a look at the first example in [this doc](https://github.com/openconfig/public/blob/master/doc/network_instance_examples.md) -- it shows how to configure switched vlans (I'm assuming you're trying to do simple L2 VLANs).  The example is the resultant json, but it maps directly into where to find those data elements in the schema (and the generated python classes).

**Comment by sindhujit** [comment]
Hi @aashaikh I work directly with madhulika. What exact YANG module should we use for that ? We tried openconfig-network-instance.yang but it seems trying to create a binding.py file for that creates an error :
``openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:223): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::network-instances"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:269): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::network-instances"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:287): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::network-instances"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:407): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::network-instances"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:625): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::network-instances"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:633): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::network-instances"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:697): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::protocols"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:708): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::protocols"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:719): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::protocols"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:730): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::protocols"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:738): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::protocols"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:749): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::protocols"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:760): warning: node "openconfig-network-instance::config" is not found in "openconfig-network-instance::protocols"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:780): warning: node "openconfig-network-instance::type" is not found in "openconfig-network-instance::network-instance"
openconfig-network-instance.yang:1165 (at openconfig-network-instance.yang:789): warning: node "openconfig-network-instance::type" is not found in "openconfig-network-instance::network-instance"
openconfig-acl.yang:848 (at openconfig-acl.yang:394): warning: node "openconfig-acl::config" is not found in "openconfig-acl::acl-sets"
openconfig-acl.yang:848 (at openconfig-acl.yang:400): warning: node "openconfig-acl::config" is not found in "openconfig-acl::acl-sets"
openconfig-acl.yang:848 (at openconfig-acl.yang:407): warning: node "openconfig-acl::config" is not found in "openconfig-acl::acl-sets"
openconfig-acl.yang:848 (at openconfig-acl.yang:415): warning: node "openconfig-acl::config" is not found in "openconfig-acl::acl-sets"
openconfig-if-aggregate.yang:11: error: circular dependency for module "openconfig-interfaces"

Also we are getting an issue with the package pybindIETFXMLEncoder
`ImportError: cannot import name 'pybindIETFXMLEncoder'`

Seems like that package is not part of pyangbind 0.8.1 as per 
https://stackoverflow.com/questions/51606284/importerror-cannot-import-name-pybindietfxmlencoder
