### ISSUE TITLE
Openconfig Optical Amplifier

### ISSUE THREAD

**Issue by AneesSaifudeen** [openconfig/public#326]
Can you please clarify whether the module represents a single EDFA/Raman component, or if it represents a logical amplifier card that would consist of multiple components.

**Comment by aashaikh** [comment]
@ejbrever
The model supports a component (e.g., linecard) with multiple amplifiers -- the top level of the model is a list (which could also just have a single element).

**Comment by ejbrever** [comment]
I like to think of it as each amplifier in OpenConfig is a logical amplifier gain block. A given hardware component might have various numbers of logical amplifier gain blocks. For example, an EDFA+Raman gain block (i.e. Hybrid Amp Card), a card with a single gain block or potentially many amplifier gain blocks (i.e. Amp-array Card).

The amplifier model also has a component reference that can be used to tie the physical card within the components model to the logical amplifier gain blocks it contains.

**Comment by AneesSaifudeen** [comment]
Thank Anees and Eric for clarification.
