### ISSUE TITLE
Firewall Vendor Engagement - anyone?

### ISSUE THREAD

**Issue by jkoolwal** [openconfig/public#327]
Hi Openconfig Community!

I wanted to check in and see if anyone here has engaged the industry's standard firewall vendors regarding bringing them into the openconfig ecosystem?

Thanks!
Jai

**Comment by aashaikh** [comment]
Thanks for raising this -- we have had some discussions within the operator working group on requirements for a firewall data model, but have not yet engaged with major vendors on this topic.

**Comment by mike-albano** [comment]
Closing this comment thread; re-open if questions persist.
