### ISSUE TITLE
Query on backoff-interval in openconfig-openflow.yang

### ISSUE THREAD

**Issue by pullururajasekhar** [openconfig/public#329]
Hi @aashaikh @robshakir 

Could you please help elaborate on the configuration/behavior of backoff-interval and the max-backoff defined here:
https://github.com/openconfig/public/blob/master/release/models/openflow/openconfig-openflow.yang#L248

My understanding is that:
**The backoff-interval is the minimum number of seconds to wait before attempting to reconnect to the openflow controller. On each failed attempt to reconnect, the time interval to attempt reconnection gets doubled until it reaches the max-backoff value. Once the time interval reaches the max-backoff value, next attempt to reconnect on failure is after max-backoff seconds.**

**### Example with backoff-interval : 4, max-backoff : 16**
```
00:00:01: entering connecting state, connecting to controller.. failed.
00:00:01: entering backoff state
00:00:05: entering connecting state, connecting to controller.. failed.(waited for 4s before reconnect)
00:00:05: entering backoff state
00:00:13: entering connecting state, connecting to controller.. failed.(waited for 8s before reconnect)
00:00:13: entering backoff state
00:00:29: entering connecting state, connecting to controller.. failed.(waited for 16s before reconnect)
00:00:29: entering backoff state
00:00:45: entering connecting state, connecting to controller.. failed.(waited for 16s before reconnect)
00:00:45: entering backoff state
00:00:61: entering connecting state, connecting to controller.. failed.(waited for 16s before reconnect)
00:00:61: entering backoff state
above repeats until successful connection
```

Thanks & Regards,
Rajasekhar

**Comment by aashaikh** [comment]
@samribeiro can comment in more detail, also based on experience with vendor implementations.

**Comment by samribeiro** [comment]
Hi @pullururajasekhar, your interpretation is mostly correct. The backoff-interval is the minimum number of seconds to wait before attempting to reconnect, the default backoff, or starting backoff interval. While the max-backoff is the value that the backoff interval will never surpass or exceed. The exact growing exponential used is not prescribed here and is up to the implementer.

**Comment by pullururajasekhar** [comment]
Hi @samribeiro Thanks for the response. 
As there's no default config for the 'backoff-interval' in the yang model, I hope the implementer is free to chose the starting minimum back off interval.

**Comment by samribeiro** [comment]
Hi @pullururajasekhar, correct, the implementer is free to choose the default value.

**Comment by aashaikh** [comment]
Please reopen if more discussion is needed on this.
