### ISSUE TITLE
openconfig-mpls: missing top level grouping for MPLS configuration and state

### ISSUE THREAD

**Issue by crcampos612** [openconfig/public#330]
Missed "uses mpls-top;" statement at the end of openconfig-mpls.yang module in order to view and drop down schema tree.

**Comment by chrisy** [comment]
`mpls` is imported into `network-instance` at `/oc-netinst:network-instances/oc-netinst:network-instance/mpls`. It's not a standalone root in the hierarchy.

**Comment by crcampos612** [comment]
Thanks for the clarification! I didn't realise. So it means that I should define LSP within network-instance to be used by that specific network-instance service ( L2/L3 VPN ). However, what happen if I need to deploy generic  LSPs ( w/o TE ) in the network not bound to any network-instance but available for any service ?

**Comment by exa-arrcus** [comment]
@crcampos612 this is the intention of the NI type `DEFAULT_INSTANCE`

**Comment by crcampos612** [comment]
Hi, another question about mpls-te model, what about using a hop-limit as a constraint for a LSP ? I don't see it. Thanks again!
