### ISSUE TITLE
How to start with openconfig on hardware device?

### ISSUE THREAD

**Issue by li9270** [openconfig/public#338]
Hello, I want my hardware device to support openconfig. 
Need I write a xxx.yang which fit openconfig standard ? 
I see that there are many yang file in openconfig, but I don't know how to use them.
Is there any tourial or simple example that can help me to understand them?

Thanks a lot!

**Comment by robshakir** [comment]
Hi,

There is no need to define a new module -- you should pick the ones that correspond to features that your hardware device supports, for example, it's very likely that it has network interfaces so you'd likely want to start with `openconfig-interfaces.yang`.  A typical development flow would be to map those modules to your internal configuration schema, and then expose an interface to external management systems using a protocol like [gNMI](https://github.com/openconfig/gnmi/blob/master/proto/gnmi/gnmi.proto).

There isn't really a document that explains how to implement this from an OpenConfig-specific perspective, I'd recommend reading up on YANG modelling and potentially gNMI and coming back with more specific questions.

Many thanks,
r.

**Comment by li9270** [comment]
Thank you for your suggestion！
