### ISSUE TITLE
Not possible to compile the openconfig-terminal-device.yang and openconfig-if-ethernet.yang

### ISSUE THREAD

**Issue by vprasad** [openconfig/public#34]
Issue 1 :-for openconfig-if-ethernet.yang ,there is augment statement like :- 
augment "/oc-if:interfaces/oc-if:interface" {
when "oc-if:type = 'ift:ethernetCsmacd'" {

But when we compile using confdc compiler it throws error saying type is not found in openconfig-interfaces.yang.
However when i change it to :- 
augment "/oc-if:interfaces/oc-if:interface" {
when "oc-if:config/oc-if:type = 'ift:ethernetCsmacd'" {

Now it compiles fine i.e., when  i specify the container in which type is present.

Issue 2 :-all the must expression present in openconfig-terminal-device.ynag are failing.Below is the error:- 
g: The 'must' expression will fail: the node 'LOGICAL_CHANNEL' from module 'openconfig-terminal-device' (in node 'logical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:453: warning: The 'must' expression will fail: the node 'assignment-type' from module 'openconfig-terminal-device' (in node 'logical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:453: warning: The 'must' expression will fail: the node 'LOGICAL_CHANNEL' from module 'openconfig-terminal-device' (in node 'logical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:467: warning: The 'must' expression will fail: the node 'assignment-type' from module 'openconfig-terminal-device' (in node 'optical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:467: warning: The 'must' expression will fail: the node 'OPTICAL_CHANNEL' from module 'openconfig-terminal-device' (in node 'optical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:467: warning: The 'must' expression will fail: the node 'assignment-type' from module 'openconfig-terminal-device' (in node 'optical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:467: warning: The 'must' expression will fail: the node 'OPTICAL_CHANNEL' from module 'openconfig-terminal-device' (in node 'optical-channel' from 'openconfig-terminal-device') is not found
openconfig-terminal-device.yang:820: warning: The 'must' expression will fail: the node 'operational-modes' from module 'openconfig-terminal-device' (in node 'components' from 'openconfig-platform') is not found
openconfig-terminal-device.yang:820: warning: The 'must' expression will fail: the node 'operational-modes' from module 'openconfig-terminal-device' (in node 'components' from 'openconfig-platform') is not found
openconfig-terminal-device.yang:820: warning: The 'must' expression will fail: the node 'operational-modes' from module 'openconfig-terminal-device' (in node 'components' from 'openconfig-platform') is not found
openconfig-terminal-device.yang:820: warning: The 'must' expression will fail: the node 'operational-modes' from module 'openconfig-terminal-device' (in node 'components' from 'openconfig-platform') is not found

Thanks,
Vivek Prasad

**Comment by fnchooft** [comment]
Hi Vivek,
Did you ever get any feedback on this?
Kind regards,
Fabian

**Comment by vprasad** [comment]
> Hi Vivek,
> Did you ever get any feedback on this?
> Kind regards,
> Fabian

Hi Fabian,
I never Got any response.
Thanks,
