### ISSUE TITLE
Is there any Openconfig based Access Control Model?

### ISSUE THREAD

**Issue by gsindigi** [openconfig/public#342]
Do we have any model defined towards access control model defining means to restrict/allow access to a defined set of users to config/exec operations and data tree subsets ?   Something specific to a RBAC model or similar.   I see that there's a role defined in [openconfig-aaa.yang](https://github.com/openconfig/public/blob/facd687c2e9029b9424b72af60852f720d63a697/release/models/system/openconfig-aaa.yang) module which is a union of string & an id-ref to system_defined_roles.  But, I could not find any module addressing access-control.  

```yang
    leaf role {
      type union {
        type string;
        type identityref {
          base oc-aaa-types:SYSTEM_DEFINED_ROLES;
        }
      }
      description
        "Role assigned to the user.  The role may be supplied
        as a string or a role defined by the SYSTEM_DEFINED_ROLES
        identity.";
    }

....

identity SYSTEM_DEFINED_ROLES {
…   
identity SYSTEM_ROLE_ADMIN {
  base SYSTEM_DEFINED_ROLES;
...

```
How does one models non-admin roles ? 

Also, I see there is this [RFC8341](https://tools.ietf.org/html/rfc8341) defining a "Network Configuration Access Control Model".  Is there anything similar for Openconfig modules as well?  

Thanks.

**Comment by chrisy** [comment]
As far as I know, nobody in the OpenConfig community has any plans at the moment to build out a more complete access model. There is some consensus that authorization controls from a system such as TACACS is generally a better approach. My own opinion is that modeling these controls in a vendor agnostic way (that is, could be mapped to and from current vendor configurations) is quite a difficult task given the variety of approaches.

For our (my employers') part, in the few cases where we have needed more AAA configuration on the device, we've built out some basic local augments to the model that mirror our use of vendor functionality (eg, Cisco user & task groups) that our automation platform recognizes and transforms accordingly. 

Building out something similar to RFC8341 for just the OpenConfig namespaces is not beyond the realm of possibility, though again, nobody in the community has suggested they intend to work on this; protecting just the OpenConfig part of the tree does not afford much protection when notable vendors simply translate it to their own syntax on the device.

**Comment by einarnn** [comment]
@chrisy, the NACM model in RFC 8341 is model-agnostic, so can be applied to openconfig models as well as vendor models. Even in a scenario when a vendor maps from openconfig to a native model, it can still work.

Is there any particular reason in your mind why the NACM model is inappropriate for openconfig models?

**Comment by chrisy** [comment]
@einarnn  No reason, lack of familiarity leading to not making assumptions of suitability. Did not mean that to read that I actively believed it unsuitable!

**Comment by dplore** [comment]
Note GNSI and pathz which introduces fine grained (per path) access control  https://github.com/openconfig/gnsi/tree/main/pathz
