### ISSUE TITLE
network-instance: configure L2-L3 stitching ( terminate VLL or VPLS to VRF service ) 

### ISSUE THREAD

**Issue by crcampos612** [openconfig/public#349]
Hi, I trying to model a configuration for interconnecting Layer 2 VPNs with Layer 3 VPNs using network-instance module. From CLI perspective, vendors treat this issue under different approaches. Either using "intermediate" logical interfaces like Juniper ( logical tunnel interface ) or, in the case of Nokia, through the concept of "spoke termination". In the end, both of them allow to "hairpin" a L2 and a L3 service in the same device. 
However, in order to translate to openconfig model, it doesn't look clear how to do it. Theoretically, steps would be, first, creating a network-instance type=L2P2P and then another network-instance type=L3VRF, but how to bind them to stitch both services ? If you try to put in "/network-instances/network-instance/interfaces/interface/config/interface" a reference to the VLL or PW termination previously defined, as usually you would do with a physical interface, what name or reference you should use ?   Finally, I see another network-instance type=L2L3, but I don't understand if it's applicable here an how to.
Many Thanks in advance!

**Comment by aashaikh** [comment]
I'm not sure if we have an example that exactly covers this case, but there is a [doc](https://github.com/openconfig/public/blob/master/doc/network_instance_examples.md) explaining a few different scenarios that tie together interfaces and L2/L3 network instances.

**Comment by luciaob** [comment]
Hi,

Aligned with @crcampos612 question, in the case we have the following PE-CE scenario: 
![image](https://user-images.githubusercontent.com/60645253/81661821-f5bd6480-943c-11ea-9f74-eeab964743c4.png)

How could traffic comming from the VLL be stitched7linked into the L3VPN?

I have reviewd the doc that @aashaikh referred, but I cannot see how this stitching could be done wth openconfig-network-instance model currently available.
