### ISSUE TITLE
Missing items in ETHERNET_PMD_TYPE in openconfig-transport-types.yang

### ISSUE THREAD

**Issue by arpp** [openconfig/public#35]
Hi,
Looking at the ETHERNET_PMD_TYPE in openconfig-transport-types we are missing few of the ethernet compliance codes:
- ETH_40GBASE_CSR4
- ETH_40GBASE_SR_BD
- ETH_40G_AOC

Any reason for not having these codes and what should be the expected output of the field oc-transceiver:ethernet-compliance-code for such transceivers.

**Comment by aashaikh** [comment]
We're in the process of adding a few missing PMD types -- we'll look at these as well.   thanks.
