### ISSUE TITLE
Question : Are there any released packages of openconfig models

### ISSUE THREAD

**Issue by rkosegi** [openconfig/public#350]
Does OpenConfig release/package yang modules in form of pypi/deb/rpm/.. ?

**Comment by robshakir** [comment]
No - today we don't package the modules into any kind of binary release. We'd be happy to discuss the use case for doing so, and review and accept contributions for this if it's something useful to the community.

Thanks,
r.

**Comment by rkosegi** [comment]
Closing as this was just a question
