### ISSUE TITLE
openconfig-lldp rw property of chassi-id

### ISSUE THREAD

**Issue by luciaob** [openconfig/public#351]
Hi,

I am doing some test on real devices regarding openconfig-lldp module. Vendors say that the following three parameters are read-only and are not modificable:
- Chassis-id
- System-description
- Chassis-id-type

What is the aim of having those params as RW instead of RO in openconfig-lldp.yang module?

**Comment by exa-arrcus** [comment]
The fact they are not modifiable on some implementations is a design decision from the implementor.  The model allows for implementors to allow for configuration/override of these nodes which is perfectly acceptable.  For instance in our implementation (ArcOS), we allow for a user-defined system-description.

For those that do not support writing to these nodes, the `config` node can be deviated

**Comment by luciaob** [comment]
Ok, understood. Thanks for the explanation.
