### ISSUE TITLE
Can’t show correctly the tree and attributes (openconfig-network-instance) Prefix collision "inet" 

### ISSUE THREAD

**Issue by danielhbar** [openconfig/public#352]
Hello!

I had been some problems compiling in Yang-Suite or Pyang the modules and submodules related with Network Instance (openconfig-network-instance), from Yang-Suite 

These are some errors that generate from Yang-Suite when this perform validation and analyze the compile of Openconfig modules and submodules:

_**"
openconfig-network-instance @ 2017-12-13 
    • Prefix collision: This module or its dependencies import both "ietf-inet-types" and "openconfig-inet-types" under the same prefix "inet", but each prefix MUST uniquely identify a single module. One possible cause is using the wrong revision(s) of this module's dependencies.
Is possible that there are a reuse of libraries that import from submodules (openconfig-inet-types and ietf-inet-types) with the prefix “inet”.
"**_
_For Example:
"
submodule openconfig-isis-lsp {

  belongs-to openconfig-isis {
    prefix oc-isis;
  }
  import openconfig-extensions { prefix "oc-ext"; }
  **import openconfig-inet-types { prefix "inet"; }**
  import openconfig-isis-types { prefix "oc-isis-types"; }
  import openconfig-isis-lsdb-types { prefix "oc-isis-lsdb-types"; }
  import openconfig-types { prefix "oc-types"; }
  import openconfig-mpls-types { prefix "oc-mpls-types"; }

  // namespace
  namespace "http://openconfig.net/yang/openconfig-isis";

submodule openconfig-isis {

  prefix "oc-isis";

  // import some basic types
  **import ietf-inet-types { prefix "inet"; }**
  import ietf-yang-types { prefix "yang"; }
  import openconfig-types { prefix "oc-types"; }
  import openconfig-isis-types { prefix "oc-isis-types"; }
  import openconfig-routing-policy { prefix "oc-rpol"; }
  import openconfig-extensions { prefix "oc-ext"; }
  import openconfig-interfaces { prefix "oc-if"; }
  import openconfig-segment-routing { prefix "oc-sr"; }_

Is probably that those errors are the cause of doesn’t show correctly in Yang-Suite the attributes how look the in the submodules.

When I try to set on oc-types module the type of address family only show the Identity (L2-ETHERNET) and is missing (ipv4, ipv6 and MPLS).

**_Extract of module openconfig-oc-types:_**

  identity ADDRESS_FAMILY {
    description
      "A base identity for all address families";
  }

  **identity IPV4 {
    base ADDRESS_FAMILY;**
    description
      "The IPv4 address family";
  }

  **identity IPV6 {
    base ADDRESS_FAMILY;**
    description
      "The IPv6 address family";
  }

  **identity MPLS {
    base ADDRESS_FAMILY;**
    description
      "The MPLS address family";
  }

  identity L2_ETHERNET {
    base ADDRESS_FAMILY;
    description
      "The 802.3 Ethernet address family";
  }

**Comment by aashaikh** [comment]
We've had several related reports having to do with prefixes -- the thing to remember is that prefixes in import statements have local scope, and can be different / overlapping / etc. across files even when importing the same module.

I can't reproduce this error with pyang 2.x (and several other tools) -- I'm assuming you're only seeing this with yang-suite?  (pointer to yang-suite please?).   It seems to have a different interpretation of the YANG spec than pyang.  In both YANG 1.0 and 1.1, the spec says:
```
When a definition in an external module is referenced, a locally
defined prefix MUST be used, followed by ":", and then the external
 identifier.
```
Locally defined here presumably means the file (i.e., submodule or module) so I don't think this should be an error.  

We've generally been trying to make prefixes consistent where there are differences as a convenience, so will likely address this one as well.  But suggest you also follow up with yang-suite maintainers.

**Comment by saumya0033** [comment]
Uploaded the whole set of OpenConfig models from OpenConfig/Github portal and created a repository in the Cisco Yang Suite tool.
But while creating the Yang set, facing this same kind of error..
Error- prefix collision: this module or its dependencies import both "ietf-inet-types" and "openconfig-inet-types" under the same prefix "inet",

This error is appearing for so many modules like..
ietf-inet-types
openconfig-aft-network-instance
openconfig-network-instance
openconfig-bfd
openconfig-igmp
openconfig-isis
openconfig-mpls

What might be the reason and remedy?
