### ISSUE TITLE
VLAN representation using openconfig models.

### ISSUE THREAD

**Issue by prvattem** [openconfig/public#354]
Hi

What is the right way to represent a VLAN
1) via /openconfig-networkinstances:network-instances/networking-instance[Vlan100] of type L2L3
 (or)
2) via /openconfig-interfaces:interfaces/interface[Vlan100] of type IF_ROUTED_VLAN

If you could add an use-case here it will be helpful 
https://github.com/openconfig/public/blob/master/doc/network_instance_examples.md

Thanks

**Comment by chrisy** [comment]
Hello!

The first question you must answer: What is a VLAN?

Is it simply a subinterface that is associated with specific VLAN tags? (aka routers with trunked ports)

Is is a layer 2 virtual switch with attached ports that are associated with specific VLAN tags? (how routers do certain L2 services, or linux-bridge)

Is it a layer 2 construct that is intrinsically tied to a specific VLAN identifier? (aka how "switches" do it)

Since you mention L2L3 and ROUTED_VLAN, are you instead looking for a routed interface that is attached to a L2 virtual switch (BVI/IRB)?

The context will help with answering your question.

**Comment by prvattem** [comment]
We are looking at a Layer 2 Broadcast domain, tied to a VLAN Identifier.

**Comment by prvattem** [comment]
We have representations for each of the constructs you mentioned:
-- "Is it simply a subinterface that is associated with specific VLAN tags? (aka routers with trunked ports)"

Ethernet1.0 -- vlan 100
/openconfig-interfaces:interfaces/interface[Ethernet1]/Subinterfaces/subinterface[0]/oc-vlan:vlan/config/vlan-id=100

Ethernet1.0 -- vlan 200
/openconfig-interfaces:interfaces/interface[Ethernet1]/Subinterfaces/subinterface[1]/oc-vlan:vlan/config/vlan-id=200

"Is is a layer 2 virtual switch with attached ports that are associated with specific VLAN tags? (how routers do certain L2 services, or linux-bridge)"

/openconfig-networkinstances:network-instances/networking-instance[Bridge100]/config/type=L2VSI
and populate 
/openconfig-networkinstances:network-instances/networking-instance[Bridge100]/Interfaces or
/openconfig-networkinstances:network-instances/networking-instance[Bridge100]/vlans


To represent Vlan which is aLayer 2 Broadcast domain, tied to a VLAN Identifier, the modelling is not clear, as to how it should be done

/openconfig-networkinstances:network-instances/networking-instance[Vlan100] of type L2L3
(or)
/openconfig-interfaces:interfaces/interface[Vlan100] of type IF_ROUTED_VLAN

**Comment by chrisy** [comment]
Sorry for the delay.

Coincidentally there's a similar discussion on the mailing list.

I believe you are mixing approaches. If you want a dumb-switch style vlan with an IP address, then you may want an /interfaces/subinterface/routed-vlan interface and a /network-instance/vlan/ for the L2 part. This models the switch concept where VLANs are their own first-class-citizen, but they're independent of the rest of OC in many ways which follows more of a router-like approach, and that is what you have above.

I pasted into a response on the ML this excerpt from an internal wiki I wrote some time ago. This is untested, though, so YMMV:

```
{
    "openconfig-interfaces:interfaces": {
        "interface": [
            {
                "name": "vlan100",
                "config": {
                    "name": "vlan100",
                    "iftype": "openconfig-if-types:IF_ROUTED_VLAN"
                },
                "openconfig-vlan:routed-vlan": {
                    "config": {
                        "vlan": 100
                    },
                    "openconfig-if-ip:ipv4": {
                        "addresses": {
                            "address": [
                                {
                                    "ip": "1.2.3.4",
                                    "config": {
                                        "ip": "1.2.3.4",
                                        "prefix-length": 26
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]
    },
    "openconfig-network-instance:network-instances": {
        "network-instance": [
            {
                "name": "DEFAULT",
                "config": {
                    "name": "DEFAULT",
                    "type": "openconfig-network-instance-types:DEFAULT_INSTANCE"
                },
                "vlans": {
                    "vlan": [
                        {
                            "vlan-id": 100,
                            "config": {
                                "vlan-id": 100,
                                "name": "VLAN-FOO"
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```

But in reality, do you need a "vlan" object? Are you targeting a device that needs it?

**Comment by prvattem** [comment]
Thanks for your response. Sorry for responding very late on this.

There are few comments here:
1. network-instances/network-instance[DEFAULT]/fdb -  the "DEFAULT_INSTANCE", can represent the FDB table, entries coming for various VLANS.
2. network-instances/network-instance[Vlan100]/fdb -  the "L2L3" instance, can represent the FDB table, entries belonging to only Vlan100.
3. interfaces/interface[Vlan100] - provides a way to realize all the L3 properties of a Vlan(SVI).
3. Now, we have implemented a model where a VLAN is stretched onto a VXLAN network. Here the VLAN will be associated to a VNI. 
	3.a. This creates a need for network-instance of the "L2L3".
	3.b. This instance can be extended to capture various features on Vlan. Example: ARP/ND suppression

4. So we are using network-instances/network-instance of type L2L3 to represent a Vlan and extending it capture various other properties.

Please provide your comments on this approach.
