### ISSUE TITLE
Seeking clarification on grouping nomenclature in openconfig style guide

### ISSUE THREAD

**Issue by sayedsaquibbrcm** [openconfig/public#360]
Style guide mentions guidelines about naming groupings when defining data models. The purpose is maximum re-usability and readability. Style guides suggests suffixes for grouping naming ie; it should be [top|config|state]

top|config|state are for very specific purposes. the models in the master branch contains grouping namings ending with *key-refs, *common, *list which are also meaningful and re-usable.

Does the style-guide *strictly* advises that grouping names cannot be suffixed with anything other than [top|config|state]?

Are grouping names ending with *key-refs, *common, *list etc acceptable?

Excerpt from style guide for reference:
`
Grouping names should make it easy to quickly understand the nature of the data within. A suggested convention is xxx-yyy[-config|state|top], where xxx is the top-level module name (without the openconfig prefix), yyy is a string which indicates the contents of the groupings.
`

**Comment by robshakir** [comment]
No - this is not a strict requirement for all groupings. Generally, we
would expect that leaf-only groupings for config/state are suffixed with
-(config|state) and the top most structural grouping for a module is
suffixed with -top. Other groupings generally do not follow a fixed format
- you may see -top or -structural used in the models, or even no such
suffix.

r.

**Comment by sayedsaquibbrcm** [comment]
Thank you, for the answer
