### ISSUE TITLE
openconfig-mpls-te.yang,  container p2p-primary-path is same name as its list.

### ISSUE THREAD

**Issue by breathefreshair** [openconfig/public#365]
https://github.com/openconfig/public/blob/master/release/models/mpls/openconfig-mpls-te.yang

  grouping p2p-primary-paths-top {
    description
      "Top level grouping for p2p primary paths";

    container p2p-primary-path {    ===============> can use  p2p-primary-paths ? it seems reasonable.
      description
        "Primary paths associated with the LSP";

      list **p2p-primary-path** {
        key "name";
        description
         "List of p2p primary paths for a tunnel";

**Comment by chrisy** [comment]
Yes, that should probably have been pluralized when it was first developed; but it would now be a breaking change for minor value so I wouldn't recommend changing it.

**Comment by breathefreshair** [comment]
> Yes, that should probably have been pluralized when it was first developed; but it would now be a breaking change for minor value so I wouldn't recommend changing it.

Thanks, I got it.
