### ISSUE TITLE
require-instance in openconfig-mpls-te and openconfig-telemetry

### ISSUE THREAD

**Issue by abhikeshav** [openconfig/public#37]
Per #9, looks like the `require-instance` statements were removed for `openconfig-bgp` modules, but there are [couple of other places](https://github.com/openconfig/public/search?q=require-instance&type=Code&utf8=%E2%9C%93) where this still shows up. Any plans of removing these?

**Comment by andaru** [comment]
Bounce. 

This error (`require-instance` invalid for a `leafref` in YANG 1.0) still exists in the grouping `telemetry-sensor-profile` within `openconfig-telemetry.yang`, however it looks as though the grouping `telemetry-sensor-profile` is not used by any module, only the `telemetry-sensor-profile-config` grouping, which has no such error.

Is the plan to move this to a YANG 1.1 module.  In an environment which requires modules to syntactically validate for operation to proceed, is moving `openconfig-telemetry.yang` to be YANG 1.1 syntax compliant what you'd recommend?

```
$ git grep "telemetry-sensor-profile"
release/models/telemetry/openconfig-telemetry.yang:                uses telemetry-sensor-profile-config;
release/models/telemetry/openconfig-telemetry.yang:                uses telemetry-sensor-profile-config;
release/models/telemetry/openconfig-telemetry.yang:  grouping telemetry-sensor-profile-config {
release/models/telemetry/openconfig-telemetry.yang:  grouping telemetry-sensor-profile {
release/models/telemetry/openconfig-telemetry.yang:    list telemetry-sensor-profile {
```

**Comment by robshakir** [comment]
Hi Andrew,

This is an oversight, this should have been fixed previously. The plan is to remain at YANG 1.0. We noted there was this unused grouping before too - I'll start the process to release a fixed version.

Thanks for pointing it out.

Cheers,
r.

**Comment by andaru** [comment]
No problem, thanks for the reply.

**Comment by aashaikh** [comment]
This should be fixed in the latest push -- thanks again.
