### ISSUE TITLE
state-only addresses on interfaces

### ISSUE THREAD

**Issue by rski** [openconfig/public#371]
Here is the snippet from  openconfig-if-ip.yang:

```
  grouping ipv6-top {
    description
      "Top-level configuration and state for IPv6 interfaces";

    container ipv6 {
      description
       "Parameters for the IPv6 address family.";

      container addresses {
        description
          "Enclosing container for address list";

        list address {
          key "ip";
          description
           "The list of configured IPv6 addresses on the interface.";

          leaf ip {
            type leafref {
              path "../config/ip";
            }
            description "References the configured IP address";
          }

          container config {
            description
              "Configuration data for each IPv6 address on
              the interface";

            uses ipv6-address-config;

          }

          container state {

            config false;
            description
              "State data for each IPv6 address on the
              interface";

            uses ipv6-address-config;
            uses ipv6-address-state;
          }
        }
      }
...
```

This assumes that an interface's IP is configurable. This is not always the case, such as with link local IPv6 addresses on Arista's EOS. This means that link-local addresses cannot be streamed. There are possible ways to work around this, e.g. by setting the state as config too, and disallow editing the config, but that goes against the current.

I'm raising this issue because I think the intferface models should take state-only addresses into account, giving some way to express them. Maybe there is one already and I've missed it after looking around for a bit.

**Comment by colinmcintosh** [comment]
Hi @rski, it looks like the config portion of the modeled is meant to contain the auto-configured portion of the system's configuration in addition to the manually configured portions. This is similar to how DHCP addresses would appear in the config portion of the tree even though those addresses are not configured explicitly.

This can be marked in the tree with the IP origin leaf: https://github.com/openconfig/public/blob/5897507ecdb54453d4457e7dbb0a3d4b7ead4314/release/models/interfaces/openconfig-if-ip.yang#L513-L521

It looks like there is also a IP origin enum for link local addresses called `LINK_LAYER`: https://github.com/openconfig/public/blob/5897507ecdb54453d4457e7dbb0a3d4b7ead4314/release/models/interfaces/openconfig-if-ip.yang#L117-L122

@aashaikh can add additional details about this if I missed anything.

**Comment by aashaikh** [comment]
One clarification is that for system-assigned IP addressed like link-local addresses, we would expect to see the address only in the state container as applied configuration, i.e.:
`/interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/state/ip`

Since this address is not configured by an external NMS, the config container should not contain the address, since it is not part of intended configuration.  As @colinmcintosh mentioned, the `/interfaces/interface/subinterfaces/subinterface/ipv6/addresses/address/state/origin` leaf would be set to LINK_LAYER .

**Comment by rski** [comment]
right, that's what I would think too, but doesn't that violate the leafref? `address` is a list whose key is a leafref pointing to the config container
