### ISSUE TITLE
[BGP] Support of address family RT-Constraint (AFI/SAFI : 1/132)

### ISSUE THREAD

**Issue by Tristou27** [openconfig/public#372]
Hello all,

Would it be possible to add to BGP models the support of this address family ? 
Route Target Constraint is standardized since 2006 under RFC 4684 and seems not to be present in the last BGP models.

Thanks,
Regards,
Tristan

**Comment by robshakir** [comment]
Absolutely, this can be supported. If you'd like to open a PR then this will expedite the addition.

Thanks,
r.

**Comment by Tristou27** [comment]
Hello 
Just issued the pull request, #384 .

Please let me know if it's OK and ready to be merged.

Thanks.
Tristan
