### ISSUE TITLE
Missing model to protection scenarios of logical channels (1+1, 1:1, 1:N)

### ISSUE THREAD

**Issue by alfredogonzalezmuniz** [openconfig/public#377]
There is no way to describe scenarios of protection 1+1 or 1:1 within the OT when using a electrical matrix.
How can we model a structure of 1+1 or 1:N logical channels protecting a single client port?
We need a model to define this scenario to allow the definition of the working and the protection path and a switch control entity to manage the protection.

**Comment by ejbrever** [comment]
I don't believe there is a way to do this today. Just to brainstorm a little on how we might do this, I am wondering if it might make sense to have a new optical protection model. Essentially a list of protection-groups. Something along the lines of:

protection-groups: {
  [
    {
      config {
        name: "protectionName1",
        protected-logical-channels: [
          "logicalCh1",
          "logicalCh2"
        ],
        interesting-config...
      },
      state {
        interesting-state...
      }
    }
  ]
}

We could potentially expand a logical channel to describe the protection, but I'm wondering if there might be a bit of config/state that will be related to the protection. If we have a dedicated model this will be a bit easier to understand and avoid complicating the logical channel model, but I not convinced on that point either :)

Curious to get others thoughts as well.
