### ISSUE TITLE
port range pattern are not correct

### ISSUE THREAD

**Issue by jmenok** [openconfig/public#378]
pattern seems to be wrong, e.g. a port range of 64998..64999 cannot be specified  

https://github.com/openconfig/public/blob/7ff359490559c11cbe63bcce27915dfdb5958ffa/release/models/acl/openconfig-packet-match-types.yang#L267

**Comment by aashaikh** [comment]
Thanks for catching this -- we will look at developing a fix (please feel free to contribute a fix as well).

**Comment by dutta-partha** [comment]
Please try as below :

`pattern '^(6553[0-5]|655[0-2][0-9]|65[0-4][0-9]{2}|' + 
        '6[0-4][0-9]{3}|[1-5][0-9]{4}|[0-9]{1,4})\.\.' + 
        '(6553[0-5]|655[0-2][0-9]|65[0-4][0-9]{2}|' +
		'6[0-4][0-9]{3}|[1-5][0-9]{4}|[0-9]{1,4})$' `

**Comment by aashaikh** [comment]
Thanks @dutta-partha for the suggested fix.

This was also mentioned in #345 .  Requesting @wenovus to follow up along with other regex updates (thanks Wen).

**Comment by allyn-wade** [comment]
I believe an error was made when adopting this regex. In the current openconfig-packet-match-types.yang, we have:

  [0-5][0-9]{4}

instead of the proposed:

  [1-5][0-9]{4}
