### ISSUE TITLE
NTP: root-delay, root-dispersion, offset should use microsec unit

### ISSUE THREAD

**Issue by jmenok** [openconfig/public#379]
The spec defines root-delay and root-disperson as 2^16-bit integers for seconds and fractional seconds, respectively.  This gives a precision of ~15 us (2^-16).

Thus it should be reconsidered to define the unit in microseconds instead of milliseconds.

References:
https://github.com/openconfig/public/blob/7ff359490559c11cbe63bcce27915dfdb5958ffa/release/models/system/openconfig-system.yang#L572
https://github.com/openconfig/public/blob/7ff359490559c11cbe63bcce27915dfdb5958ffa/release/models/system/openconfig-system.yang#L589
https://github.com/openconfig/public/blob/7ff359490559c11cbe63bcce27915dfdb5958ffa/release/models/system/openconfig-system.yang#L600

**Comment by nkitchen** [comment]
The problem with using microsecond units is the range.

In the packet format ("NTP short"), the maximum root delay or root dispersion is 2<sup>16</sup> seconds, which is about 18 hours.

The maximum value representable with uint32 milliseconds is 2<sup>32</sup> * 0.001 seconds, which is about 1193 hours. No problem there.

But the max representable value with uint32 microseconds is about 1.193 hour. That's an order of magnitude too low.
