### ISSUE TITLE
NTP server config should have reference to a NTP-auth-key

### ISSUE THREAD

**Issue by jmenok** [openconfig/public#380]
Today, OpenConfig defined a list of NTP servers and a list of NTP authentication keys assuming that each server might any of the keys. 
Typically a NTP server can be accessed only with one authentication key.
So from modelling point of view it would be better to have an optional reference in NTP server config specifying the NTP auth key, which should be used for this dedicated NTP server. 

Reference:
https://github.com/openconfig/public/blob/7ff359490559c11cbe63bcce27915dfdb5958ffa/release/models/system/openconfig-system.yang#L480

**Comment by Verma-Anukul** [comment]
Any PR for this request
