### ISSUE TITLE
openconfig-if-ip.yang : introduction of per family per subinterface multicast packet and octet counters

### ISSUE THREAD

**Issue by dshokarev** [openconfig/public#381]
Dear OC Community,

I represent a routing systems vendor (Juniper Networks) and would like to propose an addition of the following leaves to the IPv4 / IPv6 containers in the openconfig-if-ip.yang model for your review:

**IPv4**
Path, Type, Description
interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/in-mcast-pkts, counter64, "number of IPv4 multicast packets received on a subinterface"
interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/in-mcast-octets, counter64,  "number of octets in IPv4 multicast packets received on a subinterface"
interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/out-mcast-pkts, counter64, "number of IPv4 multicast packets sent to a subinterface"
interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/out-mcast-octets, counter64, "number of octets in IPv4 multicast packets sent to a subinterface"

**IPv6**
Path, Type, Description
interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/in-mcast-pkts, counter64, "number of IPv4 multicast packets received on a subinterface"
interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/in-mcast-octets, counter64,  "number of octets in IPv4 multicast packets received on a subinterface"
interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/out-mcast-pkts, counter64, "number of IPv4 multicast packets sent to a subinterface"
interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/out-mcast-octets, counter64, "number of octets in IPv4 multicast packets sent to a subinterface"

Would you please review?

Thanks,
Dmitry.

**Comment by aashaikh** [comment]
Thanks for the suggestion -- these seem reasonable to add.  Will you create a PR for these?
