### ISSUE TITLE
a copy of the ALv2 license must be shippped with the openconfig models

### ISSUE THREAD

**Issue by guillaumelambert** [openconfig/public#382]
Currently, no copy of the ALv2 license used by openconfig models is present in the OpenROADM repo.
And in the section 4 of the ALv2 license, there is a redistribution clause stating that a copy of the ALv2 license must be shipped with them.

https://github.com/openconfig/public/blob/master/LICENSE
Quoting lines 89-95:
"4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and
"
NB: There is no contamination problem by using the openconfig models Apache license version 2 inside OpenROADM.

**Comment by chrisy** [comment]
Did you intend to open this issue against OpenConfig? If true, then OpenROADM would need to take the corrective action, not OpenConfig, surely?

**Comment by guillaumelambert** [comment]
Hi chrisy
Right, I put it in the wrong place...
