### ISSUE TITLE
QSFP_DD missing in TRANSCEIVER_FORM_FACTOR_TYPE for ZR use-case

### ISSUE THREAD

**Issue by prmanna** [openconfig/public#388]
Hi,

Request to add QSFP_DD base TRANSCEIVER_FORM_FACTOR_TYPE in openconfig-transport-types.yang.

Regards,
Prasenjit

**Comment by prmanna** [comment]
Hi,

any update on this?

Regards,
Prasenjit

**Comment by oscargdd** [comment]
Hi @prmanna 
Check the latest version, I recently updated the model to include QSFP28_DD, complementing the QSFP56_DD that was added recently. 

With this we can close the issue
