### ISSUE TITLE
What is the expected way to configure a port-based VPWS service?

### ISSUE THREAD

**Issue by kreeger-arrcus** [openconfig/public#389]
Does someone understand how I would use the openconfig model to configure a physical interface for a port-based L2 service, such as VPWS, in which all frames should be passed through, regardless of whether or not they have a VLAN tag?

First, I thought that using a match on VLAN range 0-4094 would be the answer, however the vlan-id type only allows a range of 1-4094. This does not allow for untagged packets on a subinterface.

Should a simpler mode be added to simply say "port-based" or similar to indicate any frame is passed through, or does the vlan-id range need to be loosened to allow 0 as a value for untagged frames?

Loosening the range to allow 0 allows matching untagged packets and then perhaps pushing on a tag if desired...

**Comment by chrisy** [comment]
Do you have a vendor equivalent? In my head this should be as simple as just specifying the parent port in the endpoint, but I suspect vendor configurations do need some active encouragement to also include tagged frames.

**Comment by kreeger-arrcus** [comment]
@chrisy This Cisco documentation shows how they decide to match packets for subinterfaces.
https://www.cisco.com/c/en/us/support/docs/routers/asr-9000-series-aggregation-services-routers/116453-technote-ios-xr-l2vpn-00.html#anc4
The use the keywords "encapsulation untagged" to match only untagged packets for a subinterface, or the keywords "encapsulation default" to match all packets to a subinterface.
