### ISSUE TITLE
Duplicated revisions 

### ISSUE THREAD

**Issue by missaesasaya** [openconfig/public#390]
I am using OpenYuma netconf server and when parsing OpenConfig yang files to generate code it complains about duplicated entries in some files:

```
Error: revision with same date on line 48
openconfig-bgp-types.yang:54.3: error(224): duplicate entry
```

I found this issue in at least 4 files, but I didn't check all:
- bgp/openconfig-bgp-types.yang
- isis/openconfig-isis-types.yang
- isis/openconfig-isis.yang
- types/openconfig-inet-types.yang

**Comment by aashaikh** [comment]
Having revision statements with the same date is not prohibited by the YANG spec (neither RFC 6020 nor 7950).  None of the CI tools we use to validate OpenConfig modules flag this as an error.  I'm not sure why OpenYuma considers it an error.

**Comment by missaesasaya** [comment]
It may not be prohibited but the module+revision is what identifies the
module in netconf capabilities. Having duplicated revision statements means
the same capability statement can represent two different module revisions.

Em sex, 20 de nov de 2020 04:58, Anees Shaikh <notifications@github.com>
escreveu:

**Comment by aashaikh** [comment]
I see -- yes, this looks like a limitation in how NETCONF currently identifies modules.  We can also have a look at the modules to see if any of the duplicate revision dates are incorrect.
