### ISSUE TITLE
Leaking routes across network instances

### ISSUE THREAD

**Issue by saramach** [openconfig/public#392]
Hello folks-
We are looking for the model scheme to configure route leaking. (Like service routes from a service VRF to tenant VRF etc).
I could see the "inter-instance-policies" container, which provides import and export policies. 
And in the policy, the condition and action, the RT can be specified as an extended community.

But, vendors seem to provide the following construct:

Source VRF:
export <RT> policy
The  policy can be something like a route-map

Destination VRF:
import <RT>

This is tough to map with the "inter-instance-policies" as it is now. Any suggestions?

thanks
Satish.

**Comment by aashaikh** [comment]
I'm still not quite sure where the model is missing what is needed for this case.  Is the question about how to configure the routing policy that's used in the inter-instance-policies?

**Comment by saramach** [comment]
Hi @aashaikh -
With the inter-instance-policies, I'm trying to see how an RT based export and import can be configured.
For example: Something like:
Source VRF: route-export <RT> route-map <policy-definition>
Destination VRF: route-import <RT>

To achieve things like: https://www.arista.com/en/um-eos/eos-section-23-9-evpn-and-vcs-commands#ww1339585
This is something like:
```
OS10(config)# ip vrf default
OS10(conf-vrf)# ip route-export 0:0 route-map RouteMap_DHCPServer
OS10(conf-vrf)# exit
OS10(config)# ip vrf Yellow
OS10(conf-vrf)# ip route-import 0:0
OS10(conf-vrf)# exit
OS10(config)# ip vrf Green
OS10(conf-vrf)# ip route-import 0:0
OS10(conf-vrf)# exit
OS10(config)# ip vrf Red
OS10(conf-vrf)# ip route-import 0:0
OS10(conf-vrf)# exit
```

Thanks

**Comment by aashaikh** [comment]
We had some additional discussion on this for the EVPN use case in the last couple of weeks.  There was consensus to add more explicit (and simplified) modeling specifically for route-target import/exports between network-instances (i.e., VRFs).  For other types of policies, the existing inter-instance policy modeling should be used.  We will be updating the network-instance model with this soon.

**Comment by saramach** [comment]
Thanks @aashaikh

**Comment by missaesasaya** [comment]
> We had some additional discussion on this for the EVPN use case in the last couple of weeks. There was consensus to add more explicit (and simplified) modeling specifically for route-target import/exports between network-instances (i.e., VRFs). For other types of policies, the existing inter-instance policy modeling should be used. We will be updating the network-instance model with this soon.

Is there any preview of how this is going to be done? I am currently implementing a deviation to be able to configure route-targets using OpenConfig models and it would be nice to have a glimpse of the planned structure.

This is how we I am planning to implement it on my side:

module: openconfig-network-instance
  +--rw network-instances
     +--rw network-instance* [name]
        +--rw name                       -> ../config/name
        +--rw routes-targets
           +--rw route-target* [rt-rd-string]
              +--rw rt-rd-string      -> ../config/rt-rd-string
              +--rw config
              |  +--rw rt-rd-string   bgp_vrf_rt_t (string/pattern ".*:.*")
              |  +--rw direction      identity(IMPORT | EXPORT | BOTH)
              +--ro state
                 +--ro rt-rd-string   bgp_vrf_rt_t (string/pattern ".*:.*")
                 +--ro direction      identity(IMPORT | EXPORT | BOTH)
