### ISSUE TITLE
single and double tagging needs to be exclusive

### ISSUE THREAD

**Issue by arulprabhu81** [openconfig/public#395]
Hi,

In the openconfig-vlan module, single-tagged and double-tagged need to be exclusive. 

From file: openconfig-vlan.yang:

    container match {
    .
     container single-tagged {
      .
      container double-tagged {

Am using this under these under subinterface hierarchy:

    /interfaces/interface/subinterfaces/subinterface/oc-vlan:vlan/oc-vlan:match/oc-vlan:single-tagged
    /interfaces/interface/subinterfaces/subinterface/oc-vlan:vlan/oc-vlan:match/oc-vlan:double-tagged

In this case both need to be exclusive. We should have used 'choice' to make it exclusive. 
Want to understand if there are any requirements for both needs to be present under same subinterface or any other augmented level ?

I hope all other containers under oc-vlan:vlan/oc-vlan:match/ are also mutually exclusive as per my understanding. 
You may want all of them as choices.

Thanks,
Arul.

**Comment by chrisy** [comment]
Per the [style guide](https://www.openconfig.net/docs/style-guide/#choice), we avoid the `choice` keyword.

As for the exclusivity, the description for match includes the statements:

>  Typically only one of the subordinate containers should be specified. [...] Implementations are expected to return errors for combinations that they do not support, or provide deviations to the same effect.
