### ISSUE TITLE
Invalid Regex in openconfig-yang-types.yang

### ISSUE THREAD

**Issue by nshetty10** [openconfig/public#402]
The following data type in openconfig-yang-types.yang has a bug 

`typedef date-and-time {
    type string {
      pattern
        '^[0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}' +
        '(\.[0-9]+)?Z[+-][0-9]{2}:[0-9]{2}$';
    }`

The regex match Z[+-] should be changed to [Z+-]. As per RFC3339, it could be only one of them ( Z or + or -). The current match mandates Z along with with + or -. But according to the RFC, it can be only one of them. 

Link to RFC
https://tools.ietf.org/html/rfc3339

The confusion is because of time package in golang has wrong examples.

Same issue is discussed by other developers for another project.
https://github.com/moment/moment/issues/5045

**Comment by aashaikh** [comment]
Thanks for catching this -- we will publish a fix based on your suggestion.  We are also working on a simple mechanism to add tests for regexes that will hopefully make it easier for the community to add test cases going forward.

**Comment by missaesasaya** [comment]
This is the same issue raised in https://github.com/openconfig/public/issues/166. Do we have a planned date for this fix?

**Comment by wenovus** [comment]
Thanks again for bringing this up, https://github.com/openconfig/public/commit/225dac979c4f98d210d9104bd70e7d236feed1be is the fix.
