### ISSUE TITLE
support for configuring the route limit for the redistributed routes in the IGP(ISIS or OSPF)

### ISSUE THREAD

**Issue by wilsonroy** [openconfig/public#408]
Hello,

Wanted to know are their any plans to add the "redistribution-container" kind of config for the IGP protocols. I could see something done for the RIP. Please refer below link and its still in draft stage.
https://tools.ietf.org/html/draft-ietf-rtgwg-yang-rip-11

I'm working on configuring the route limit applicable for ISIS per instance and per level. route limit for only redistributed routes. This is to prevent redistributing the large number of routes into ISIS.  I'm exploring the table-connection and also looked into the "grouping l3ni-route-limit-structural". Wanted to know if there is better way to achieve this with the existing OC models. 

Thanks,
Wilson

**Comment by aashaikh** [comment]
The OpenConfig network instance model supports route limits on a per-instance basis by AFI-SAFI, not by the origin or target protocol.  To help better understand this, can you please point to some specific platforms that support this feature?

**Comment by s19nal** [comment]
@aashaikh I see support for this in Cisco (sorry my memory is terrible!) for opsf and isis:

router ospf process-id
redistribute protocol ...
redistribute maximum-prefix maximum [threshold ]

router isis [area-tag]
redistribute protocol ...
redistribute maximum-prefix maximum [percentage] [warning-only | withdraw]

@wilsonroy is this the sort of thing you are looking for?

**Comment by wilsonroy** [comment]
Thank you @aashaikh and @s19nal for the reply. 

@aashaikh yes, per instance route limit yang models already present. My use case is very much similar to what @s19nal pointed out in the above message. 

@s19nal you pointed out the right use case. Need suggestion on how to configure the "maximum-prefix", "percentage" etc for the redistributed routes for Ospf and ISIS. 

At present I don't see YANG models for this. correct me if am wrong! I can add this config as augment, but wanted to check if there is way to do it using existing yang config.
