### ISSUE TITLE
ODUFlex enum is missing in TRIBUTARY_PROTOCOL_TYPE

### ISSUE THREAD

**Issue by maljayac** [openconfig/public#410]
Hi Team,

Kindly requesting to add trib-protocol for representing ODUFlex protocol in TRIBUTARY_PROTOCOL_TYPE enum list in openconfig-transport-types.yang 

This is required for 400GE datapath support.

**Comment by aashaikh** [comment]
Thanks for noting this.   We are in the process of extending modeling to support 400G technologies, including extending the protocol enums, PMDs, and form factors.
