### ISSUE TITLE
Prefix collision - Cisco Yang Suit - "ietf-inet-types" and "openconfig-inet-types" clashing

### ISSUE THREAD

**Issue by saumya0033** [openconfig/public#412]
Uploaded the whole set of OpenConfig models from OpenConfig/Github portal and created a repository in the Cisco Yang Suite tool.
But while creating the Yang set, facing this same kind of error..
Error- prefix collision: this module or its dependencies import both "ietf-inet-types" and "openconfig-inet-types" under the same prefix "inet",

This error is appearing for so many modules like..
ietf-inet-types
openconfig-aft-network-instance
openconfig-network-instance
openconfig-bfd
openconfig-igmp
openconfig-isis
openconfig-mpls

What might be the reason and remedy?
** I have raised a query/concern with Cisco team.

**Comment by chrisy** [comment]
I suspect the bug in Yang Suite is it expects consistent prefix use across all modules loaded, a losing proposition. [YANG doesn't require this](https://tools.ietf.org/html/rfc6020#section-7.1.4), though I posit we should strive towards it inside our project.

Four modules use prefix `prefix inet` for `openconfig-inet-types` whereas everywhere else it's `oc-inet`. Those four modules do not also import `ietf-inet-types`, but where we do use it, in other modules, it does also use the prefix `inet`.

It's a common and flawed practice for tools to index globally on prefix.

**Comment by saumya0033** [comment]
Thanks Chrisy, It is still working, inspite those errors. But, yes, it should be resolved within OpenConfig project.
