### ISSUE TITLE
Request adding OC model for SNMP OID (1.3.6.1.2.1.55.1.1.0) ipv6Forwarding

### ISSUE THREAD

**Issue by Surakshah** [openconfig/public#414]
There is a requirement for the SNMP OID (1.3.6.1.2.1.55.1.1.0) ipv6Forwarding  to be exported using telemetry. 
 
 Following is the snmp oid =>
 https://apps.juniper.net/mib-explorer/search.jsp#object=ipv6Forwarding&product=Junos%20OS&release=20.4R1
 
There is no existing OC model for this.
Request adding OC model for the same.

**Comment by robshakir** [comment]
Please feel free to propose a pull request for this functionality as per the OpenConfig [contribution process](https://github.com/openconfig/public/blob/master/doc/external-contributions-guide.md). We are happy to find a shepherd for such requests, I don't see this being controversial.

Thanks,
r.

**Comment by oscargdd** [comment]
Hi @robshakir, @Surakshah, I can help to sheppered  the requirement. 

@Surakshah Send me an email (it is in my public profile). 

As far I understand, the OID ipv6Forwarding means that the entity which is being monitored has enabled or disabled the forwarding of ipv6 packets. Were do you suggest to place that information in the data model? I guess it could be at the network-instance level. 

In the use case you mention reading, but I guess you will require also being able to configure it, right?

In addition, the forwarding can also be activated per interface. Do you also require that?
