### ISSUE TITLE
Attribute/Leaf to Xpath mapping

### ISSUE THREAD

**Issue by saumya0033** [openconfig/public#415]
Hello there,
Is there a mapping existing or any tool where i can find/create the attribute/leaf Vs it's Xpath mapping?
I need this to validate the existing Openconfig support on different vendor devices.
Regards

**Comment by robshakir** [comment]
The [yangpath](https://github.com/openconfig/oc-pyang/blob/master/openconfig_pyang/plugins/yangpath.py) plugin for pyang (from the [oc-pyang repo](https://github.com/openconfig/oc-pyang) can be used to extract all schema paths for an input set of modules. It's used by downloading the repo and using it with pyang's pluginpath directive.

Thanks,
r.
