### ISSUE TITLE
Remove anchors in pattern statements of openconfig-yang-types.yang. 

### ISSUE THREAD

**Issue by imsajidkhan** [openconfig/public#416]
Hi,

Recently a fix was added to remove the anchor  from the pattern statements in openconfig-inet-types, dont we need this fix in openconfig-yang-types.yang too ? 
 * (M) release/models/types/openconfig-inet-types.yang  
     - Remove anchors in pattern statements to make them W3C compliant

thx,

**Comment by aashaikh** [comment]
We are making the changes on a per-module basis.  It requires moving the existing POSIX patterns to use the `posix-pattern` extension statement defined in `openconfig-extensions` and creating a W3C-compliant expression for the pattern statement.  If you'd like to work on this, please open a PR per the [contributions](https://github.com/openconfig/public/blob/master/doc/external-contributions-guide.md) process.
