### ISSUE TITLE
openconfig-network-instance: various issues with when statements

### ISSUE THREAD

**Issue by pmerlo74** [openconfig/public#42]
Hi,

Similar to reported issues in other models I've encountered both compile errors and data validation errors with openconfig-network-instance.

1. While compiling with confdc I hit several errors related to paths in when statements. Below is one example, there were at least 10 others that need to be addressed that I have not included to keep this note brief.

openconfig-network-instance.yang:100: error: the node 'type' from module 'openconfig-network-instance' (in node 'network-instances' from 'openconfig-network-instance') is not found

In this case I modified this line:
           when "../type = 'L2VSI' or ../type = 'L2P2P'" +
                 " or ../type = 'L2L3'" {

to this and the compilation succeeded:
            when "config/type = 'L2VSI' or config/type = 'L2P2P'" +
                 " or config/type = 'L2L3'" {

2. After fixing the compile issues I've run into problems where the when statements did not validate data properly. One failing example from the protocols container is below.

            uses oc-loc-rt:local-static-top {
              when "../config/identifier = 'STATIC'" {
                description
                  "Include static route parameters only when the
                  protocol is set to static";
              }
              description
                "Configuration and state parameters relating to
                static routes";
            }

I added the prefix 'oc-pol-types' to the STATIC value to address this. I suspect other when statements in this model have the same issue but did not specifically check them all.

Thanks,
Paul

**Comment by LeonGWang** [comment]
I believe the issue 1 is resolved by this commit 5dc792b7303a0f92aff8ffecb4bd9916f30e962a already.

**Comment by LeonGWang** [comment]
Issue 2 should be resolved by PR #267

**Comment by LeonGWang** [comment]
Issue 2 is merged upstream as well (not through PR #267), so this issue can be closed.
