### ISSUE TITLE
Question regarding oc-bgp:peer-type

### ISSUE THREAD

**Issue by missaesasaya** [openconfig/public#423]
I have a question regarding the use of /oc-bgp:bgp/oc-bgp:neighbors/oc-bgp:neighbor/oc-bgp:config/oc-bgp:peer-type configuration. This seems to be redundant, as the type could be derived by comparing local-as (or /bgp/global/config/as) and peer-as.

What is the goal of this configration? Could it be used instead of peer-as? Or should we add a check to ensure local-as and peer-as are the same when peer-type=INTERNAL?

**Comment by robshakir** [comment]
This leaf is explicitly specifying whether a peer should be treated as iBGP or eBGP -- you're right that this can be derived, but some JUNOS-like implementations include this as explicit configuration. It should not be used instead of `peer-as` in my view.
