### ISSUE TITLE
Typo in openconfig-platform-pipeline-counters.yang

### ISSUE THREAD

**Issue by rolandphung** [openconfig/public#424]
https://github.com/openconfig/public/blob/5a9965bbb81393f7524ea6af4f4f8316a9ee99a9/release/models/platform/openconfig-platform-pipeline-counters.yang#L717

lookup-aggregte -> lookup-aggregate

**Comment by kamiraux** [comment]
This seems fixed by #477

**Comment by dplore** [comment]
Yes, fixed now.
https://github.com/openconfig/public/blob/cc64bbf9b6c228aa438bc15fb66ad4c0670c0e72/release/models/platform/openconfig-platform-pipeline-counters.yang#L803
