### ISSUE TITLE
BGP model revision 6.0.0 -> 0.6.1

### ISSUE THREAD

**Issue by venkatmahalingam** [openconfig/public#427]
There is a revision change in file (release/models/bgp/openconfig-bgp.yang)  from 6.0.0 -> 0.6.1 in the below commit, is this intentional? this doesnt look right, please fix it.

https://github.com/openconfig/public/commit/13d68b9970acf8aa301ff9d60b084c11954e4c92#r52063963

**Comment by robshakir** [comment]
Upstream PR created for this.

**Comment by venkatmahalingam** [comment]
Thanks!

**Comment by robshakir** [comment]
This should be fixed in master. Thanks for the bug report. 

We also added a semver validation to our CI tests to make sure this doesn't happen again. Credit to @wenovus !
