### ISSUE TITLE
Clarification with openconfig-interfaces : last-change

### ISSUE THREAD

**Issue by jladouceur** [openconfig/public#43]
I hope this it the correct forum to clarify a question I have with the openconfig-interfaces, leaf last-change.

    leaf last-change {
      type yang:timeticks;
      description
        "Date and time of the last state change of the interface
        (e.g., up-to-down transition).   This corresponds to the
        ifLastChange object in the standard interface MIB.";
      reference
        "RFC 2863: The Interfaces Group MIB - ifLastChange";
    }

The type yang:timeticks appears to not be the best choice based on the description. A yang:timeticks does not describe a date and time. Only the elapse time between an undefined reference epochs.
Furthermore, if using yang:timeticks, the leaf must define the reference epoch, which appears to be missing.

This leaf appears to be the same as
ietf-interface.yang :  last-change :type yang:date-and-time

How are people in the community interpreting and using this leaf ?

**Comment by aashaikh** [comment]
hi -- our intention with this leaf is in fact to use timeticks but we need to update the description to make the reference epoch clear (thanks for pointing it out).   Our view is that the telemetry client can always convert the timeticks into whatever time format is desired -- `date-and-time` is primarily for human consumption.

We will update the description in the next revision to clarify this.

**Comment by jladouceur** [comment]
As an agent developer, can you clarify what the industry expects and/or currently uses as the epoch ?
I suspect that is would be since the system has been up. (ie. ticks relative to upTime)
The down side of this is the value wraps around after 497+ days, and more logic has to be done to interpret the value.

thanks for your feedback.

**Comment by aashaikh** [comment]
The common reference epoch for something like this would be the Unix Epoch (Jan 1, 1970 00:00:00 UTC) -- see BGP `last-established` opstate leaf as an example.

In the `openconfig-types` module, we define a `timeticks64`, which we use in the `last-established` leaf -- we can change this leaf accordingly.

thanks.

**Comment by jefftant** [comment]
Hi Guys,

We are (RTGWG rtg-dt-yang-arch team) finalizing ietf-routing-types.yang, at https://github.com/ietf-rtg-area-yang-arch-dt/conventions-features/blob/master/ietf-routing-types.yang
Do you feel - it would be useful to OC community? 
Anything you see missing?

Thanks and great weekend! 

Cheers,
Jeff
