### ISSUE TITLE
OpenConfig Styling guide: RPC definitions

### ISSUE THREAD

**Issue by prvattem** [openconfig/public#430]
OpenConfig YANG module template (https://openconfig.net/docs/style-guide/#openconfig-yang-module-template) has provision for defining RPCs.
An RPC definition(as defined below) fails with OC-linter complaining about missing config and state containers.
```
     rpc activate-software-image {
         input {
             leaf image-name {
                 type string;
             }
         }
         output {
             leaf status {
                 type string;
             }
         }
     }
```

What is the recommended definition and usage for RPCs?

**Comment by aashaikh** [comment]
Sorry for the confusion, we should update the module template to remove non-applicable placeholders.  OpenConfig models avoid a number of YANG language constructs including RPCs (this is also why the linter is not recognizing RPCs).  

For operational commands, including software image management per your example, please see the OpenConfig [gNOI](https://github.com/openconfig/gnoi) project.

**Comment by a-barboza** [comment]
@prvattem @aashaikh : I know the topic is closed, but before opening another topic on the matter I wanted to tap this thread to understand how REST/RESTConf clients would use gNOI in the absence of OpenConfig style guides for RPCs ? Is there a standard way to map gNOI to Yang RPC ?
