### ISSUE TITLE
Sflow model doesnt support same collector IP/port across network-instances

### ISSUE THREAD

**Issue by venkatmahalingam** [openconfig/public#440]
Hello @aashaikh 

In the below sflow YANG model, [collector](https://github.com/openconfig/public/blob/master/release/models/sampling/openconfig-sampling-sflow.yang#L171) list doesn't have 'network-instance' as the key, and hence same collector IP & port cant be configured across network-instances, is it possible to add network-instance also as key for collector list with major version change?

https://github.com/openconfig/public/blob/master/release/models/sampling/openconfig-sampling-sflow.yang#L142

**Comment by robshakir** [comment]
Thanks for this report - we'd be happy to review a PR for this change. There should be no need to have a major version change if the leaves are added in a way that does not change the interpretation of the existing leaves.

**Comment by venkatmahalingam** [comment]
> Thanks for this report - we'd be happy to review a PR for this change. There should be no need to have a major version change if the leaves are added in a way that does not change the interpretation of the existing leaves.

Sure, will create a PR for review, thanks!
