### ISSUE TITLE
Question about afts model

### ISSUE THREAD

**Issue by mikewiebe** [openconfig/public#441]
We have a couple of questions about the `afts` model for the following paths:

* `+ro /network-instances/network-instance[name]/afts/ipv4-unicast/ipv4-entry[prefix]/state/origin-protocol?   identityref`
    * If we have ECMP with 2 paths one from BGP and another from OSPF what should be set as the origin-protocol?

* ` +ro /network-instances/network-instance[name]/afts/ipv4-unicast/ipv4-entry[prefix]/state/decapsulate-header?   oc-aftt:encapsulation-header-type`
    * The definition according to the model is:
        * the specified header type. In the case that no next-hop is specified, the packet header is removed, and a subsequentforwarding lookup is performed on the packet encapsulated within the header, matched within the relevant AFT within thespecified network-instance.
    * Based on this a few queries:

If the prefix is not tunnel terminating what value should be populated here?

```yang
typedef encapsulation-header-type {
  type enumeration {
    enum GRE {
      description "The encapsulation header is a Generic Routing Encapsulation header.";
    }
    enum IPV4 {
      description "The encapsulation header is an IPv4 packet header";
    }
    enum IPV6 {
     description "The encapsulation header is an IPv6 packet header"; }
    enum MPLS {
    description "The encapsulation header is one or more MPLS labels indicated by the pushed and popped label stack lists.";
    }
  }
  description
    "Types of tunnel encapsulation that are supported by systems as either head- or tail-end.";
}
```

**Comment by robshakir** [comment]
Mike,

Thanks for the questions:

1. If there is an ECMP across protocols then `origin-protocol` here is likely not something that should be populated. We've had some discussion about adding `origin-protocol` at the next-hop level too, which would allow each NH to be identified w.r.t the protocol it was installed by.
2. If the packet is not being decapsulated - i.e., the packet is forwarded based on the outer header - then there's no need to populate the `decapsulate-header` field.

Cheers,
r.

**Comment by mikewiebe** [comment]
Thanks for the responses Rob.  This is helpful.
