### ISSUE TITLE
network-instance/fdb/mac-table -- evi type mismatch +question regarding vlan to vxlan mapping

### ISSUE THREAD

**Issue by rkashapov-bf** [openconfig/public#445]
https://github.com/openconfig/public/blob/ed650bd969afc2eb5f66d60b86b62ffa6fd5fb8e/release/models/network-instance/openconfig-network-instance-l2.yang#L309-L312

as mentioned in a description the leaf value references `/network-instances/network-instance/evpn/evpn-instances/evpn-instance/evi` which type is *string*, not *vni-id* (uint32).

https://github.com/openconfig/public/blob/ed650bd969afc2eb5f66d60b86b62ffa6fd5fb8e/release/models/network-instance/openconfig-evpn.yang#L524-L528

it's quite confusing and unclear what the actual reference is ... the identifier of `evpn-instance` or identifier of `vxlan`. 

it makes sense to update the reference: either to name the leaf `vni` (referencing associated vxlan) or to update the type to *string* (matching the identifier of `evpn-instance`)

also i have a related question: while the `evi` (vni?) entry under `fdb/mac-table` is read-only then what the expected way to configure the vlan to vxlan mapping?

**Comment by sbarguil** [comment]
Thank @rkashapov-bf  for your commet. 

For xpath: 

```
/network-instances/network-instance/evpn/evpn-instances/evpn-instance/config/evi
````

You are correct.  This should not be a string.  We need to change this to oc-evpn-types:vni-id. I'll create a PR to solve this issue. 

Regarding the second question, the mapping is donde in the same way it is done nowadays in the OC-NI, using the VLAN container.
