### ISSUE TITLE
Regex for IS-IS area address is incorrect

### ISSUE THREAD

**Issue by dan-lepage** [openconfig/public#459]
https://github.com/openconfig/public/blob/ed650bd969afc2eb5f66d60b86b62ffa6fd5fb8e/release/models/isis/openconfig-isis-types.yang#L326

This regex currently requires a trailing '.' (e.g. `49.0001.` instead of just `49.0001`); I believe it should be: `'^[0-9A-Fa-f]{2}(\.[0-9A-Fa-f]{4}){0,3}$'`.

**Comment by wenovus** [comment]
Thanks for raising this, we don't have tests for the is-is regexes: https://github.com/openconfig/public/tree/master/regexp-tests. If you want to fix the pattern you can a couple tests there following the same style.
