### ISSUE TITLE
add properties under subcomponent in the openconfig-platform.yang

### ISSUE THREAD

**Issue by dshokarev** [openconfig/public#46]
Hi OpenConfig team,

This is an enhancement request.

In this model https://github.com/openconfig/public/blob/master/release/models/platform/openconfig-platform.yang is it possible to add  platform-component-properties-top under platform-subcomponent-ref-top.

Basically, allow subcomponents to have properties too.

Thanks,
Dmitry.

**Comment by aashaikh** [comment]
hi Dmitry, in the platform model subcomponents are just components themselves, so they do have associated properties already.   The subcomponent list is just a set of references to establish the structure and relationships between components.

Let us know if you still have questions.

**Comment by dshokarev** [comment]
Thanks, Anees, this is clear now, I should have read the description.
