### ISSUE TITLE
Clarification regarding standalone-link-training present in oc-if-ethernet model 2.11.0

### ISSUE THREAD

**Issue by prabjosh** [openconfig/public#461]
On devices running Cisco IOS-XR software, UpRev of oc-if-ethernet model to 2.11.0 is being evaluated. As part of the same, support for standalone-link-training needs to be added.

Could you please provide us the cisco specific CLI related to this config/state leaf.

Thank You.

**Comment by aashaikh** [comment]
Not quite sure what is the ask here -- are you asking whether IOS-XR supports standalone link training as described in the model and the corresponding Cisco CLI commands?  Is this perhaps better directed to Cisco or corresponding XR documentation?

**Comment by prabjosh** [comment]
From what I checked, this configuration is not supported in Cisco IOS-XR. In that case is it OK to mark this leaf as a deviation (not-supported)?
