### ISSUE TITLE
Clarification regarding vlan-id leaf list in openconfig-vlan model

### ISSUE THREAD

**Issue by prabjosh** [openconfig/public#468]
Hi,

Following containers are defined in openconfig-vlan model (version 3.2.0) which deal in list of vlan ids.

- single-tagged-list
- double-tagged-inner-list
- double-tagged-outer-list

The list of vlan ids is supported in the form of a leaf list, comma-seperated with each item of the following type.

  typedef vlan-id {
    type uint16 {
      range 1..4094;
    }
    description
      "Type definition representing a single-tagged VLAN";
  }

Could you please clarify if an item in the list will be single tagged or ranged vlan id (with low and high value). Looking at the typedef definition it looks like we can't have a ranged vlan id (for example 100-200) in the leaf list.

Could you please help is in clarifying the above understanding.

Thank You.

**Comment by chrisy** [comment]
There are adjacent containers that deal with ranges explicitly; is there a combination you are looking for that is not represented? Are you looking for a list of ranges? What platform supports that?
