### ISSUE TITLE
AFT vs. FIB

### ISSUE THREAD

**Issue by jryburn** [openconfig/public#47]
The AFT and FIB models seem very similar. Is the AFT model intended to replace/deprecate the FIB model?

**Comment by aashaikh** [comment]
Yes, the AFT model deprecates the FIB model.  Thanks for pointing it out.

**Comment by robshakir** [comment]
The FIB model was removed.

**Comment by luyuanfang** [comment]
Thanks for the clarification. - Luyuan

**Comment by luyuanfang** [comment]
Assume you would update it in the logical model representation sometime later, along with other changes.
