### ISSUE TITLE
Need changes in OC-system hierarchy to accommodate scenarios of a distributed system

### ISSUE THREAD

**Issue by shrutikul96** [openconfig/public#475]
The current tree defined under openconfig-system (system/processes/process/state) has no option to accommodate the case where the OC path is being used for distributed systems as the process id (system/processes/process[pid]/state) is not unique across these kind of systems.

Suggestion would be to possibly provide a way to place linecard specific processes info under "/components/component/linecard/processes"

**Comment by aashaikh** [comment]
Can you please elaborate on the use case you're interested in, and what you mean by use in distributed systems?

**Comment by shrutikul96** [comment]
Hi aashaikh,

I have now modified the issue description to make the use case more understandable.

By distributed systems, I mean systems where we have both the control plane and the data plane running (Routing Engine + Linecard/ASIC)
