### ISSUE TITLE
Clarification regarding oc-if model version 2.5.0

### ISSUE THREAD

**Issue by anusharma87** [openconfig/public#479]
While trying to implement Openconfig-interfaces version 2.5.0 leaves 'management' and 'cpu', on Cisco IOS XR 
we are looking for some clarity on the semantics of these leaves in order to identify the correct mapping.

The openconfig description of management leaf indicates that - 
"When set to true, the interface is a dedicated management interface that is **not connected to dataplane interfaces**."
On devices running IOS-XR we have MgmtEth interfaces but they can be connected to dataplane of some platforms. So would this be a correct candidate to map to?

The openconfig description of cpu leaf indicates that -
"When set to true, the interface is for **traffic that is handled by the system CPU**, sometimes also called the control plane interface."
On devices running IOS XR we don't have special 'for-us' interface. If our understanding of the openconfig description is correct, then this would be an unsupported leaf on IOS-XR. Could someone kindly clarify if something more nuanced is expected here?

**Comment by anusharma87** [comment]
Any thoughts on this please?

**Comment by aashaikh** [comment]
*On devices running IOS-XR we have MgmtEth interfaces but they can be connected to dataplane of some platforms*

In this case, what makes them management interfaces?   What does it mean that they can be connected to the dataplane?  Would that be for users to implement in-band management?

*On devices running IOS XR we don't have special 'for-us' interface*

Do interfaces in XR in LPTS have an associated CPU0 interface entry?  (I'm not very familiar with this part of the arch).  If there is no interface exposed, then yes, I would expect this leaf to never be set to true.
