### ISSUE TITLE
Incorrect pattern in openconfig-yang-types.yang ?

### ISSUE THREAD

**Issue by patel-alpesh** [openconfig/public#48]
Looks like only an issue with openconfig-yang-types.yang. It contains a definition of date-and-time and the “pattern” looks incorrect according to RFC7950#section-6.1.3

   Within a double-quoted string (enclosed within " "), a backslash
   character introduces a representation of a special character, which
   depends on the character that immediately follows the backslash:
 
    \n      newline
    \t      a tab character
    \"      a double quote
    \\      a single backslash

 
The pattern contains \ as the date separator. But entire pattern is enclosed in double quotes.
 
  typedef date-and-time {
    type string {
      pattern
        "^[0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}" +
        "(\.[0-9]+)?Z[+-][0-9]{2}:[0-9]{2}$";
    }
 
Should the pattern be enclosed in single-quote or the instances of ‘\’ be changed to ‘\\\’ to fix problem?.

**Comment by robshakir** [comment]
Thanks for reporting this. We'll make the fix and publish a new version in the coming days.

**Comment by aashaikh** [comment]
This should be fixed in the latest push of the yang-types module.  Thanks again.
