### ISSUE TITLE
Query on “/network-instances/network-instance/afts/next-hop-groups/next-hop-group/state/color"

### ISSUE THREAD

**Issue by manirk-jnpr** [openconfig/public#485]
Hi @aashaikh and @robshakir,

This is a query on AFTS for nexthop group color.

For hierarchical fib use case shown below, if there are multiple colors in the different paths of ECMP, which color should be streamed?
Route -> ECMP -> path-1 (color 1) ->
-> path-2 (color 2) ->

Would it make sense to move this color information under “/network-instances/network-instance/afts/next-hops/next-hop/” instead of having it in next-hop-group?

Thanks,
Mani
Juniper Networks.

**Comment by manirk-jnpr** [comment]
Hi @aashaikh and @robshakir,

Could you respond to this query?

Thanks,
Mani

**Comment by robshakir** [comment]
Hi Mani,

The `color` leaf here is specifically intended to store colours as per the SR-TE policy architecture, where it is matched using the extended color community to routes within the system. Is this colour the same one that you're thinking of, as it's not clear to me that a single NHG can map to >1 color in the SR-TE architecture today AIUI.

Thanks,
r.
