### ISSUE TITLE
Port Mirror OC support needed,

### ISSUE THREAD

**Issue by nmmanju** [openconfig/public#487]
Hi OC-Team

There is a need from the vendor (Company: Juniper Networks Inc) to support port-mirroring feature under Sampling
current Sampling SFlowd, model does not suit the requirement for port -mirror

The ability to encap and send copy of a packet via GRE tunnel, or send copy of the packet to directly connected port, these are the capabilities which are needed, 

Please let me know if the above requirements look ok then I can propose an OC model for Port Mirror and Port mirror the packet via Tunnel.

Please let me know if you have a better solution to the above requirements.

Thanks and regards
Manjunath N M

**Comment by dplore** [comment]
Fixed in #544
