### ISSUE TITLE
Illegal unicode character in OSPF file

### ISSUE THREAD

**Issue by einarnn** [openconfig/public#49]
This line:

https://github.com/openconfig/public/blob/master/release/models/ospf/openconfig-ospfv2-area-interface.yang#L153

...appears to have an illegal unicode character before the section number that causes a compilation failure in pyang:

```
      reference "RFC3630, §2.5.5";
```

Cheers,

Einar

**Comment by robshakir** [comment]
Hi Einar,

I think this is valid - and should be treated as a pyang bug -- Section 6 of 6020 says:

```
  YANG modules use the UTF-8 [RFC3629] character encoding.
```

Thanks,
r.

**Comment by einarnn** [comment]
Agreed, yes.
