### ISSUE TITLE
Query regarding openconfig-platform-cpu

### ISSUE THREAD

**Issue by hanaik** [openconfig/public#496]
We are working on providing telemetry support for openconfig-platform-cpu. 
Below is the query:
1) It has component name as an input for which we are supposed to provide the CPU usage details for. What exactly component name refers to here? 

2) The component being referred to in the openconfig-platform-cpu is indicated in the module openconfig-platform-types as CHASSIS, BACKPLANE, FABRIC, POWER_SUPPLY, FAN which doesn’t make sense in context of cpu-utilization. We found two component (LINECARD and CONTROLLER_CARD) in openconfig-platform-types.yang which makes bit sense in this context.
But again if we use the component name as just LINECARD how can we specify which linecard (LC0,LC1.. etc)?

Today XR provides these cpu utilization details per node/location basis. So can we take the component name as LC(0/0/CPU0, 0/1/CPU0) and RP (0/RP0/CPU0, 0/RP1/CPU0).

So the xpath would be like
/openconfig-platform:components/component[0/0/CPU0]/cpu/openconfig-platform-cpu:utilization/state/instant
/openconfig-platform:components/component[0/0/CPU0]/cpu/openconfig-platform-cpu:utilization/state/interval
/openconfig-platform:components/component[0/0/CPU0]/cpu/openconfig-platform-cpu:utilization/state/max
/openconfig-platform:components/component[0/1/CPU0]/cpu/openconfig-platform-cpu:utilization/state/max-time
/openconfig-platform:components/component[0/RP0/CPU0]/cpu/openconfig-platform-cpu:utilization/state/min
/openconfig-platform:components/component[0/RP0/CPU0]/cpu/openconfig-platform-cpu:utilization/state/min-time

Or it has to be like:
/openconfig-platform:components/component[LINECARD]/cpu/openconfig-platform-cpu:utilization/state/instant **--> for LC**
/openconfig-platform:components/component[CONTROLLER_CARD]/cpu/openconfig-platform-cpu:utilization/state/instant **--> for RP**

If we have to follow the second method, then in case of multiple RP and LC, how can we specify for which node the CPU usage details are to be provided for?

Can someone please help with this query?

**Comment by MH-F** [comment]
Hi,
Have you already solved this problem?

**Comment by dplore** [comment]
I think the intent for this structure is that the  component with identity=`CPU` may contain `cpu/utilization/state/instant` and so on.   This `CPU` component may have a [/components/component/state/parent](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-platform.html#components-component-state-parent) which has identity=`LINECARD` or `CONTROLLER_CARD` for example.  

The name of the `CPU` component may be any string.  But the user should not need to parse the string to derive any structure or references to other components.  

@robshakir in case he has some other history behind the intent for how the paths are intended to be  used.
