### ISSUE TITLE
OC models for action commands?

### ISSUE THREAD

**Issue by mirceaulinic** [openconfig/public#50]
Hello,

Thanks for the great work here!

I have a question regarding other type of entities of data. I am not entirely sure it makes sense, but I'd like to expose the idea and hear more thoughts.
I think many of us (including myself) struggled to synthesize commands such as traceroute, ping etc. whose output depends very much on the vendor.
Would make sense to you to have models for those outputs as well? They would be pretty much similar to oper in scope, but the trigger is an action running in background rather than exposing attributes.

I am looking forward to hearing your thoughts!
Thanks,
--Mircea

**Comment by aashaikh** [comment]
Hi Mircea, there is some work ongoing to define common data for operational commands, including ping, traceroute, etc.  We are expecting to publish a draft of these soon -- please stay tuned.

**Comment by mirceaulinic** [comment]
Great stuff @aashaikh, thanks for info!
