### ISSUE TITLE
Yang Issue with openconfig-mpls

### ISSUE THREAD

**Issue by mksriram** [openconfig/public#51]
openconfig-mpls imports openconfig-segment-routing with a prefix of oc-sr
openconfig-mpls includes the sub-package openconfig-mpls-te which imports openconfig-mpls-sr whose prefix is also defined as oc-sr

In openconfig-mpls-sr, the prefix is defined as oc-mpls-sr

So can we please have the openconfig-mpls-te be modified to change the following
import openconfig-mpls-sr { prefix oc-sr; }
to
import openconfig-mpls-sr { prefix oc-mpls-sr; }

and the subsequent references of oc-sr to oc-mpls-sr?

**Comment by robshakir** [comment]
Hi,

I think this is valid YANG. Per Section 5.1 of 6020, then the prefix used in the import statement is only locally significant to the importing entity. We can look at changing this if it causes tooling issues -- could you confirm what toolchain you're using that doesn't support this please?

Thanks,
r.

**Comment by mksriram** [comment]
Sorry. I didnt realize that there was a question posted. 

I am using the Opendaylight yang parser.(Boron)

Thanks
Sriram
