### ISSUE TITLE
openconfig-bgp-global.yang: 'Enabled' leaf for confederation

### ISSUE THREAD

**Issue by adamsimpson1** [openconfig/public#52]
The inclusion of an 'enabled' leaf (type boolean) in the 'confederation' container is confusing. What is the purpose? There is no default configuration for a confederation that can be assumed if only the 'enabled' leaf is set to true and no other leafs in the container are set.

**Comment by robshakir** [comment]
Hi Adam,

I tend to agree here. I've opened an operators-repo issue to discuss this.

Thanks,
r.

**Comment by jefftant** [comment]
+1 Adam

Cheers,
Jeff
