### ISSUE TITLE
openconfig-bgp-global.yang: No default-route-distance for BGP protocol instance

### ISSUE THREAD

**Issue by adamsimpson1** [openconfig/public#53]
The current BGP model allows a route-distance to be set for EBGP routes and separate route-distance to be set for IBGP routes but there is no route-distance setting for all BGP routes (regardless of type) learned by a BGP instance. Would that be something to consider adding?

**Comment by robshakir** [comment]
Hi Adam,

We support the default metric for route distance through `/network-instances/network-instance/protocols/protocol/config/default-metric`. Is this what you were looking for?

Thanks,
r.
