### ISSUE TITLE
Guidelines for updating a Base Yang vs creating/updating an extension Yang

### ISSUE THREAD

**Issue by prvattem** [openconfig/public#539]
We have couple of OpenConfig Yang Models, which have a base model and an extension model. 
Example: openconfig-if-ethernet.yang and openconfig-if-ethernet-ext.yang
               openconfig-if-ip.yang and openconfig-if-ip-ext.yang

Are there any guidelines for:

1. What constitutes a base yang model and what goes into an extension?
2. If there is change required in the base yang, can we update the base yang with the change or make it part of the extension yang?
3. If there is no a extension yang, do we have to create one to capture the new changes to the base yang?
4. If we have to bring in a new feature for the Ethernet Interfaces, where would the changes be made (base or ext)?

**Comment by dplore** [comment]
Hi, thanks for your question.  Conceptually the base model is the minimum required schema for a model to be usable.  Where applicable, the choice of base or extension should follow the specification of the protocol or feature being modeled.   

One may submit a pull request to update the base model without touching the extensions.  If an extension is appropriate, you may suggest it's addition via a pull request without also touching the base model.
