### ISSUE TITLE
openconfig-bgp-common.yang: allow-multiple-as

### ISSUE THREAD

**Issue by adamsimpson1** [openconfig/public#54]
Why is allow-multiple-as modeled as specific to multipaths learned from EBGP peers? Why is not also applicable to multipaths learned from IBGP peers?

**Comment by robshakir** [comment]
Hi Adam,

Some implementations enforce such a check only for eBGP. Does SROS support this for both cases? Examining JUNOS, it seems like there is similar behaviour there - so we can consider adding it if SROS does.

Thanks,
r.
