### ISSUE TITLE
openconfig-system/state/config-time ?

### ISSUE THREAD

**Issue by a-barboza** [openconfig/public#545]
leaf boot-time {
        type oc-types:timeticks64;
        units "nanoseconds";
        description
          "This timestamp indicates the time that the system was last
          restarted.  The value is the timestamp in nanoseconds relative
          to the Unix Epoch (Jan 1, 1970 00:00:00 UTC).";
    }

Is there any plan to have a "config-time" leaf which would indicate the timestamp of the last configuration change?
And perhaps another leaf to indicate when the configuration was last saved to persistent/startup configuration?

**Comment by dplore** [comment]
Feel free to submit a pull request to add config-time.  Check the [external submissions guide](https://github.com/openconfig/public/blob/master/doc/external-contributions-guide.md) for tips on your first pull request

**Comment by a-barboza** [comment]
It appears a pull request has been raised here:
https://github.com/openconfig/public/pull/719

**Comment by dplore** [comment]
fixed by #719
