### ISSUE TITLE
openconfig-bgp-common-multiprotocol.yang: No Add-Paths configuration per AFI/SAFI

### ISSUE THREAD

**Issue by adamsimpson1** [openconfig/public#55]
Would it be useful to add an add-paths container to each afi-safi list element so that Add-Paths behavior can be controlled per AFI/SAFI? Applying the same Add-Paths parameters to all supported address families seems too restrictive.

**Comment by robshakir** [comment]
Hi Adam,

We'll discuss in the operators group and update this issue -- as of yet, no-one raised a requirement for per-AFI,SAFI.

Cheers,
r.
