### ISSUE TITLE
openconfig-bgp-peer-group: Inheritance units are unclear

### ISSUE THREAD

**Issue by adamsimpson1** [openconfig/public#56]
There is some ambiguity about what peer-group configuration should be inherited by a neighbor that is referenced to use that peer-group. The same for global BGP configuration inherited by a peer-group. For example, if afi-safi-X is enabled and afi-safi-Y is disabled in the peer-group configuration and only afi-safi-Y is enabled in the neighbor configuration, which of the following is expected:

(a) the neighbor has only afi-safi Y enabled, because the neighbor configuration of afi-safi list is authoritative
(b) the neighbor has afi-safi X and Y enabled, because each afi-safi element in the list is individually inherited

There are many other examples of this.

Somehow this needs to be specified in the model or else in a companion document.

**Comment by robshakir** [comment]
Hi Adam,

We'll take an action to write a companion document for this, or add it to the descriptions as you suggest. We expect that the neighbour-level configuration overloads the peer-group level.

Thanks,
r.
