### ISSUE TITLE
SRLG TLV system-id present under instances

### ISSUE THREAD

**Issue by raviv-arista** [openconfig/public#560]
In ISIS LSDB path, `/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/ipv4-srlg` or `../ipv6-srlg` has following child nodes `ipvx-srlg[instance-number]/state/system-id`. Which means all SRLGs are keyed by an arbitrary instance number irrespective of the neighbor it belongs to. This should ideally be first keyed by `system-id` and then `instance-number` since each SRLG instance is corresponding to a neighbor link.

This behaviour will be consistent with the existing `../link-state-database/lsp/tlvs/tlv/extended-is-reachability/neighbors/neighbor[system-id]/instances/instance[id]`. In `extended-is-reachability`, instances represent multiple links with the same neighbor.

**Comment by dplore** [comment]
@rsgcp can you review?
