### ISSUE TITLE
Query on router-id leaf in TE routerID TLV in IS-IS link-state-database

### ISSUE THREAD

**Issue by nikhil2553** [openconfig/public#561]
The router-id leaf ipv4 and ipv6 TE routerID TLV in isis link-state-database are **leaf-list** which should be just a **leaf.**

paths-
/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/ipv4-te-routerid/state/router-id
/network-instances/network-instance/protocols/protocol/isis/levels/level/link-state-database/lsp/tlvs/tlv/ipv6-te-routerid/state/router-id

The RFCs defining this TLVs are the following -
https://www.iana.org/go/rfc5305
https://www.iana.org/go/rfc6119

**Comment by robshakir** [comment]
The logic for having leaf-lists rather than leaves here was to cover the case when there might be multiple of the TLV present (even if this was not valid). In this case, we wanted to be able to ensure that telemetry could report these occurring.

Does that make sense?

**Comment by nikhil2553** [comment]
Makes sense.
I am closing the issue. Thanks.
