### ISSUE TITLE
openconfig-bgp-peer-group: Incorrectly pulls in route-selection-options?

### ISSUE THREAD

**Issue by adamsimpson1** [openconfig/public#57]
In peer-group/afi-sfis each afi-safi list item pulls in the route-selection-options container (grouping bgp-common-route-selection-options). This is probably incorrect. I don't think any implementation would allow route-selection options to vary based on peer group since that would introduce inconsistent best path selection and the possibility of routing loops, route oscillation, etc.

**Comment by robshakir** [comment]
Hi Adam,

I've opened an operators repo issue for this - we'll discuss and update this issue (and potentially the model).

Cheers,
r.
