### ISSUE TITLE
typedef bgp-ext-community-type 

### ISSUE THREAD

**Issue by adamsimpson1** [openconfig/public#58]
I am not sure how the first 3 string patterns are usable in this typedef because the sub-type is unspecified.

**Comment by robshakir** [comment]
Hi Adam,

These are intended to be the Two-Octet AS Specific (3.1 in RFC4360), IPv4 Address Specific (4360, 3.2), and 4-byte AS, 2b value (RFC5668) values. We made the modelling decision here to not have types assigned to these specific cases (where they are extensions of standard community usage). Do you see issues with this?

Thanks,
r.
