### ISSUE TITLE
openconfig-keychain.yang and Protocol association

### ISSUE THREAD

**Issue by smitharajan** [openconfig/public#587]
Hi,

I have two questions wrt openconfig-keychain.yang

1:I would like to know, how is the openconfig-keychain.yang going to accommodate, which protocol is using which keychain.
Currently, I don't see any config or state information under openconfig-keychain.yang referring to any protocol.
This is required whether we should allow no form of a key-chain or key-id, so that if no protocol is associated with the key-chain then only it is allowed.
Is some development work going on around this area as I see openconfig-keychain got introduced recently? Correct me if I am wrong.

2: I see that start-time / end-time  accepts nano seconds only relative to UNIX epoch..Any plan to accommodate  any other time format?

Thanks,
Smitha

**Comment by oscargdd** [comment]
Hi Smitha,

     The first step was to add the support for key-chain. Now, every protocol will be extended to use the key-chain as part of its authentication configuration. So, expect updates in the next weeks.

**Comment by smitharajan** [comment]
Thanks Oscar for your reply.

One more question, will there be config under keychain in openconfig-keychain.yang on which list of protocols using that keychain or will it be configured under protocol yang only?

Thanks,
Smitha

**Comment by smitharajan** [comment]
Hi,

Can somebody explain the significance of why **secret-key** has to be encrypted format? Is there any mechanism in place to maintain the (key , encryption algorithm ) used to encrypt this secret-key to be used?

  leaf secret-key {
      type string;
      description
        **"Authentication key supplied as an encrypted value.  The system should store and
        return the key in encrypted form.";**
    }

**Comment by dplore** [comment]
It is customary to use an encrypted string rather than a plain text
format.  Here are a couple of examples of support in vendor native CLI for
reference:

JunOS:
https://www.juniper.net/documentation/us/en/software/junos/user-access/topics/ref/statement/authentication-key-chains-edit-security.html
IOS XR:
https://www.cisco.com/en/US/docs/routers/xr12000/software/xr12k_r3.9/security/command/reference/sr39kcm.html#wp1015491

**Comment by sulrich** [comment]
both implementations (as well as others) also allow for plain-text configuration
of the key as well. the encrypted password is typically used for configuration
_restoration_ and commonly follows the vendor's specific encoding and foibles to
allow for config restoration, etc.

for initial configuration, it may not be feasible or practical to manage these
encrypted keys consistently.  having a mechanism to provide a plain-text key
seems useful.  this plain-text leaf could be restricted from retrieval in the
`state` container using whatever mechanisms the implementation provides for such
a restriction.  or, a vendor may simply opt to never present this within the
context of the `state` container based on whatever policy the implementation
provides

**Comment by sulrich** [comment]
@m26singhvi for ref

**Comment by smitharajan** [comment]
@sulrich: yes i do agree to provide support for plain-text.

@oscargdd: Can you please let me know is there any update at protocol yangs to make use of this keychain infra?

Thanks,
Smitha

**Comment by rgarunkumar** [comment]
Without having the option to configure plain-text, oc-keychain might not be usable for initial configuration. I think every vendor provides plain-text way of configuring the keys.

Some examples:

**Cisco**: https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/security/configuration/guide/b_Cisco_Nexus_9000_Series_NX-OS_Security_Configuration_Guide_7x/b_Cisco_Nexus_9000_Series_NX-OS_Security_Configuration_Guide_7x_chapter_010000.html -> Refer "key-string [encryption-type] text-string" with encryption-type = 0(plain-text)

**Juniper**: https://www.juniper.net/documentation/us/en/software/junos/user-access/topics/topic-map/user-access-root-password.html -> Refer 'plain-text-password' config option.

**Arista**: https://www.arista.com/en/um-eos/eos-data-plane-security#xx1211038 -> Refer "0Specifies that an UNENCRYPTED key will follow."

**Comment by m26singhvi** [comment]
There is a CRYPTO_NONE option available https://github.com/openconfig/public/blob/master/release/models/keychain/openconfig-keychain-types.yang which I think can be used to the crypto-algorithm value to signify unencrypted key.

**Comment by rgarunkumar** [comment]
My understanding is:
- CRYPTO_TYPE(which includes CRYPTO_NONE) specifies the 'crypto-algorithm' to be used by the protocol/application when they do their authentication i.e. on the protocol packets.
- Regarding the encryption for the secret-key means that how it is stored in the vendor's system - typically vendors store the keys in their system using some encryption techniques.

So, I think we can't use CRYPTO_TYPE(which includes CRYPTO_NONE) to specify the encryption technique used by the vendor.

**Comment by m26singhvi** [comment]
As per the following snippet from the key chain model, crypto-algorithm is associated with the key and not with the protocol.    

```
leaf crypto-algorithm {
      type identityref {
        base oc-keychain-types:CRYPTO_TYPE;
      }
      description
        "Cryptographic algorithm associated with the key.  Note that not all cryptographic
        algorithms are available in all contexts (e.g., across different protocols).";
    }
 ```

**Comment by rgarunkumar** [comment]
Hi @m26singhvi ,

Even though the crypto-algorithm is associated with the key, the keychain would ultimately be associated to a protocol. So when the protocol uses the keychain, it not only gets the active keys, it also gets the crypto-algorithm corresponding to that active key.

BTW, the description of the 'crypto-algorithm' clearly states that it is to be used by the protocols.
"Note that not all cryptographic algorithms are available **in all contexts (e.g., across different protocols)**."

Infact the 'crypto-algorithm' specified under the 'key' aligns nicely with some of the vendor implementations.

Example:
**JunOS:**
https://www.juniper.net/documentation/us/en/software/junos/user-access/topics/ref/statement/authentication-key-chains-edit-security.html
authentication-key-chains {
    key-chain key-chain-name {
        description text-string;
        key key {
            algorithm (md5 | hmac-sha-1); <---- [ARUN] This does not refer to how the keys are stored. This algo is used by the protocol
            key-name authentication-key-name;
            options (basic | isis-enhanced);
            secret secret-data;
            start-time yyyy-mm-dd.hh:mm:ss;
        }
        tolerance seconds;
    }
}

**Cisco:**
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/security/configuration/guide/b_Cisco_Nexus_9000_Series_NX-OS_Security_Configuration_Guide_7x/b_Cisco_Nexus_9000_Series_NX-OS_Security_Configuration_Guide_7x_chapter_010000.html

Under 'key' config:
cryptographic-algorithm {HMAC-SHA-1 | HMAC-SHA-256 | HMAC-SHA-384 | HMAC-SHA-512 | MD5}
Purpose: Configures the OSPFv2 cryptographic algorithm to be used for the specified key.

Thanks,
Arun.

**Comment by m26singhvi** [comment]
Sure, thanks @rgarunkumar. I raised a separate issue - https://github.com/openconfig/public/issues/785 to understand better about this.
