### ISSUE TITLE
Modeling of L2 Bridge domains

### ISSUE THREAD

**Issue by oscargdd** [openconfig/public#589]
I see there is an old issue (2016!!) about the topic https://github.com/openconfig/public/issues/30 

I open a new one here to trigger the discussion and see what is missing. 

There are devices in our network that require only layer 2 functionality, that is, mainly bridge domains. Hence, what we require is just to be ablet to create the bridge domains and associate intefaces/subinterfaces to them. 

Also, new EVPN use cases will require having multiple bridge domains. Right now, the assumption is a one-one mapping, so there is no problem :-) 

One idea is to create a bridge-domain container within network instance. 

For the L2 switch use case, possible solutions would be, 

* create a network instance of type L2VSI for the whole switch and the, create brige domains inside. Each bridge domain would have the associated interfaces.  This would require some modifications on the MAC table, as each bridge domain would have its own table. 
* create a  one network instance of type L2VSI for each bridge domain. Inside de ni, create the bridge domain. The MAC table can be reused as -is as there is a one-one mapping

For the EVPN use cases, the possible solution is:

Create a network instance of type L2VSI, enable the EVPN containers, and create the necessary bridge domains.

Comments, thoughts?

**Comment by rinhomdf** [comment]
Trying also to push again the topic, is there any ongoing discussion in the community about this?, especially for stitching L2 domains into VNO type services i believe might become important to represent somehow into the configs.

an example representation of how juniper devices try to represent these types of configs:
`routing instance L2VSI_INSTANCE {
     bridge-domains {
         CONTROL {
             vlan-id 1501;
             routing-interface irb.1501;
             vxlan {
                 vni 21001;
             }
         }
         MANAGEMENT {
             vlan-id 1500;
             routing-interface irb.1500;
             vxlan {
                 vni 21500;
             }
         }
         TENANT_1 {
             vlan-id 1601;
             routing-interface irb.1601;
             vxlan {
                 vni 22001;
             }
         }
         TENANT_2 {
             vlan-id 1603;
             routing-interface irb.1603;
             vxlan {
                 vni 22003;
             }
         }
     }
}`

**Comment by dplore** [comment]
Seems like a reasonable request.  Recommend send PR with reference to 2+ vendor implementations of the feature
