### ISSUE TITLE
openconfig-bgp-policy: match-as-path-set

### ISSUE THREAD

**Issue by adamsimpson1** [openconfig/public#59]
The match-as-path-set container has a match-set-options leaf that uses the typedef providing ANY, ALL and INVERT options. If we assume, as implied by the model, that an as-path-set is a concatenated set of strings, each of which is a regular expression used for AS path matching, then it's hard to understand how ANY, ALL or INVERT logic would be applied, since the regular expression already encodes these notions. I think it can be argued that the common match-set-options should not be applied to as-path-sets.

**Comment by robshakir** [comment]
Hi Adam,

Currently, the `as-path-set` are currently not regexps. We would expect that the `ANY`, `INVERT`, `ALL` options are implemented such that the actual specified sets are matched against. We have a TODO to determine how to have AS path regexps - at which point we would then examine whether `match-set-options` is applicable for that approach.

Will leave this issue open pending future examination of this functionality.

Thanks,
r.
