### ISSUE TITLE
pyang compilation error in openconfig-bgp

### ISSUE THREAD

**Issue by einarnn** [openconfig/public#6]
Hi,

When processing openconfig-bgp with latest revision of pyang from github, I get this error:

```
(pyang) ✔ /opt/git-repos/public/release/models/bgp [master|✔]
14:13 $ pyang --lint --strict -p ../policy openconfig-bgp.yang
openconfig-bgp.yang:428: error: restriction require-instance not allowed for this base type
(pyang) ✘-1 /opt/git-repos/public/release/models/bgp [master|✔]
14:13 $
```

Is this already a known issue?

Cheers,

Einar

**Comment by robshakir** [comment]
Hi Einar,

Yes -- as per this, and #9, this is known. The use of `require-instance` on a leafref is permitted in YANG 1.1. We'll discuss what is best to do and address this in a subsequent update.

Kind regards,
r.

**Comment by einarnn** [comment]
Great, thanks!

**Comment by robshakir** [comment]
Sorry -- I'll leave this one open until this is fixed.

Thanks!
r.

**Comment by mjethanandani** [comment]
The same is true for openconfig-mpls-te, openconfig-mpls-rsvp, and openconfig-mpls.

**Comment by bogaertb** [comment]
Shouldn't the module then use yang-version 1.1?  When using pyang supporting 1.1 you no longer get this error.

**Comment by bclaise** [comment]
Yep, all the "require-instance" errors are flagged at http://www.claise.be/IETFYANGPageCompilation.html, and the openconfig pack informed.

**Comment by robshakir** [comment]
@bogaertb  The models (as are being implemented) are intended to be YANG 1 compliant. In the next releases we will remove the `require-instance` statements.

Future revisions of the models may adopt Y1.1 - this will depend on discussions amongst the OpenConfig group, as well as with those third-party implementors who are working with various operators in the group.

**Comment by robshakir** [comment]
The current released OpenConfig BGP model has removed all `require-instance` statements on leafrefs.
