### ISSUE TITLE
Non config lists without a key

### ISSUE THREAD

**Issue by aniruddha-a** [openconfig/public#60]
Hello,

I see that there are some `list`s (for e.g., `router-capability,neighbors ` etc in `openconfig-isis-lsp.yang`) 
which are not marked as `config false;` but do not have a `key` specified either - isn't this a violation
according to RFC 6020:

```
7.8.2.  The list's key Statement

   The "key" statement, which MUST be present if the list represents
   configuration, and MAY be present otherwise
```

**Comment by robshakir** [comment]
Hi,

In YANG, the `config` parameter is inherited from a parent if there is no value explicitly specified at that level. In the `openconfig-isis.yang` file, the entire `link-state-database` hierarchy is marked `config false`: https://github.com/openconfig/public/blob/master/release/models/isis/openconfig-isis.yang#L1341

Please see RFC6020, Section 7.19.1:

```
   If "config" is not specified, the default is the same as the parent
   schema node's "config" value.  If the parent node is a "case" node,
   the value is the same as the "case" node's parent "choice" node.
```

Thanks,
r.

**Comment by aniruddha-a** [comment]
Ok, I missed the _inheritance_ part. Thanks
