### ISSUE TITLE
Update oc-macsec model to use oc-keychain model

### ISSUE THREAD

**Issue by m26singhvi** [openconfig/public#606]
Currently, openconfig macsec model -  public/release/models/macsec/openconfig-macsec.yang has a keychain container for configuring keys. 

Recently, a keychain model was published here - https://github.com/openconfig/public/blob/master/release/models/keychain/openconfig-keychain.yang 

which allows configuration of keys as well - most of it is pretty similar to what is present in Macsec model already. 

It will be good if the macsec model can remove out the key-chain container and refer to the key-chain model defined globally.

**Comment by dplore** [comment]
Thanks for the comment!  To help speed this along, I encourage you to submit a pull request to make the changes you would like to see.  Thank you!

**Comment by m26singhvi** [comment]
Thanks for taking a look at this. I will soon submit a pull request for this.
