### ISSUE TITLE
HTML representation not available

### ISSUE THREAD

**Issue by nicklasfrahm** [openconfig/public#608]
Hi,

it appears that the HTML representation is not accessible on the website (https://openconfig.net/models_html/index.html). I am currently exploring the data model, because I was working on a similar project and would love to join efforts.

This may be mixing questions a bit, but are there YAML or JSON examples of the YANG schemas? I find YANG to be hardly human readable. My use case is that I want to make Kubernetes CRDs and for this use-case it would be great to have YAML or JSON examples. I assume that it would be possible to programmatically create those from YANG, but for exploratory purposes _some kind_ of human readability would be nice.

**Comment by dplore** [comment]
The website is quite out of date, apologies.  There is some best effort / volunteer work to bring it up to date.  

Try this for rendering the OC models:
http://ops.openconfig.net/branches/models/master/

You can also use pyang from CLI:
```
(venv3) dloher@lucubrare:~/src/openconfig/public/release/models/interfaces$ pyang -p .. -f tree openconfig-interfaces.yang 
module: openconfig-interfaces
  +--rw interfaces
     +--rw interface* [name]
        +--rw name             -> ../config/name
        +--rw config
        |  +--rw name?            string
        |  +--rw type             identityref
        |  +--rw mtu?             uint16
        |  +--rw loopback-mode?   boolean
        |  +--rw description?     string
        |  +--rw enabled?         boolean
        +--ro state
        |  +--ro name?            string
        |  +--ro type             identityref

```
