### ISSUE TITLE
openconfig-bgp-neighbor: Add established boolean

### ISSUE THREAD

**Issue by loverend** [openconfig/public#61]
Currently you can represent the current state via `session-state` which requires one of `IDLE, CONNECT, ACTIVE...`. I propose that a key is added to represent if the state is established or not. 

One reason for this is that if a neighbour is enabled, but not established then the state may cycle between states, meaning that the value can become outdated very quickly.

Another reason is that we are trying to use openconfig to represent info received from syslog messages and can know that a session is not established, but not necessarily know the state.

I would like to know other peoples opinion before raising a PR.

**Comment by robshakir** [comment]
Per discussions in the operators repo, we decided not to make this change. Closing this issue :+1:
