### ISSUE TITLE
CLEI code for components

### ISSUE THREAD

**Issue by ejbrever** [openconfig/public#626]
I'd like to propose adding a leaf within the component state (https://github.com/openconfig/public/blob/master/release/models/platform/openconfig-platform.yang#L318) for the CLEI code.

The CLEI code is an industry standard globally unique identifier for telecom components :
https://en.wikipedia.org/wiki/Common_Language_Information_Services

**Comment by earies** [comment]
SGTM - I'd suggest just opening a PR to add the relevant node

For JUNOS, you can reference https://www.juniper.net/documentation/us/en/software/junos/interfaces-ethernet/topics/ref/command/show-chassis-hardware.html

**Comment by dplore** [comment]
Seems reasonable and in scope to platform models to me.

**Comment by ejbrever** [comment]
Just noting that most (if not all) optical platforms also support CLEI codes. A couple references:
Cisco: https://www.cisco.com/c/en/us/support/docs/optical-networking/ons-15454-sonet-multiservice-provisioning-platform-mspp/46247-15454-cleicodes.html
Nokia: https://documentation.nokia.com/html/365-372-324R10.0/index.html?i=365-372-324R10.0-qzx79
