### ISSUE TITLE
could not define field /openconfig-aft/afts/mpls/label-entry/state/next-hop-group: could not resolve leafref path

### ISSUE THREAD

**Issue by dliu2223** [openconfig/public#634]
proto_generator -add_schemapaths=false -base_import_path=github.com/openconfig/public/release/proto -compress_paths -consistent_union_enum_names -typedef_enum_with_defmod -enum_package_name=enums -exclude_modules=ietf-interfaces -go_package_base=github.com/openconfig/public/release/proto -ignore_circdeps -logtostderr -output_dir=proto -package_name=mpls -path=/root/dev_ubuntu/go/src/github.com/openconfig/public models/mpls/openconfig-mpls.yang
F0502 10:54:07.915925     497 protogenerator.go:136] could not define field /openconfig-aft/afts/mpls/label-entry/state/next-hop-group: could not resolve leafref path: [network-instances network-instance afts next-hop-groups next-hop-group state id] from &{0xc000816000 0xc00069a840 next-hop-group A reference to the next-hop-group that is in use for the entry
within the AFT. Traffic is distributed across the set of next-hops
within the next-hop group according to the weight.

**Comment by robshakir** [comment]
This is the same issue as #635 with the way that you're trying to generate a subset of the model. Please re-open that issue if you have questions.
