### ISSUE TITLE
could not define field /openconfig-aft/afts/policy-forwarding/policy-forwarding-entry/state/next-hop-group: could not resolve leafref path in openconfig-segment-routing.yang

### ISSUE THREAD

**Issue by dliu2223** [openconfig/public#635]
proto_generator -add_schemapaths=false -base_import_path=github.com/openconfig/public/release/proto -compress_paths -consistent_union_enum_names -typedef_enum_with_defmod -enum_package_name=enums -exclude_modules=ietf-interfaces -go_package_base=github.com/openconfig/public/release/proto -ignore_circdeps -logtostderr -output_dir=proto -package_name= -path=/root/dev_ubuntu/go/src/github.com/openconfig/public models/segment-routing/openconfig-segment-routing.yang

F0502 11:23:31.607391    1082 protogenerator.go:136] could not define field /openconfig-aft/afts/policy-forwarding/policy-forwarding-entry/state/next-hop-group: could not resolve leafref path: [network-instances network-instance afts next-hop-groups next-hop-group state id] from &{0xc00068a600 0xc0004e18c0 next-hop-group A reference to the next-hop-group that is in use for the entry
within the AFT. Traffic is distributed across the set of next-hops

**Comment by robshakir** [comment]
In this bug you're trying to generate bindings for a subset of the model that itself isn't necessarily meaningful -- i.e., `openconfig-segment-routing.yang`. This model itself is self-encapsulated, but when recursing into the `openconfig-network-instance` model then not all the dependencies are resolved. As such, you need to also generate the `openconfig-network-instance` model for this to work as you're expecting.

Now this will generate more messages than you're currently looking for, but essentially network instance is the buildable unit. You can exclude parts of the tree using deviations as input to ygot.

The `.spec.yml` specifications tell you the required modules for a model - specifically the `openconfig-network-instance-sr` rule [here](https://github.com/openconfig/public/blob/master/release/models/segment-routing/.spec.yml) is the relevant one here.
