### ISSUE TITLE
statistics in SR TE Policies: does it make sense to have in & out packets

### ISSUE THREAD

**Issue by oscargdd** [openconfig/public#638]
In SR-TE policies the following counters are defined

/network-instances/network-instance/segment-routing/te-policies/te-policy/state/counters/in-labeled-octets
/network-instances/network-instance/segment-routing/te-policies/te-policy/state/counters/in-labeled-pkts
/network-instances/network-instance/segment-routing/te-policies/te-policy/state/counters/in-octets
/network-instances/network-instance/segment-routing/te-policies/te-policy/state/counters/in-pkts
/network-instances/network-instance/segment-routing/te-policies/te-policy/state/counters/out-labeled-octets
/network-instances/network-instance/segment-routing/te-policies/te-policy/state/counters/out-labeled-pkts
/network-instances/network-instance/segment-routing/te-policies/te-policy/state/counters/out-octets
/network-instances/network-instance/segment-routing/te-policies/te-policy/state/counters/out-pkts

However, does it make sense to have both in & out statistics? The routers count the packets that match the policy, but not in or out.

**Comment by vcheny** [comment]
pkts/octets can be different when they are counted on ingress or egress directions. e.g. in-octets doesn't include the segments pushed to the packets while out-octets should. The delta between in-pkts and out-pkts would help in case devices discard some packets subjected to SRTE policies.
