### ISSUE TITLE
Incorrect when statement in vlan module

### ISSUE THREAD

**Issue by eugeneyudanov** [openconfig/public#642]
setup versions:
libyang - 2.0.112
sysrepo - 2.0.53

I have some problems with openconfig-vlan module. Leafs access-vlan, native-vlan, trunk-vlans have 'when' condition like `when "../interface-mode = 'oc-vlan-types:TRUNK'"` and `when "../interface-mode = 'oc-vlan-types:ACCESS'"`. Leaf interface-mode has the type `type oc-vlan-types:vlan-mode-type;`. vlan-mode-type is enumeration with values 'ACCESS' and 'TRUNK'. 

Problem: When I am trying to work with leafs access-vlan, native-vlan, trunk-vlans i got error because 'when' condition cannot be true in any cases. I can set to the leaf vlan-mode-type only values 'ACCESS' and 'TRUNK'. If I remove prefix in 'when' condition everything works fine.

I checked modules openconfig-vlan and openconfig-vlan-types through online validator Yanglint. It return warnings like
> libyang warn: Invalid value "oc-vlan-types:TRUNK" which does not fit the type (Invalid enumeration value "oc-vlan-types:TRUNK".).
> libyang warn: Previous warning generated by XPath subexpression[3] "interface-mode = 'oc-vlan-types:TRUNK'" with context node "/openconfig-interfaces:interfaces/interface/openconfig-if-aggregate:aggregation/openconfig-vlan:switched-vlan/state/trunk-vlans".
> libyang warn: Invalid value "oc-vlan-types:ACCESS" which does not fit the type (Invalid enumeration value "oc-vlan-types:ACCESS".).
> libyang warn: Previous warning generated by XPath subexpression[3] "interface-mode = 'oc-vlan-types:ACCESS'" with context node "/openconfig-interfaces:interfaces/interface/openconfig-if-aggregate:aggregation/openconfig-vlan:switched-vlan/state/access-vlan".
> ...

Prefixes was added by [commit](https://github.com/openconfig/public/commit/b3e96c91a86fc26af12b79bb7fa9b7b646a4a4c4).

It looks like it is the module problem. As I know we should use prefixes for identityref. For enumeration shouldn't. 
If I am wrong in something or do incorrect, please tell me.
Thank you!

**Comment by robshakir** [comment]
Thanks for catching this -- this does indeed sound like an issue in the module. I think this is one of the few cases where we have a `when` statement that references an `enumeration` value rather than an `identity`.

If you could create a PR to remove these prefixes, that would be great! We're in the process of looking at moving to libyang2 as part of our CI (we currently run libyang1, but based on some other interpretation differences, its results are of limited value).

Thanks,
r.
