### ISSUE TITLE
OpenConfig_System_SSH-Server: Yang model do no have provision for network instances and other parameters

### ISSUE THREAD

**Issue by kiravi23** [openconfig/public#643]
Hi,

I was going through the openconfig yang for SSH server in system folder([system-ssh-server-config](https://github.com/openconfig/public/blob/master/release/models/system/openconfig-system-terminal.yang)), it does not have any provision for network instance and other parameters. 

Network instance is a required option as we may require SSH server to be enabled in different VRF or network instance for management access.

I dont see global configuration support for SSH parameters like CIPHERs, MAC's, Key exchange algo and Host keys sizes in openconfig SSH server yang. This maybe needed to restrict algo based on the certifications body (FIPS, NIST...)

Regards
Kishore

**Comment by dplore** [comment]
Hi Kishore, thanks for the observations, I think you are correct.  You are welcome to propose an addition by creating a pull request to add the modeling you are looking for.
