### ISSUE TITLE
Clarification regarding IS-IS open config related to TLV isis-lsdb-common-extisreach-neighbors 

### ISSUE THREAD

**Issue by pkaneria** [openconfig/public#651]
Hello,

it has been notice that with newer version of isis yang file, IS-REACH-NEIGHBORS TLV was moved under instance container . Ealier there was no instance in IS-REACH NBR TLV.

Looks like this was done to support RFC 8202 ad instance-id is need derived from RFC8202.
After per rfc 8202 snip
"   IID #0 is reserved for the standard instance supported by legacy
   systems.  IS-IS PDUs associated with the standard instance MUST NOT
   include an IID-TLV except where noted in this document."

it is also possible that vendor doesn't support this RFC  Only ,standard instance supported by legacy systems.

There is confusion how to support IS_REACH_NBR TLV for standard instance in open config
1.  Standard instance doesn't support IID TLV. so Sending IS_REACH_NBR_TLV with instance id 0 doesn't seems to be valid.
2. if above point 1 is not correct, how standard instance support this TLV ( example would be great to understand)
3. as per my understanding , backward compatibility should be there for standard instance for IS_REACH_NBR_TLV but that is not present in latest version of open config. 

Request to clarify above item.

Regards
Parag

**Comment by robshakir** [comment]
When we were modelling the LSDB, there was some consideration as to how to model cases where there could (even if it were invalid) be more than one 'instance' (not in any sense other than the English word, so read: occurrence) of a TLV within an LSP. In this case, what we decided to do was create the model such that there was the ability to have a multiplicity of these TLVs. In some cases, this was achieved by creating a `leaf-list` (applicable where there was a single value inside the TLV). In other cases, this required a `list` and generally we called each occurrence of the TLV within that list as an `instance`.

So, the `instance` here is not designed to cover the IID, it's just supporting this case.  If you have not seen it, there is a reference parsing approach in https://github.com/openconfig/lsdbparse which demonstrates this for *most* TLVs.
