### ISSUE TITLE
Two reset-trigger mode cannot exist at the same time. The value should not be a key.

### ISSUE THREAD

**Issue by littlePeppy** [openconfig/public#659]
https://github.com/openconfig/public/blob/7a244a8e3259d3771a8ebef92b38b77e1cbadfdd/release/models/isis/openconfig-isis.yang#L535

**Comment by dplore** [comment]
Hi,  I can find reference for a few trigger conditions for ISIS overload reset:
- configuration
- timeout
- startup
- wait for bgp

It seems it is possible in some implementations to configure more than one of these at the same time?

https://www.cisco.com/c/en/us/support/docs/ip/integrated-intermediate-system-to-intermediate-system-is-is/24509-set-overload-bit.html#topic1

https://www.juniper.net/documentation/us/en/software/junos/is-is/topics/ref/statement/overload-edit-protocols-isis.html

**Comment by littlePeppy** [comment]
![image](https://user-images.githubusercontent.com/107677101/174600624-43c79d7d-275e-4c11-8bac-38b6b7755c9c.png)
When “set-bit-on-boot“ is true, that means “set-overload-bit on-startup“, the default <timeout> is used(it means wait-for-system). If you want to choose a tigger mode, then <timeout> and wait-for-bgp is alternative. 

So I think, The two reset-trigger mode cannot exist at the same time. It is consistent with you?

**Comment by robshakir** [comment]
An implementation does not *have* to support more than one mode simultaneously here - but I do think that there are use cases whereby one wants to specify a system timeout and a "wait for BGP". We might choose to model these in this way anyway (i.e., a list) such that this feels a reasonable choice.

Is there an implementation problem here other than validating that this combination might not be allowed in some implementations?
