### ISSUE TITLE
I'm not quite sure what this point means. “These labels should not be utilised by any dynamic label allocation” means this is a static block?   But,  dynamic label can be allocated form srgb.

### ISSUE THREAD

**Issue by littlePeppy** [openconfig/public#661]
https://github.com/openconfig/public/blob/c28f23731fe0d7b5816746bccef1efa25075b36a/release/models/mpls/openconfig-mpls.yang#L671

**Comment by robshakir** [comment]
hi,

I think you need to consider the whole sentence:

>        These labels should
>        not be utilised by any dynamic label allocation on the local system **unless
>        the allocating protocol is explicitly configured to specify that
>        allocation of labels should be out of the label block specified**.

(emphasis added)

in the case of the SRGB, the protocol allocating out of the dynamic label block that is the SRGB is explicitly told which label block should be used, and hence the "unless" part of this description kicks in.

the reason that we have this statement here is to say that once these label blocks have been made reserved they should not be used as general dynamic label space for the device - this is in-line with how the SRGB is done today. once one configures an SRGB then other protocols (rsvp-te, ldp etc.) should not be using labels from the configured SRGB.

cheers,
r.
