### ISSUE TITLE
Vendor-neutral software version leaf

### ISSUE THREAD

**Issue by tjburrows** [openconfig/public#675]
I am interested in adding an OpenConfig leaf that contains software version pertaining to the primary supervisor/routing engine of a router.  This is useful because it will allow a vendor-neutral way to query this commonly desired property.  

As of now, a `software-version` leaf only exists under `components`, but component names and/or the tree structure may vary by vendor, meaning one has to iterate over all components to find one that is of `OPERATING_SYSTEM` type to identify the desired `software-version` leaf.  A dedicated leaf would make this much easier.

What do you think?  Would `openconfig/system/state/software-version` make sense for the leaf location and name?

**Comment by dplore** [comment]
We should be able to reliably fetch the primary controller_card software version this way:
(type=OPERATING_SYSTEM) /components/component[name=<os>]/state/software-version

Does this work for your use case?

**Comment by tjburrows** [comment]
@dplore your suggestion is the current solution for software version, which does serve a purpose for those that want to know component-specific software information.  I believe this is valuable, but having a way to query a software version associated with a device, in a more abstracted sense, without having to choose a component (which has a vendor-specific name), would be nice.

**Comment by dplore** [comment]
I do see this as convenient and nothing is wrong with it.  It is true that most network devices do present some singular version string that represents all the software that is currently running.    Would you like to submit a pull request to add the leaf you're suggesting?  Then we can review and get feedback from the openconfig operators meeting.
