### ISSUE TITLE
last-calculated-sr-traffic is not defined

### ISSUE THREAD

**Issue by mryuezhang** [openconfig/public#678]
For leaf sr-traffic-pct, from openconfig-rsvp-sr-ext.yang, the description states that:

The value is specified as a percentage of the last-calculated-sr-traffic state leaf

However, there is no such a leaf named last-calculated-sr-traffic.

**Comment by dplore** [comment]
@mryuezhang thanks for reporting this issue.  Would you like to create a PR to propose a fix for this?

**Comment by mryuezhang** [comment]
Hi @dplore 

Please take a look a look at this PR https://github.com/openconfig/public/pull/680.

**Comment by mryuezhang** [comment]
Hi @dplore,

Please check https://github.com/openconfig/public/pull/681
