### ISSUE TITLE
What is in-sak-mkpdu and out-sak-mkpdu for in openconfig-macsec model. 

### ISSUE THREAD

**Issue by m26singhvi** [openconfig/public#679]
In openconfig-macsec model - macsec/interfaces/interface/mka/state/counters, there are leafs as follows - 
```
leaf in-sak-mkpdu {
      type oc-yang:counter64;
      description
        "Validated MKPDU received SAK count";
    }
```
Based on the description, there are can be multiple interpretation for the above counter : 

1.  Count unique number of SAK received in MKPDUs 
2. Count MKPDUs in which SAK is received ( there can be multiple MKPDUs which can have SAK ). 

What is the right interpretation from the above or is it something different ? I think it should be (1) but I want to double check. If yes, can we please update the leaf description to reflect this clearly. 

Similarly, for the following leaf as well. 
```
leaf out-sak-mkpdu {
      type oc-yang:counter64;
      description
        "MKPDU SAK sent count";
    }
```
I think the above leaf tracks the number of SAK sent out but please confirm and update description if it is so.

**Comment by samribeiro** [comment]
Hi @m26singhvi ,

in-sak-mkpdu: MKPDUs Received and Validated with SAK. There can be multiple MKPDUs. So this is your option 2)

out-sak-mkpdu: MKPDUs sent with SAK.

Please follow https://github.com/openconfig/public/blob/master/doc/external-contributions-guide.md to suggest a better description.

**Comment by m26singhvi** [comment]
I am not sure how useful option 2 is. Option 1 can help figure out the unique number of SAK distributed and received.

**Comment by samribeiro** [comment]
It is likely used for troubleshooting. You can propose an additional leaf that reflects what you want to see but this needs to be supported by an implementer.
