### ISSUE TITLE
openconfig-if-ethernet and openconfig-vlan doesn't augment on interface type correctly

### ISSUE THREAD

**Issue by lalit-arrcus** [openconfig/public#68]
These models and others where iana-if-type is included as ift is broken . iana-if-type model is ianaift so openconfig models should include iana-if-type as {prefix ianaift} instead of {prefix ift}

openconfig-vlan.yang:  import iana-if-type { prefix ift; }

**Comment by robshakir** [comment]
There is no such requirement in RFC6020 - the importing module must be able to import with its own prefix to allow disambiguation. What tooling is having issue handling this?

r.

**Comment by lalit-arrcus** [comment]
I'm using confd for it.


-Lalit

________________________________

**Comment by einarnn** [comment]
I work with confdc from confd, the basic version, and it has no issue with namespaces.

**Comment by lalit-arrcus** [comment]
that's interesting. I'm using confdc too and hitting the issue and above workaround works.
I'll take it up with confd and see whats going on.

-Lalit
