### ISSUE TITLE
What is in-cak-mkpdu and out-cak-mkpdu for in openconfig-macsec model

### ISSUE THREAD

**Issue by m26singhvi** [openconfig/public#683]
In openconfig-macsec model - macsec/interfaces/interface/mka/state/counters, there are leafs as follows -

```
leaf in-cak-mkpdu {
      type oc-yang:counter64;
      description
        "Validated MKPDU received CAK count";
    }

leaf out-cak-mkpdu {
      type oc-yang:counter64;
      description
        "MKPDU CAK sent count";
    }

```

Do they refer to group-cak feature mentioned in 802.1X-2010 standard ? If yes, can we update the description of the leaf ?

**Comment by samribeiro** [comment]
Hi @m26singhvi ,

connectivity association key (CAK), these are the group-cak feature mentioned in 802.1X-2010 standard.

Please follow https://github.com/openconfig/public/blob/master/doc/external-contributions-guide.md to suggest a better description.

**Comment by m26singhvi** [comment]
Great, thanks for the confirmation. 

Sure, I will raise a pull request to update the description.
