### ISSUE TITLE
Why isn't current-datetime in the system module under the clock container?

### ISSUE THREAD

**Issue by cfyo** [openconfig/public#685]
It seems that it would make more sense to have "current-datetime" under /system/clock/state instead of /system/state.

**Comment by dplore** [comment]
I think it's fair to say this could be presented either way.   The precedent is /sys/clock is used for configuration of the clock, and the state is to get the current clock configuration.  Whereas the value for the clock is treated as part of system state, along with the datetime for boot.    

In the case where two options are very similar, but one is already implemented, I think we should stay with what we have to avoid churn.  In addition, this leaf would be a breaking change so I'd prefer not to make this change unless there is a larger structural issue here.
