### ISSUE TITLE
Configuring aggregation members

### ISSUE THREAD

**Issue by cfyo** [openconfig/public#690]
Where do you add a member to a lag group?  You can read out members in /interfaces/interface/aggregation/state but the associated config path doesn't have a place to define members and I don't see anything under /interfaces/interface/config to add an interface to a group.

**Comment by dplore** [comment]
[This leaf defines an aggregate-id](https://github.com/openconfig/public/blob/aeaf85ee5662f01420a623d0d5a306a2185b9b4b/release/models/interfaces/openconfig-if-aggregate.yang#L198-L211)

Next, [this augment adds the aggregate-id to ethernet ports](https://github.com/openconfig/public/blob/aeaf85ee5662f01420a623d0d5a306a2185b9b4b/release/models/interfaces/openconfig-if-aggregate.yang#L229-L235)

This results in a leaf that looks like:

`/interfaces/interface/ethernet/config/aggregate-id`

**Comment by robshakir** [comment]
It's worth saying that this is configured for the member interfaces to specify that they are part of some aggregate.

**Comment by dplore** [comment]
I'll close this item.  Feel free to reopen if needed.
