### ISSUE TITLE
Software module-type for BIOS or bootloader

### ISSUE THREAD

**Issue by aredmon8551** [openconfig/public#697]
https://github.com/openconfig/public/blob/9152b712c79d0fcd776ec4b8efc9f655f6c5b916/release/models/platform/openconfig-platform-software.yang#L51

Reading through the identities of SOFTWARE_MODULE_TYPE (USERSPACE_PACKAGE_BUNDLE, USERSPACE_PACKAGE) it would seem we would need to add another for firmware or system related packages (e.g., BIOS, bootloader).

Is my interpretation correct?  If so, happy to open a pull request, just want to confirm my understanding is correct first.

**Comment by dplore** [comment]
This is a good question.  I would like to understand one or more use cases we are solving for and then I think we can identify a good solution.

**Comment by aredmon8551** [comment]
Hey Darren,

I think the BIOS and bootloader are good examples of this.  Firmware (FPGAs, other co-processors) may also fall in here, as well.

**Comment by dplore** [comment]
These are more types for sure and seem reasonable.  However, I am looking for operational use cases for exposing this data?  My personal opinion as an operator is I would prefer to know as little as possible about the internal processes and software modules inside a NOS.  The most simple abstraction would be a single software version for the whole device and I would use gNOI.OS to make changes to that.  

However, I am willing to concede that my point of view is naive if there are operational use cases to add additional types and manage software components at a more granular level.  If you or other contributors can provide these, I think it will help us understand what is needed to be modeled.

**Comment by aredmon8551** [comment]
Every shipping implementation (that I'm aware of) involves distinct and independent software packages.  EOS has aboot, EVO and SR-LINUX/EVO/IOS-XR have a BIOS.  These are often decoupled and can be upgraded independently.

**Comment by dplore** [comment]
Can you define a use case for us?  For example,  ```as a network operator, I would like to do x,y,z```.

Just trying to figure out what problem we are trying to solve so I can evaluate if there needs to be new modeling for it.

FWIW,  there are identities defined for BIOS and BOOT_LOADER today.  Not sure if these will meet your use case though.

https://github.com/openconfig/public/blob/f3f05d5f6e38ca7c46671ea5a4c11b62d264c10b/release/models/platform/openconfig-platform-types.yang#L367-L379
