### ISSUE TITLE
Clarification regarding afi-safi: /network-instances/network-instance/protocols/protocol/isis/global/afi-safi/af/config/

### ISSUE THREAD

**Issue by pkaneria** [openconfig/public#702]
Hello,

I would like to clarify Global AFI-SAFI under protocol isis config.

1. does this container /network-instances/network-instance/protocols/protocol/isis/global/afi-safi/af/config related to   ISIS Multi-topology configuration ?
2.  does MULTICAST is also possible values of SAFI ? or it it just UNICAST only ?

Regards
Parag

**Comment by dplore** [comment]
Hi,  quick answer is yes in that 
[/network-instances/network-instance/protocols/protocol/isis/global/afi-safi/af/multi-topology/config](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-network-instance.html#network-instances-network-instance-protocols-protocol-isis-global-afi-safi-af-multi-topology-config)
relates to ISIS MT.


I do not understand question #2?   Could you provide more context and example paths you are thinking about?
