### ISSUE TITLE
Support for RFC 8214 EVPN VPWS

### ISSUE THREAD

**Issue by singularsyntax** [openconfig/public#724]
Are there any plans or work underway to formally support [RFC 8214](https://www.rfc-editor.org/rfc/rfc8214.html)-style EVPN VPWS in the OpenConfig EVPN models?

I see that the existing [EVPN support](https://github.com/openconfig/public/blob/master/doc/evpn_use_cases.md) adheres to [RFC 7432](https://datatracker.ietf.org/doc/html/rfc7432). However, if you squint at it hard enough, it appears that most of the necessary elements for RFC 8214 are already defined, with the notable exception of some explicit binding between a `vpws-service-id` (i.e. `ethernet-tag`) and attachment circuit endpoints, which is in fact [defined](https://github.com/openconfig/public/blob/master/release/models/network-instance/openconfig-evpn-types.yang#L296) in the model, just not referenced in any of the EVPN-related network instance types.

**Comment by dplore** [comment]
Hi, thanks for logging this issue.  We will welcome your model contributions to add what you are looking for.  With previous EVPN models it was a challenge to find multiple peer reviewers with deep EVPN experience.  You will need to identify a volunteer to perform review with subject matter expertise in EVPN.

**Comment by dplore** [comment]
Note, a few [PR's have merged and more are in progress](https://github.com/openconfig/public/pulls?q=is%3Apr+evpn+) which add/expand vpws support.
