### ISSUE TITLE
Aggregate-sid-counters should be keyed by sid instead of mpls-label

### ISSUE THREAD

**Issue by shraddha-hegde** [openconfig/public#728]
/network-instances/network-instance/mpls/signaling-protocol/segment-routing/aggregate-sid-counters/aggregate-sid-counter/state/out-pkts

aggregate-sid-counters use mpls-label as key. 
In segment routing the SID is constant (not changing) from one node to another.
mpls label is derived based on SRGB start and the SID. Segment routing architecture allows the nodes to
have different SRGB. The mpls label would change based on neighbor's SRGB. This is problematic for the 
out-pkts counters  because mpls label can be different across the two neighbors.

Model should be updated to use SID as the key for aggregate-sid-counters

**Comment by earies** [comment]
cc: @dplore @robshakir 

Notable deviations for this today

https://github.com/aristanetworks/yang/blob/master/EOS-4.29.0F/release/openconfig/models/mpls/arista-mpls-deviations.yang
https://github.com/YangModels/yang/blob/main/vendor/cisco/xr/771/cisco-xr-openconfig-network-instance-deviations.yang

**Comment by dplore** [comment]
Thanks for reporting the issue.  @rgwilton, @rolandphung, @hobbydos  for comment
