### ISSUE TITLE
Reporting temperature state for components with multiple temp sensors

### ISSUE THREAD

**Issue by aredmon8551** [openconfig/public#734]
https://github.com/openconfig/public/blob/00a27a5f0f3c472205ef293ab238e0530b610811/release/models/platform/openconfig-platform.yang#L564

Looking for guidance on implementation approach regarding temperature state.

In several instances a component like a linecard or routing-engine will house several temperature sensors. Given that, we have a potential issue with a paths like the following:

```
/components/component/state/temperature/alarm-severity
/components/component/state/temperature/alarm-status
/components/component/state/temperature/alarm-threshold
/components/component/state/temperature/avg
/components/component/state/temperature/instant
/components/component/state/temperature/interval
/components/component/state/temperature/max
/components/component/state/temperature/max-time
/components/component/state/temperature/min
/components/component/state/temperature/min-time
```
If we represent this at a granular level, it would read as something like:

`/component/component[CHASSIS0:LINECARD0:TEMP0]/state/temperature/*`

Where in the above TEMP0 is one of many of the sensors onboard the component.

Looking for feedback regarding this approach - I believe it's compliant, though want to ensure we're aligning properly to any precedents/operator expectations already out there.

**Comment by earies** [comment]
> But it would appear duplicative if rendered as a tree.

That's fine and the parent/child relationship should be mandatory in all cases where it applies and a hw/sw component is not by chance anchored at the root w/ or w/o children.  The string encoding scheme as you mention is up to each implementation but encoding the full parent relationship directly in this node gives the added benefit of uniqueness and flexibility since this list is system wide - more of an implementation detail than anything

**Comment by dplore** [comment]
To clarify, the expectation for components of TYPE=SENSOR is:

* `/components/component/state/parent` for component TYPE=SENSOR will be set to an appropriate component.
* `/components/component/state/description`  should have a human readable description that could be used to understand the component's location/position in the device and type.  (for example, `CPU Temperature sensor 1`)

The parent component will have an appropriate `openconfig-platform-types` set such as `CPU`.  The parent may be recursively traced to resolve it's position in the component tree, all the way up to the `CHASSIS` component.
