### ISSUE TITLE
Why is macsec-ciphersuite a leaf-list in openconfig-macsec : macsec/mka/policies/config

### ISSUE THREAD

**Issue by m26singhvi** [openconfig/public#743]
Currently, macsec-ciphersuite is a leaf list in openconfig-macsec, path - macsec/mka/policies/config.  

In a policy, only one macsec-ciphersuite is expected to be used once configured, then why do we need this to be a leaf list and can we make this a leaf only ?

```
leaf-list macsec-cipher-suite {
      type macsec-types:macsec-cipher-suite;
      description
        "Set Cipher suite(s) for SAK derivation";
    }
 ```

Proposal : To make this a leaf instead.

**Comment by dplore** [comment]
Are there implementations that allow more than one cipher-suite to be configured?  I did a quick search and found reference to a [cisco ios xr implementation](https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r7-3/system-security/configuration/guide/b-system-security-cg-asr9000-73x/implementing-macsec-encryption.html) and [junos implementaton](https://www.juniper.net/documentation/us/en/software/junos/security-services/topics/ref/statement/cipher-suite-edit-security-macsec.html)  reference which show the ability to configure only one cipher-suite.    

I found a third [reference to arubua ](https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-7886/Content/Chp_MACsec/MACsec_cmds/cip-sui-mac-ll-10.htm)which permits multiple cipher suites.

OC should support the more permissive use case.  If a platform can only support one cipher-suite, the device may reject a setRequest containing more than one cipher.

**Comment by m26singhvi** [comment]
Thanks for taking a look at this.  As per 802.1X-2020 ( Figure 11.12 ) , only 1 ciphersuite can be used to generated a new SAK. May be the 3rd implementation you referred allows configuration of multiple ciphersuites but uses eventually 1. 

In any case,  device rejecting a setRequest containing more than one ciphersuite sounds good to me.

**Comment by dplore** [comment]
Ok, I will close this issue.  Feel free to reopen if necessary.
