### ISSUE TITLE
Suggestions about key leaf of list "static-groups"

### ISSUE THREAD

**Issue by SiyuChen22** [openconfig/public#748]
Hi,
I'm Siyu from Huawei. We notice that the leaf "static-group" is the only key leaf of list "static-groups" currently. Under this circumstance, the new (Source2,Group) record will be merged with the old (Source1,Group) record when they have the same group address but different source address.
We think it would be better to set leaf "source" as key leaf as well so that records with different sources can coexist.
We are looking forward to your reply.
Best wishes.

**Comment by robshakir** [comment]
Which model does this refer to please?

r.

**Comment by SiyuChen22** [comment]
It's list "static-groups" of "grouping igmp-static-top" in file called "openconfig-igmp.yang".
