### ISSUE TITLE
IS-IS lsp-id typedef is wrong in openconfig-isis-types

### ISSUE THREAD

**Issue by nokia1adam** [openconfig/public#751]
Typedef for lsp-id looks wrong. The encoding limits the fragment IDs to 0-99. The last two characters should be in the hex [0-9a-f] to allow for 256 fragments.

 typedef lsp-id {
    type string {
      pattern
            '[0-9A-Fa-f]{4}\.[0-9A-Fa-f]{4}\.[0-9A-Fa-f]'
      +      '{4}\.[0-9][0-9]-[0-9][0-9]';
      oc-ext:posix-pattern
            '^[0-9A-Fa-f]{4}\.[0-9A-Fa-f]{4}\.[0-9A-Fa-f]'
      +      '{4}\.[0-9][0-9]-[0-9][0-9]$';
    }

**Comment by dplore** [comment]
Hi @nokia1adam, it would be greatly appreciated if you can submit a PR to update the model.  We'll review and approve.
