### ISSUE TITLE
Origin-protocol for next-hops

### ISSUE THREAD

**Issue by aredmon8551** [openconfig/public#755]
https://github.com/openconfig/public/blob/200af096528411e2ba26dc04d2dced4e823c7be9/release/models/aft/openconfig-aft-common.yang#L380-L385

Having a debate with protocol developers regarding the origin-protocol for next-hops - my understanding is that this state should reflect the protocol through which the next-hop was learned.  This should not reflect the protocol that instantiates/triggers the next-hop (i.e., kicks off the resolution). 

Some examples:
1. For an ARP learned next-hop, INSTALL_PROTOCOL_TYPE should be DIRECTLY_CONNECTED
2. For an indirect next-hop learned through OSPF INSTALL_PROTOCOL_TYPE should be OSPF regardless of what other protocols may be using that next-hop for resolution.

Are the above examples accurate?

**Comment by dplore** [comment]
Yes, I think your interpretation is correct and agrees with the OC yang description.  Is there an issue with this approach?

**Comment by nokia1adam** [comment]
Considering the relationship ip-entry[A]->next-hop-group[B]->next-hop[C], it seems that this is proposing that the origin-protocol of [A] should always be the same as the origin-protocol of [C]. If so, what's the point of origin-protocol for next-hops?

In my opinion, the origin-protocol of [C] should be the resolving protocol of the next-hop, otherwise it's not providing anything useful that isn't already known from the hierarchy of AFT objects.

**Comment by aredmon8551** [comment]
@nokia1adam - maybe I'm missing something, but in my second example ip-entry[A] could be BGP (or gRIBI, static, etc.) and next-hop[C] could be OSPF, so different protocols.  Your opinion is shared by some others that I'm speaking to, but I'm struggling to understand the line of thought behind it.

**Comment by nokia1adam** [comment]
No, I don't think you are missing anything and it's a valid question. My reasoning is just based on the usefulness of the information. The model doesn't need to tell you that the next-hops of a BGP route were provided by the BGP protocol. But you might be interested to know that a particular BGP next-hop has been resolved by an OSPF route (for example) to provide the direct forwarding interface.
