### ISSUE TITLE
openconfig-isis.yang: isis-overload-bit-reset-config 

### ISSUE THREAD

**Issue by nikhil2553** [openconfig/public#77]
We have **delay** associated with the reset-trigger and description of which says "If a reset trigger is specified, the system should delay resetting the overload bit for the specified number of seconds after the trigger occurs.".

For WAIT_FOR_SYSTEM delay the resetting of overload-bit is fine but for for WAIT_FOR_BGP delay resetting of overload-bit after BGP has converged doesn't make much sense. Does this delay refer to the timeout in case of WAIT_FOR_BGP, time after which we should reset the overload-bit even if BGP hasn't converged.

**Comment by robshakir** [comment]
The `delay` leaf consistently means that we should delay after the trigger having occurred -- so it shouldn't ever be interpreted as a timeout [0]. It's fine for an implementation not to support a delay of resetting after BGP has converged.

Thanks for pointing out the missing `timeout`. I've added this into the model and will review it with the group.
