### ISSUE TITLE
openconfig-isis-routing.yang: missing rt-admin-config in multi-topology config container

### ISSUE THREAD

**Issue by nikhil2553** [openconfig/public#78]
under isis-mt-list we have multi-topology container which contains config and state container. Looks like we are missing rt-admin-config (enabled) in config container. It is present in state container though.

**Comment by nikhil2553** [comment]
what is the need of afi-name and safi-name under multi-topology container as multi-topology container itself is under afi-safi list.

**Comment by robshakir** [comment]
Thanks for catching the missing `rt-admin-config` issue. This will be fixed in a pending release.

I also agree that the dual-specification of the AFI and SAFI identifier is a bug. I'll amend this and suggest a fix to the team.

Thanks!
r.
