### ISSUE TITLE
missing channels in channels-type?

### ISSUE THREAD

**Issue by precla** [openconfig/public#797]
https://github.com/openconfig/public/blob/5ca6a36fb57b09ab656fc608ac134550c9a43716/release/models/wifi/openconfig-wifi-types.yang#L60

For example, channels 171, 172 are missing. `iw phy phy0 channels` shows it for my device (mac80211 hwsim):
```
* 5855 MHz [171] 
          Maximum TX power: 13.0 dBm
          Channel widths: 20MHz VHT80
* 5860 MHz [172] 
          Maximum TX power: 13.0 dBm
          Channel widths: 20MHz VHT80
```

There seems to be a few more missing when compared to this wikipedia article. For example 155, 138 -> don't have those in my `iw phy phy0 channels` output tho.

https://en.wikipedia.org/wiki/List_of_WLAN_channels#5_GHz_(802.11a/h/j/n/ac/ax)

Is this on purpose?

**Comment by jsnyder81** [comment]
@precla 
I'm not sure on 172, this is an 802.11p frequency and i'm not sure enterprise infrastructure will be used for this band for C-V2X, this requires some research.  HWSIM can be used by those other industries as well, so it's not unusual for them to have new bands before actual hardware.

171 is a UNII-4, which we should get added as i think OC hardware from one vendor supports this today.

In terms of terminology, these are the 20MHz primary channels. For 155, 138, these are 80MHz channels in 5GHz and 40MHz in 6GHz. So 155 is inclusive of (149, 153, 157, 161) in 5GHz and (153, 157) in 6GHz. 138 is inclusive of (132, 136, 140, 144) in 5GHz.

**Comment by precla** [comment]
Considering the comment and commit, I can say that it can be closed as completed unless you want to further investigate.
Thanks!

**Comment by jsnyder81** [comment]
@precla I think we are ok with the current implementation unless we need to add those .11p channels.  The remaining are all bonded center frequency number, but we include the primary 20MHz members.  For example:
171 = 165 @ 80MHz.

The same goes for things like 38 (which is 36 + 40).  Configuration would be the primary 20MHz + channel width.

**Comment by precla** [comment]
Thanks again for the investigation and feedback!
