### ISSUE TITLE
question: level capability description "vlevel"

### ISSUE THREAD

**Issue by dfitzg1** [openconfig/public#80]
What is the meaning of "v" before the "level-1-2" in the description?  Also, this is intended to mean both 1 and 2, right?
leaf   level-capability {
--
type   oc-isis-types:level-type;
default   "LEVEL_1_2";
description
"ISIS   level capability(level-1, level-2,vlevel-1-2).";
}

**Comment by robshakir** [comment]
This is a typo, but yes - `LEVEL_1_2` means both level 1 and level 2.
