### ISSUE TITLE
BGP large communities and send-community leaf

### ISSUE THREAD

**Issue by missaesasaya** [openconfig/public#809]
Hi all,

I have some questions/suggestions regarding the following leaf:

     /network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/config/send-community

Currently, it has 4 possible values: STANDARD, EXTENDED, BOTH and NONE. But, [RFC 8092](https://www.rfc-editor.org/rfc/rfc8092.html) defines a new type of community: LARGE. From what I could understand, Cisco has redefined BOTH to include all community types, but this prevents the customer to send only large communities or only extended and large communities. Why can't we have send-community changed to a leaf-list or a bits type leaf where we can set any combination of STANDARD, EXTENDED and LARGE values?

Another issue is: the implementation I am working with allows the configuration of send-community per address-family in a peer/peer-group. Is it possible to have this option also? We would keep the current config in peer/peer-group level and add a new send-community leaf inside afi-safi list.

Regards

Missae

**Comment by robshakir** [comment]
hi Missae!

Couple of comments.

1. For adding large communities support, absolutely we can look to make a change here. Generally, we do not use the bits type, but a leaf-list would be a potential option. Here, I'd suggest opening a PR with a proposal - linking to >= 2 different vendor implementations so that we can compare how this maps across different implementations.
2. The answer here is similar -- if this is something that is widely supported then this is a change we can make. The best way to kick off that discussion is to open a PR!

Thanks!
r.

**Comment by sundaramtirunel** [comment]
```
Another issue is: the implementation I am working with allows the configuration of send-community per address-family in a peer/peer-group. Is it possible to have this option also? We would keep the current config in peer/peer-group level and add a new send-community leaf inside afi-safi list.
```
You have mentioned in the description that you want to add a send-community leaf under neighbor and peer-group afi-safi list. I would welcome that move and help us adopt this leaf very easily.
But here, you have added the leaf under global afi-safi list.
Can you move that to neighbor afi-safi list? The grouping name is `bgp-common-mp-afi-safi-config` right under this grouping.

**Comment by dplore** [comment]
@sundaramtirunel note #852 completed the issue regarding LARGE communities.  I recommend starting a new issue regarding "configuration of send-community per address-family in a peer/peer-group. "  if you are interested in pursuing that further?

**Comment by sundaramtirunel** [comment]
Thanks @dplore @missaesasaya for suggestions.
We can open new issue on this.

**Comment by missaesasaya** [comment]
I will close this, as this is being handled in #976
