### ISSUE TITLE
typo in leaf iid-tlv description : think "trues" should be "true"

### ISSUE THREAD

**Issue by dfitzg1** [openconfig/public#81]
Think "When set to trues" is intended to be "When set to true".
   
 leaf iid-tlv {
      type boolean;
      default false;
      Description
        "ISIS Instance Identifier TLV. When set to trues, the IID-TLV identifies
        the unique instance as well as the topology/topologies to which the
        PDU applies.";
      reference "RFC6822: IS-IS Multi-Instance. TLV 7";

**Comment by nkmafi** [comment]
When iid-tlv is set, the IS-IS instance identifier is advertised as described in RFC6822.
The IS-IS instance however is defined as a string. So were do we configure the instance identifier number?

grouping isis-global-config {
    description
      "This grouping defines lobal configuration options for ISIS router.";

    // multi-instance
    leaf instance {
      type string;
      default 0;
      description
        "ISIS Instance.";
    }
