### ISSUE TITLE
Question on laser control on optics

### ISSUE THREAD

**Issue by fgruman** [openconfig/public#819]
During implementing the model for optical pluggables, we had a question on the laser control for the optics.

Is laser controlled by the transceiver's port's (optical-port) admin-state?
Or is the laser controlled by the tranceiver's physical-channel tx-laser boolean?

We were thinking the tx-laser initially but the description of this attribute indicates that this controls a tx-label.
    leaf tx-laser {
      type boolean;
      description
        "Enable (true) or disable (false) the transmit label for the
        channel";
    }

It was not clear what was meant by "transmit label".  Can this be clarified?  is this a communication channel within the laser (e.g., maybe a modulation label for connectivity discovery).

So it seemed like tx-laser may not be meant for laser on/off control.
So should the optical port admin state be used for this function?

Is this interpretation correct?

**Comment by fgruman** [comment]
As a follow up to this question, when dealing with a breakout cable with 4 interfaces, there doesn't appear that I can control the individual interfaces without using the tx-laser attribute or adding an explicit admin-state (or other type of laser control).

**Comment by dplore** [comment]
@ejbrever can you respond for us?

**Comment by ejbrever** [comment]
IIRC, tx-laser is actually what you want to turn off the laser. I think that wording is incorrect (I think "label" is supposed to be "laser").

I have seen some platforms use admin-state with different behaviors. In many cases, disabling the admin state acts as a parent to disable the laser on all sub-physical-channels. In other cases, disabling the admin-state allows the tx-laser to still fire, but silencing alarms/alerts for the transceiver.

I do think with the first behavior, the device should not implicitly set tx-laser to disable if the admin-state is disabled. Instead, it should require the tx-laser to be explicitly set to disable (i.e. have to set both). This is just to avoid implicit behaviors that would not easily be understood.

**Comment by dplore** [comment]
Please feel free to reopen if there are further comments on this issue

**Comment by fgruman** [comment]
Thanks, I think this answered my question.  Sorry I should have responded explicitly.

**Comment by dplore** [comment]
Glad to hear it!
