### ISSUE TITLE
isis/openconfig-isis.yang : missing leaf "enabled"

### ISSUE THREAD

**Issue by m26singhvi** [openconfig/public#84]
In isis/openconfig-isis.yang, for grouping isis-interface-config, one of the leaf "enabled" seems to be missing but it is present here in : 

http://ops.openconfig.net/branches/master/openconfig-network-instance.html#

This issue has been raised assuming the above url is more latest than the github source code.

**Comment by robshakir** [comment]
In the network instance model, we enable protocols within the `protocols/protocol/config` container, not within each individual model. This leaf is therefore intentionally removed.

**Comment by m26singhvi** [comment]
Couple of things here : 

1.  What if we want to disable isis protocol only for one of the interfaces. We can't update protocols/protocol/config container, as it applied to all the interfaces. 

2. Can we try and keep the following tree in sync with code or vice versa ?
http://ops.openconfig.net/branches/master/openconfig-network-instance.html#

**Comment by robshakir** [comment]
IS-IS is not enabled unless the interface is explicitly listed within the interfaces list. There is no "default enabled" configuration for IS-IS in OpenConfig.

The link you are pointing to is not intended to be up-to-date with the public repo. We're proposing to add auto-generated documentation in the future but it will not be at that link.

**Comment by m26singhvi** [comment]
Thanks a lot for replying ! I guess I can close this issue then !
