### ISSUE TITLE
incorrect condition check in "when" stmts in openconfig-bgp-policy model

### ISSUE THREAD

**Issue by alpesh-arrcus** [openconfig/public#87]
The comparison checks need to be updated to put the enums in quotes. Diff below. Pls note the line numbers do not match with the latest file but the issue is still valid.

``````
785c785
<       when "../config/method=INLINE" {
---
>       when "../config/method='INLINE'" {
844c844
<       when "../config/method=REFERENCE" {
---
>       when "../config/method='REFERENCE'" {
948c948
<       when "../config/method=INLINE" {
---
>       when "../config/method='INLINE'" {
1009c1009
<       when "../config/method=REFERENCE" {
---
>       when "../config/method='REFERENCE'" {
``````

Pls help address in next release.

thanks
alpesh

**Comment by LeonGWang** [comment]
Hi, I am running into the same issue. Wondering if a fix is in the works.

**Comment by aashaikh** [comment]
@LeonGWang can you please comment on where you are seeing this issue? (e.g., which toolchain)

**Comment by LeonGWang** [comment]
Seems like this issue is fixed (merged upstream) and can be closed.
