### ISSUE TITLE
Question/clarification about qos-queue-config

### ISSUE THREAD

**Issue by cosmos2k17** [openconfig/public#871]
The _qos-queue-config_ grouping in _openconfig-qos-elements_ is a template which needs to be applied to interface?
If so shouldn't we have the queue name under  _openconfig-qos-interface_ refer to _qos-queue-config_?

If it is different, why do we have queue name configurable under _openconfig-qos-interface_ ?

**Comment by dplore** [comment]
Hi there, Can you be more specific?  Are you referring to  [/qos/interfaces/interface/input/queues/queue/config/name](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-interfaces-interface-input-queues-queue-config-name)?

https://github.com/openconfig/public/blob/aec94a15243712da1d236e2d5c30434dcb7ccff9/release/models/qos/openconfig-qos-interfaces.yang#L286-L300

The purpose of this leaf is to associate a named queue with the interface.  ref: [openconfig qos overview](https://github.com/openconfig/public/blob/master/doc/qos_overview.md)

**Comment by cosmos2k17** [comment]
Hi, yes, i am refering [/qos/interfaces/interface/input/queues/queue/config/name](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-interfaces-interface-input-queues-queue-config-name)

I hope named queue is created at [/qos/queues/queue/config/name](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-queues-queue-config-name) in which case, we need to have this path mentioned under [/qos/interfaces/interface/input/queues/queue/config/name](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-interfaces-interface-input-queues-queue-config-name) as like it is done under [/qos/forwarding-groups/forwarding-group/config/output-queue](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-forwarding-groups-forwarding-group-config-output-queue)

or both are different?

**Comment by dplore** [comment]
> Hi, yes, i am refering [/qos/interfaces/interface/input/queues/queue/config/name](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-interfaces-interface-input-queues-queue-config-name)
> 
> I hope named queue is created at [/qos/queues/queue/config/name](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-queues-queue-config-name) in which case, we need to have this path mentioned under [/qos/interfaces/interface/input/queues/queue/config/name](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-interfaces-interface-input-queues-queue-config-name) as like it is done under [/qos/forwarding-groups/forwarding-group/config/output-queue](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-forwarding-groups-forwarding-group-config-output-queue)
> 
> or both are different?

[See example QoS config for details](https://github.com/openconfig/public/blob/master/doc/qos_overview.md#ingress-classification-with-egress-scheduling) on the configuration and how interfaces are included.
 
Queues are associated with a list of interfaces by setting this leaf-ref to the [/qos/interfaces/interface/config/interface-id](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-interfaces-interface-interface-id)
