### ISSUE TITLE
what is the best way to model FLEXO and Flexogroup ?

### ISSUE THREAD

**Issue by aagrawal493** [openconfig/public#874]
Please suggest what is the best way to model FLEXO and Flexogroup into openconfig model.

**Comment by dplore** [comment]
Could you provide a reference to more details?  For example, a link to documentation for some implementation from a router vendor or open source?

**Comment by aagrawal493** [comment]
i was referring to Flexible OTN from ITU-T G.709.1.
https://www.itu.int/rec/T-REC-G.709.1-201806-I

**Comment by dplore** [comment]
@ejbrever Are you familiar with this?  Any suggestions for @aagrawal493 ?

**Comment by ejbrever** [comment]
I'm not familiar with Flexo unfortunately. I took a very quick look and it almost seems like this is just adding more layers within the OTN model, which I think should be fine from as the model supports the flexibility to layer through logical-channels. This might have already been supported as I see these protocol types specified:
https://github.com/openconfig/public/blob/master/release/models/optical-transport/openconfig-transport-types.yang#L755-L763

If those don't cover what is additionally needed, perhaps we just need to add another TRIBUTARY_PROTOCOL_TYPE?

**Comment by dplore** [comment]
Closing issue as stale, please feel free to reopen with new comments @aagrawal493
