### ISSUE TITLE
How to Enable Record Route for MPLS Tunnels(LSPs)

### ISSUE THREAD

**Issue by mryuezhang** [openconfig/public#889]
Hello,

OpenConfig has the definitions for record route objects. However, there is no config/state leaf for record-route under LSPs. Does OpenConfig always assume record-route is enabled on MPLS tunnels and cannot be turned off?

**Comment by mryuezhang** [comment]
I suggest that something similar to the snippet below can be added under [tunnel-p2p-attributes-config](https://github.com/openconfig/public/blob/master/release/models/mpls/openconfig-mpls-te.yang#L799)
```Yang
container record-route-config {
  leaf enabled {
    type Boolean;
    default false;
    description
      "enables record-route on the
       lsp";
  }
}
```

**Comment by dplore** [comment]
Hi, thanks for the comments.  This is a good obseration.   OC only exposes record route objects as state via this container:  
[/network-instances/network-instance/mpls/signaling-protocols/rsvp-te/sessions/session/record-route-objects/record-route-object/state](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-network-instance.html#network-instances-network-instance-mpls-signaling-protocols-rsvp-te-sessions-session-record-route-objects-record-route-object-state)

There is no enable/disable for record route in OC today, so it is implied that record route is always enabled.  

Do you need to disable record route?

Your proposal seems to align in concept with what [Cisco IOS-XR ](https://www.cisco.com/c/en/us/td/docs/routers/crs/software/crs_r4-1/mpls/command/reference/mpls_cr41crs_chapter3.html#wp419523793) and [JunOS](https://www.juniper.net/documentation/us/en/software/junos/mpls/topics/ref/statement/record-edit-protocols-mpls.html)
support.  That is,  enable/disable record route (which is on a per tunnel interface).  IOSXR and JunOS have different defaults though.  (Cisco appears to disable by default where JunOS is enabled by default).   

I think I would just add an enabled leaf under the existing grouping you linked to.  An additional container isn't needed.

ie something like:
```yang
  grouping tunnel-p2p-attributes-config {
    description
      "Configuration related to p2p LSPs";
    leaf destination {
      type inet:ip-address;
      description
        "P2P tunnel destination address";
    }
    leaf enabled {
      type Boolean;
      default true;
      description
        "Enables recording a path on an LSP using the record route object (RRO)";
    }
  }

I prefer enable by default as this is inline with the current expected OC behavior, making this a non-breaking change.

**Comment by mryuezhang** [comment]
As you’ve pointed out, record route is disabled by default on IOS-XR. Therefore, there must be a way inside OpenConfig to enable it. 

However, I disagree on giving any default values to this leaf. The reason is that currently the default behaviour for record route on tunnels using OpenConfig is rather undefined than enabled. The default behaviour is up to each vendor’s operating system. Since OpenConfig is intended to be vendor-neutral, providing any default value to this leaf is favouring some operating systems over the others.
 
Hence, I propose to add something like below:

```Yang
  grouping tunnel-p2p-attributes-config {
    description
      "Configuration related to p2p LSPs";
    leaf destination {
      type inet:ip-address;
      description
        "P2P tunnel destination address";
    }
    leaf record-record-enabled {
      type Boolean;
      description
        "Enables recording a path on an LSP using the record route object (RRO)";
    }
  }
```

**Comment by dplore** [comment]
We discussed in OC operators group today.   @oscargdd noted that RRO is an optional specification in MPLS.  IMO, this does mean that RRO should not be enabled by default.  

Please propose a pull request to add this leaf.  The community can debate if there needs to be a default, but I agree that by RFC defniition that the feature is optional means the default does not need to be 'enabled'.

**Comment by mryuezhang** [comment]
Opened #926
