### ISSUE TITLE
supporting eVPN service models 

### ISSUE THREAD

**Issue by sanju-a** [openconfig/public#89]
Hi, 

I know there were discussion in the past around the eVPN model and see the placeholder for L2VPN in "bgp/openconfig-bgp-common-multiprotocol.yang". Is there a topic I can look up that captures the details. I tried looking it up but could not find. Pardon me if this is a re-ask. 

I would like to know the background before proposing the models initially for type 2, for intra-DC and later for type-5 for inter-DC. 

Thanks,
Sanju

PS: I have also posted on the mailing list.

**Comment by aashaikh** [comment]
hi Sanju -- not sure there is a specific thread or issue on this, but past discussions on "service" models essentially concluded that we would focus on device level modeling (where there is a lot of opportunity for common standards), and then folks could build service models on top using the common building blocks.

That said, I think we'd be open to updating the device / protocol models (e.g., BGP) with the requisite support for eVPN, etc.  We're also working on a better-defined process to allow the wider community to propose additions to the models, while still maintaining an operator-driven perspective.

**Comment by hasanrazaonline** [comment]
Hi,
It has been 2 years and this issue still in open state. Any update whether evpn openconfig yang effort is initiated and running in the background? If not, do we have the process now in place to get started on it?

**Comment by chrisy** [comment]
@hasanrazaonline I am not aware of anyone else working on EVPN, but we (Comcast) will be digging into it soon, certainly for some MPLS-based use cases and possibly also VXLAN. We will start once we have some clarity on the specifics of our use cases. Very early initial indications suggest that most of the structure will fit within the current way we use OpenConfig for l2vpn type services and adding needed EVPN specific identifiers etc, but too soon to tell if this is all that is needed.
