### ISSUE TITLE
QoS Classiers terms should be ordered list

### ISSUE THREAD

**Issue by rszarecki** [openconfig/public#896]
Currently Classier terms is list with "id" being a key, while "id" is of string type.
This do not allow to unambiguisly tell the order of terms, what is critical, since condition of terma may be overlaping.
Also adding of ne term would not be possible.

https://github.com/openconfig/public/blob/51e534ee090d8c641fa886ab13422e8e94a68774/release/models/qos/openconfig-qos-elements.yang#L164

It is suggested to replace Id with sequence-Id similiarly to sedulers[seq-id] of uint32 type. And mandate taht terms are evaluated always in ascending order.

**Comment by dplore** [comment]
I think sequence id is a good approach and as noted there is precedence in the QoS module to use a sequence id.   

[/qos/scheduler-policies/scheduler-policy/schedulers/scheduler/config/sequence](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-scheduler-policies-scheduler-policy-schedulers-scheduler-config-sequence) is used for ordering scheduler policy.
