### ISSUE TITLE
bgp-policy uses require-instance on a leafref

### ISSUE THREAD

**Issue by mjethanandani** [openconfig/public#9]
While it is probably ok to use require-instance on a leafref in YANG 1.1, where the restriction has been relaxed, YANG 1.0 does not support it. If anything it complains about it. Is there a plan to have a YANG 1.0 model for bgp-policy that does not use require-instance?

**Comment by robshakir** [comment]
Hi Mahesh,

As per #6, we're currently discussing this. I'll close this issue as it is a duplicate.

Thanks!
r.
