### ISSUE TITLE
route-policy:defined-sets:bgp-defined-sets:ext-community-sets members type

### ISSUE THREAD

**Issue by rcicu** [openconfig/public#901]
https://github.com/openconfig/public/blob/6e1174af25db09af1f58a42ff51c01be864a6e88/release/models/bgp/openconfig-bgp-policy.yang#L532

Currently `ext-community-member` is a list of `oc-bgp-types:bgp-ext-community-type` and `oc-bgp-types:bgp-community-regexp-type` but it will not be beneficial to have it as a list of containers?

Having to delete one entry for the list is difficult, since you need to know that values are there and update the list with all the values, except the target one. Using a list of containers it will allow to apply a `YFilter.delete` to the desired entry. This is similar to how prefixes are removed from `route-policy:defined-sets:prefix-sets`.

Or there is another way to do that without knowing the values before?

**Comment by dplore** [comment]
I am working to refactor the bgp communities from a union type of many regex strings to explicitly defined types in containers.

I think the community-set will still be a list, but pointing to a list of containers instead of a list of strings.

**Comment by dplore** [comment]
@rcicu the refactored bgp community model with communities modeled with strongly typed leafs in containers is here:  #883 

I'd apprecaite a review if you are interested.
