### ISSUE TITLE
Inconsistent 'enabled' structure in STP

### ISSUE THREAD

**Issue by rgwilton** [openconfig/public#902]
Looking at the STP model, we noticed that is configures protocol instance enable differently from how this is normally done in OC, i.e., via a per protocol instance enabled flag:

```
  +--rw stp
     +--rw global
     |  +--rw config
     |  |  +--rw enabled-protocol*               identityref

when the enabled-protocol is a leaf-list that default to empty, or otherwise contains RSTP, MSTP or RAPID_PVST.
```

Is there any reason why this shouldn't just be done as simple enabled flags for the rstp, mstp, and rapid-pvst containers, i.e., mirroring how this is generally done in other parts the OC YANG model?

E.g.,
```
  +--rw stp
     +--rw rstp
     |  +--rw config
     |  |  +--rw enabled?         boolean
     +--rw mstp
     |  +--rw config
     |  |  +--rw enabled?         boolean
     +--rw pvst
     |  +--rw config
     |  |  +--rw enabled?         boolean
```

**Comment by dplore** [comment]
For quick reference, [/stp/global/config/enabled-protocol](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-spanning-tree.html#stp-global-config-enabled-protocol) and the [git blame](https://github.com/openconfig/public/commit/65ea19c2fa91d67b1a87091549946805c248da6c) for the addition to the models.

Comments from internal notes only show this is intended as a way to allow multiple STP protocols to be enabled at the same time.   More comments from others on this topic are appreciated.

**Comment by dplore** [comment]
Recommend submitting a PR to refactor this as suggested.  To prevent a breaking change, please use deprecate on the existing list.
