### ISSUE TITLE
how breakout groups should be represented in openconfig-platform-transceiver yang ?

### ISSUE THREAD

**Issue by aagrawal493** [openconfig/public#906]
As per examples provided in openconfig-platform-port yang if a 400G-DR4 interface (8 electrical channels at 50Gbps) is to be broken out into 4 100Gbps ports, the following configuration is used:
{
              \"groups\": {
                \"group\": [
                  {
                    \"config\": {
                      \"breakout-speed\": \"SPEED_100GB\",
                      \"index\": 0,
                      \"num-breakouts\": 4,
                      \"num-physical-channels\": 2
                    },
                    \"index\": 0
                  }
                ]
              }
            }";
Here total 4 breakouts are done and each breakout contain 2 physical channels.
in openconfig-platform-transceiver  subtree /components/component/transceiver/physical-channels can this be represented by breakout groups ?
or in other words, as per example this physical channels will be 8 indexes, or these can be represented by 4 breakout groups ?
if these physical channels will be 8 indexes then  where breakout group properties should be mapped ?

**Comment by dplore** [comment]
/components/component/transceiver/physical-channels is intended to list all the channels on a physical port.  I interpret this to be 8 channels in your example.


[/interfaces/interface/state/physical-channel](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-interfaces.html#interfaces-interface-state-physical-channel) is intended to point to only the channels used for a specific interface.  So each of the breakout 100GB Ethernet interfaces would have a list of channels that are allocated to the 100G interface.  So I think this is how you can see the mapping of those 8 channels to 4 interfaces.

**Comment by dplore** [comment]
Feel free to reopen if this doesn't answer your question or you disagree with the interpretation
