### ISSUE TITLE
.../vlan/members/member Should be keyed

### ISSUE THREAD

**Issue by aaronbee** [openconfig/public#94]
Hello,

We were investigating whether the OpenConfig models have any unkeyed lists (other than leaf-lists), because it is not clear how describe a path to them, for example in a subsciption update. It turns out there is only one unkeyed list:

network-instances/network-instance/vlans/vlan/members/member

This member list has a base-interfaces-ref-state, which is a state container containing a leafref to the interfaces list. The member collection could be keyed by this leafref, by making a leafref to it. For example,

```
list member {
    key interface;
    leaf interface {
        type leafref {
            path "../state/interface";
        }
    }
}
```

**Comment by dplore** [comment]
This issue is obsolete.
