### ISSUE TITLE
Errors seen while running pyang on bgp models

### ISSUE THREAD

**Issue by sidheshdivekar29** [openconfig/public#95]
Hi,
Am seeing errors while trying to generate tree for bgp models using pyang.
ietf-interfaces and ietf-yang-types doesn't seem to be present in the repo.

~/workspace/public/release/models/bgp$ pyang -f tree  openconfig-bgp.yang openconfig-bgp-types.yang openconfig-bgp-policy.yang openconfig-bgp-peer-group.yang openconfig-bgp-neighbor.yang openconfig-bgp-global.yang openconfig-bgp-errors.yang openconfig-bgp-common.yang openconfig-bgp-common-structure.yang openconfig-bgp-common-multiprotocol.yang openconfig-extensions.yang /home/ubuntu/workspace/public/release/models/policy/openconfig-routing-policy.yang /home/ubuntu/workspace/public/release/models/types/openconfig-yang-types.yang /home/ubuntu/workspace/public/release/models/policy/openconfig-policy-types.yang /home/ubuntu/workspace/public/release/models/types/openconfig-types.yang /home/ubuntu/workspace/public/release/models/types/openconfig-inet-types.yang /home/ubuntu/workspace/public/release/models/interfaces/openconfig-interfaces.yang -o tree.txt
openconfig-interfaces.yang:11: error: module "ietf-interfaces" not found in search path
openconfig-policy-types.yang:11: error: module "ietf-yang-types" not found in search path

**Comment by robshakir** [comment]
Please read the pyang documentation. You'll need to use `-p` for pyang to specify where to find included modules - you don't need to list them all on the command line like this.

The IETF modules are not included in the OpenConfig repo -- you can get them from the github.com/YangModels/yang repo.
