### ISSUE TITLE
Adding the option to configure source address/interface for a DHCP relay agent

### ISSUE THREAD

**Issue by marius-ore** [openconfig/public#951]
In some scenarios when configuring DHCP relay, it can be useful to specify a source IP address or a source interface whose address is to be used as the source address in the messages relayed to a DHCP server. I don’t see a way to specify that in the current model for `relay-agent`, so I propose deprecating the leaf list `helper-address` from `/relay-agent/dhcp(v6)/interfaces/interface/(config|state)/` and replacing it with a list `helper-addresses` keyed by IP helper address and containing attribute `source`, which is a union of `inet:ip-address` and `oc-if:interface-id`

Change summary:
```
 module: openconfig-relay-agent
   +--rw relay-agent 
      +--rw dhcp
      |  +--rw interfaces
      |  |  +--rw interface* [id]
      |  |  |  +--rw id               -> ../config/id
      |  |  |  +--rw config
      |  |  |  |  +--rw id?                        oc-if:interface-id
-     |  |  |  |  +--rw helper-address*   inet:ip-address
+     |  |  |  +--rw helper-addresses
+     |  |  |  |  +--rw helper-address* [address]
+     |  |  |  |  |  +--rw address?     -> ../config/address
+     |  |  |  |  |  +--rw config
+     |  |  |  |  |  |  +--rw address?           string  //ip address or hostname
+     |  |  |  |  |  |  +--rw source?            union   // source ip address or interface identifier
+     |  |  |  |  |  +--ro state
+     |  |  |  |  |  |  +--ro address?           string  //ip address or hostname
+     |  |  |  |  |  |  +--ro source?            union   // source ip address or interface identifier
      +--rw dhcpv6
      |  +--rw interfaces
      |  |  +--rw interface* [id]
      |  |  |  +--rw id               -> ../config/id
      |  |  |  +--rw config
      |  |  |  |  +--rw id?                        oc-if:interface-id
-     |  |  |  |  +--rw helper-address*   inet:ipv6-address
+     |  |  |  +--rw helper-addresses
+     |  |  |  |  +--rw helper-address* [address]
+     |  |  |  |  |  +--rw address?     -> ../config/address
+     |  |  |  |  |  +--rw config
+     |  |  |  |  |  |  +--rw address?           inet:ipv6-address
+     |  |  |  |  |  |  +--rw source?            union   // ipv6 address or interface identifier
+     |  |  |  |  |  +--ro state
+     |  |  |  |  |  |  +--ro address?           inet:ipv6-address
+     |  |  |  |  |  |  +--ro source?            union   // ipv6 address or interface identifier
```
The ipv4 portion of my proposal includes a change of type, from `helper-address` with members of type `inet:ip-address` to `address` of type `string`, in order to allow specifying a named DHCP server as IP helper.

**Comment by marius-ore** [comment]
Configuration examples:

Arista:  https://www.arista.com/en/um-eos/eos-ipv4#xx1144379

Junos (source interface): https://www.juniper.net/documentation/us/en/software/junos/subscriber-mgmt-sessions/topics/ref/statement/relay-source-edit-forwarding-options.html

HPE FlexNetwork (source IP address), "Specifying the source IP address for relayed DHCP requests" in _Configuring the DHCP relay agent:_ https://techhub.hpe.com/eginfolib/networking/docs/switches/5130ei/5200-3942_l3-ip-svcs_cg/content/index.htm

**Comment by marius-ore** [comment]
Are there any opinions on this? Any things I should change/alternative proposals?

I am also considering changing the proposal slightly to have the newly added leaf `/relay-agent/dhcpv6/interfaces/interface/helper-addresses/helper-address/config/helper-address` to also be just `string` instead of `inet:ipv6-address` (just like in the v4 case), in order to allow for named DHCP servers with ipv6 addresses to be added as ipv6 helpers by their host name. While I am not aware of existing examples of configuring an ipv6 helper address by host name, I think it's something that may be supported in the future and perhaps could be good to add here for feature parity with ipv4.

**Comment by dplore** [comment]
Here is a reference to [Cisco IOS ip dhcp-relay source-interface](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipaddr_dhcp/configuration/15-sy/dhcp-15-sy-book/dhcp-relay-svr-option-82.html#GUID-4AF995F3-68E4-4EC3-B03D-B9896306ADC1).

The use case to specify source address seems widely supported and not currently modeled in OC.  

I don't see broad support for configuring multiple different source addresses.  

I'd prefer to stick with using `inet:ip-address`.  I don't see precedent in OC to introduce hostnames for destinatons.

Care to send a pull request for the yang and there can be more review?
