### ISSUE TITLE
Queries regarding Encapsulate-Gre (OC-NI)

### ISSUE THREAD

**Issue by ManojKumar002** [openconfig/public#952]
Hi @aashaikh ,

My name is Manoj Kumar (Company:Juniper Networks)
We have some questions regarding the Encapsulate-Gre in openconfig-network-instances(OC-NI) model.

In the OC-NI model the xpath "/openconfig-network-instance/network-instances/network-instance/policy-forwarding/policies/policy/rules/rule/action/encapsulate-gre/targets" is a list, where multiple 'target' can be configured with different set of source and destination address for a single 'rule'.

But in Juniper networks for single rule only one encapsulation is allowed.

My questions are:
    1. What is the purpose of configuring the multiple targets for a single rule ?
    2. Instead of configuring the source and destination addresses under each and every rule, why can't we configure the 'target' separately and reuse it in different rules? This would be an efficient way to handle repeated source and destination address sets.

Thanks and Regards,
Manoj Kumar

**Comment by dplore** [comment]
Multiple targets means more than one GRE destination can be configured.  This is used for load balancing flows into multiple GRE 'tunnels'.  

I think it's possible to refactor the module, but there would need to be some operational use case showing that the current schema is broken and/or not scaling to solve a real operational use case.
