### ISSUE TITLE
Behaviour of `bgp-actions/set-community` is unclear when `method` is unset.

### ISSUE THREAD

**Issue by wenovus** [openconfig/public#963]
The leaf [/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/config/method](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-routing-policy.html#routing-policy-policy-definitions-policy-definition-statements-statement-actions-bgp-actions-set-community-config-method) doesn't have a default value: https://github.com/openconfig/public/blob/5d38d8531ef9c5b998262207eb6dbdae8968f9fe/release/models/bgp/openconfig-bgp-policy.yang#L744-L756

Say both [INLINE](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-routing-policy.html#routing-policy-policy-definitions-policy-definition-statements-statement-actions-bgp-actions-set-community-inline-config-communities) and [REFERENCE](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-routing-policy.html#routing-policy-policy-definitions-policy-definition-statements-statement-actions-bgp-actions-set-community-reference-config-community-set-ref) community values are specified, what then should be the expected behaviour when `method` is unset?

Some ideas:
* (**perhaps the most reasonable**) Don't change the model (just add a comment), simply ignore both INLINE and REFERENCE configurations if they are set.
* Remove `method`, and always union\* the communities specified by both INLINE and REFERENCE.
* Specify INLINE or REFERENCE as the default.
* Don't change the model (just add a comment), interpret UNSET to mean union\*

\* my understanding of BGP is that since community values are transitive, then de-duplicating repeated communities is safe; however I could be wrong here and if so the union would just mean appending all of the specified community values from both lists.

**Comment by dplore** [comment]
I am not sure if this leaf is needed?  If there is an inline community-set defined, then it should be used?  

(/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline/config/communities)

If a reference is configured, it should be used
(/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference/config/community-set-ref)

If they are both set, then yes, that is probably not expected.  But it would be safe to merge them.  

I would not expect an implementation to support both INLINE and REFERENCE simultaneously.

**Comment by wenovus** [comment]
In that case I'm also leaning towards the merging behaviour.

Since this is a low-priority issue in practice, I'll leave this issue open for OC stakeholders to decide and then update the description string.

**Comment by dplore** [comment]
Another option brought up by @oscargdd is to make this leaf mandatory.  This will force the user to pick one of the enums removing any ambiguity of which method to use.

**Comment by wenovus** [comment]
That sounds like a good idea. I see this being used in the OpenConfig
models elsewhere although it is not common. It is also not enforced by ygot
during validation currently but it can be easily implemented if need be.

  Wen

**Comment by dplore** [comment]
+1, please submit PR to make this leaf mandatory.

**Comment by wenovus** [comment]
> +1, please submit PR to make this leaf mandatory.

Apologies, looking at the YANG definition for the `inline` and `reference` containers, I see a `when` statement qualifying them such that the config is invalid when `mode` is not set:

https://github.com/openconfig/public/blob/5d38d8531ef9c5b998262207eb6dbdae8968f9fe/release/models/bgp/openconfig-bgp-policy.yang#L798-L802

https://github.com/openconfig/public/blob/5d38d8531ef9c5b998262207eb6dbdae8968f9fe/release/models/bgp/openconfig-bgp-policy.yang#L857-L861

Therefore, addressing the title of this issue, there is actually no confusion about what happens when `method` is unset: any configuration in `inline` and `reference` is invalid.

Furthermore, I do not believe mandatory makes sense: In OC we don't have presence containers, which means that if mandatory, this leaf must be configured, even if there was no intention to configure any set-community:
https://www.rfc-editor.org/rfc/rfc7950#section-7.6.5

Since the title of the issue is resolved, and the model looks good as it is, I will close this issue, thanks for the comments, I'll take a closer look at the model next time to spot `when` statements.

Aside: it would be useful if ygot were to support `when` statements so that this check is available programmatically.
