### ISSUE TITLE
 send-community leaf under neighbor and peer-group afi-safi list

### ISSUE THREAD

**Issue by sundaramtirunel** [openconfig/public#969]
Hi all,

Pursuant to the idea floated in #809 and #843 [@missaesasaya], we would like to bring in a change regarding send-community leaf under neighbor and peer-group afi-safi list.
Its a welcome move and help us adopt this leaf very easily.
But the leaf got added under global afi-safi list. 
We need to move the leaf to neighbor and peer-group afi-safi list. The grouping name is `bgp-common-mp-afi-safi-config`.

Thanks,
Sundaram T R

**Comment by missaesasaya** [comment]
I have opened a PR for this change: #976
