### ISSUE TITLE
openconfig-isis: redundant "enabled" leaf under ISIS levels?

### ISSUE THREAD

**Issue by kavitharp** [openconfig/public#97]
Hello, 

What is the use for the enabled leaf under protocols/protocol/isis/levels/level/config/enabled.
There is a leaf called level-capability under : protocols/protocol/isis/global/config/. Level-capability says what level/s the given ISIS instance should operate at. I think the enabled flag under the levels container and the level-capability maybe stepping on each others toes here, IIUC.
Could you please clarify what is the purpose of level-capability and enabled leaf under level/config for ISIS?

Thanks, 
Kavitha

**Comment by robshakir** [comment]
Thanks -- I agree that this can be determined from the `level-capability` leaf. I'll remove this leaf in the next revision of the model and make the clarification that the `level-capability` should be used to determine whether a particular level is enabled.

**Comment by kavitharp** [comment]
Thanks!

**Comment by xw-g** [comment]
@robshakir do you still plan to do it or anything changed after last comment? cc: @dplore 

cc: @aredmon8551,  @nokia1adam, @rolandphung,  @aaronmillisor

**Comment by robshakir** [comment]
Created #794 to implement this.
