### ISSUE TITLE
Clarification regarding ospf graceful restart attributes

### ISSUE THREAD

**Issue by shashu89** [openconfig/public#980]
Hi,

I just wanted to confirm if my understanding regarding graceful restart attributes in openconfig is correct:

- enabled : This parameter enables Router to go to OSPF GR speaker mode
- helper-only : This parameter enables Router to go to OSPF GR helper mode ( helper-only seems misleading )
So, I believe these both are exclusive and when both are enabled, Router will be in both speaker and helper mode.

**Comment by dplore** [comment]
[/network-instances/network-instance/protocols/protocol/bgp/global/graceful-restart/config/helper-only](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-network-instance.html#network-instances-network-instance-protocols-protocol-bgp-global-graceful-restart-config-helper-only)

From my interpretation I think helper-only means the target device should only implement [section 4.2 of RFC4724 ](https://datatracker.ietf.org/doc/html/rfc4724#section-4.2)

Hence, the target behaves only as a receiver/listener of graceful restart.  The target would not support retaining forwarding when it's own BGP process restarts.  Seems relatively clear in the doc?

**Comment by shashu89** [comment]
Thanks for your response. So these definitions are correct?
enabled : This parameter enables Router to go to OSPF GR speaker mode
helper-only : This parameter enables Router to go to OSPF GR listener mode

**Comment by dplore** [comment]
Yes, this is my interpretation.  I welcome any other comments.
