### ISSUE TITLE
Question regarding revision 2.13.0 of openconfig-if-ethernet.yang

### ISSUE THREAD

**Issue by Namratha-pn** [openconfig/public#984]
Hi,

I wanted to confirm on the revision 2.13.0 in openconfig-if-ethernet.yang.
https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-if-ethernet.yang#L29

To our understanding, this is making ethernet parameters available on the LAG interfaces. Why is it so when the model is specific to ethernet interfaces? And which of the leaves is must for the LAG interfaces?

Thanks,
Namratha

**Comment by Namratha-pn** [comment]
Hi Team,

Any update on the queries? 

Thanks,
Namratha

**Comment by dplore** [comment]
Hi Namratha,  you can see motivation for this change via pull request here: https://github.com/openconfig/public/pull/830.

As far as which leaves are a must, it does look like quite a few of the Ethernet leaves are specific to individual Ethernet ports and are not applicable to an aggregate interface.

One way to address this is to refactor this change to break up the openconfig-if-ethernet model into  groupings which are relevant to an aggregate interface and those which are not.    Do you have any other suggestions?

**Comment by Namratha-pn** [comment]
Hi Darren,

Thanks for the response.
Yes adding different groupings for ethernet and aggregate/LAG interface under openconfig-if-ethernet model could help in addressing the issue and the specific  groupings could include the relevant content. 
The LAG grouping could be made available for type LAG interfaces and Ethernet grouping for type  Ethernet interfaces.

Thanks,
Namratha
