### ISSUE TITLE
openconfig-isis.yang: lsp-pacing-interval description is wrong

### ISSUE THREAD

**Issue by ghankins** [openconfig/public#99]
oc-ext:openconfig-version "0.3.3";

    leaf lsp-pacing-interval {
      type uint64;
      units milliseconds;
      description
        "The interval interval in milliseconds between the
        detection of topology change and when the SPF algorithm runs.";
    }

**Comment by 3alexb** [comment]
ack. will change:
    leaf lsp-pacing-interval {
      type uint64;
      units milliseconds;
      description
        "The interval in milliseconds during which LSPs are sent from interface.";
    }

**Comment by matt-arrcus** [comment]
Still wrong in https://github.com/openconfig/public/blob/master/release/models/isis/openconfig-isis.yang 

The pacing interval is not an SPF delay.  It's a rate limit on the transmission of LSPs on a specific IS-IS interface.
